### ISSUE TITLE
Failing in io.js?

### ISSUE THREAD

**Issue by callumacrae** [sass/node-sass#706] opened 2015-02-25 17:34 UTC
I'm getting an error when I try to run gulp-sass on io.js, and it looks like the problem is in either io.js itself, or node-sass (not sure which).

Here's the error on travis:

https://travis-ci.org/Lostmyname/lmn-gulp-tasks/jobs/52152492

And here's the error locally:

```
  scss
    1) should parse simple scss
    - should parse simple sass
    2) should parse simple scss with minify false
    3) should handle node_modules imports
    4) should be autoprefixed
    5) should check for "../node_modules"
    6) …unless you skip it
    7) should check for "../node_modules"


  0 passing (110ms)
  1 pending
  7 failing

  1) scss should parse simple scss:
     Error: `libsass` bindings not found. Try reinstalling `node-sass`?
      at getBinding (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/index.js:3:17)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at require.requireFn (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/index.js:8:12)
      at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-load-plugins/index.js:56:18)
      at scssTask (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/tasks/scss.js:19:20)
      at Context.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:32:7)
      at Test.Runnable.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:218:15)
      at Runner.runTest (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  2) scss should parse simple scss with minify false:
     Error: `libsass` bindings not found. Try reinstalling `node-sass`?
      at getBinding (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/index.js:3:17)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at require.requireFn (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/index.js:8:12)
      at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-load-plugins/index.js:56:18)
      at scssTask (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/tasks/scss.js:19:20)
      at Context.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:61:7)
      at Test.Runnable.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:218:15)
      at Runner.runTest (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  3) scss should handle node_modules imports:
     Error: `libsass` bindings not found. Try reinstalling `node-sass`?
      at getBinding (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/index.js:3:17)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at require.requireFn (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/index.js:8:12)
      at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-load-plugins/index.js:56:18)
      at scssTask (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/tasks/scss.js:19:20)
      at Context.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:75:7)
      at Test.Runnable.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:218:15)
      at Runner.runTest (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  4) scss should be autoprefixed:
     Error: `libsass` bindings not found. Try reinstalling `node-sass`?
      at getBinding (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/index.js:3:17)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at require.requireFn (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/index.js:8:12)
      at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-load-plugins/index.js:56:18)
      at scssTask (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/tasks/scss.js:19:20)
      at Context.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:89:7)
      at Test.Runnable.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:218:15)
      at Runner.runTest (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  5) scss should check for "../node_modules":
     Error: done() called multiple times
      at Test.Runnable (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:92:3)
      at context.describe.context.context (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:21:1)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Function.Module.runMain (module.js:487:10)
      at startup (node.js:111:16)
      at node.js:799:3

  6) scss …unless you skip it:
     Error: `libsass` bindings not found. Try reinstalling `node-sass`?
      at getBinding (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-sass/index.js:3:17)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at require.requireFn (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/index.js:8:12)
      at Object.defineProperty.get (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/gulp-load-plugins/index.js:56:18)
      at scssTask (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/tasks/scss.js:19:20)
      at Context.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:114:7)
      at Test.Runnable.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:218:15)
      at Runner.runTest (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:374:10)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:299:14)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:248:23)
      at Immediate._onImmediate (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  7) scss should check for "../node_modules":
     Error: done() called multiple times
      at Test.Runnable (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:92:3)
      at context.describe.context.context (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/test/scss.js:21:1)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Module.require (module.js:351:17)
      at require (module.js:370:17)
      at /Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/Users/callumacrae/Sites/lmn/lmn-gulp-tasks/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:446:26)
      at Object.Module._extensions..js (module.js:464:10)
      at Module.load (module.js:341:32)
      at Function.Module._load (module.js:296:12)
      at Function.Module.runMain (module.js:487:10)
      at startup (node.js:111:16)
      at node.js:799:3
```

I have no idea what is causing it, but it only happens on io.js—my tests are fine on both node 0.10 and node 0.12.

**Comment by am11** [comment] 2015-02-25 18:06
Use io.js v1.2 instead of v1.3 with node.js v2.0.1.

Duplicate of #703, #699 and #694.

**Closed by am11** 2015-02-25 18:06 UTC
Labels: Duplicate

**Comment by callumacrae** [comment] 2015-02-26 11:13
Of course people are going to make duplicate issues if you keep closing them without documenting that you don't support the latest version of something!

Are you working on a fix?

**Comment by am11** [comment] 2015-02-26 11:16
Github 101: First search the issue tracker if someone else has reported the issue or if it is already fixed, then file a new issue.

> Are you working on a fix?

This is already fixed. See #694. Hang tight for vNext.
