### ISSUE TITLE
Windows: Error: The specified procedure could not be found. (node v0.12)

### ISSUE THREAD

**Issue by akuseru** [sass/node-sass#656] opened 2015-02-09 23:10 UTC
node-sass appears to install fine, but fails to run on node 0.12. here are the outputs from the installation test script I saw in another thread:

```
PS C:\temp1> npm -v
2.5.1
PS C:\temp1> node -v
v0.12.0
PS C:\temp1> node -p process.versions
{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }
PS C:\temp1> node -p process.platform
win32
PS C:\temp1> node -p process.arch
x64
PS C:\temp1>npm install node-sass
-
> node-sass@2.0.0-beta install C:\temp1\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\temp1\node_modules\node-sass\vendor\win32-x64\binding.node

> node-sass@2.0.0-beta postinstall C:\temp1\node_modules\node-sass
> node scripts/build.js

node-sass@2.0.0-beta node_modules\node-sass
├── get-stdin@3.0.2
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── nan@1.6.2
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── shelljs@0.3.0
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── meow@2.1.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.0)
├── gaze@0.5.1 (globule@0.1.0)
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.2
6.3)
└── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4,
 oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, qs@2.3.3, node-uuid@1.4.2, combined-stream@0.0.7, form-data@0.2.0
, mime-types@2.0.8, http-signature@0.10.1, bl@0.9.4, tough-cookie@0.12.1, hawk@2.3.1)

PS C:\temp1> node -p "console.log(require('node-sass').info())"
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.
C:\temp1\node_modules\node-sass\vendor\win32-x64\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\temp1\node_modules\node-sass\lib\index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

PS C:\temp1> cd node_modules\node-sass\vendor
PS C:\temp1\node_modules\node-sass\vendor> rm .\win32-x64\binding.node
PS C:\temp1\node_modules\node-sass\vendor> node -p "console.log(require('node-sass').info())"
C:\temp1\node_modules\node-sass\lib\index.js:21
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\temp1\node_modules\node-sass\lib\index.js:21:11)
    at Object.<anonymous> (C:\temp1\node_modules\node-sass\lib\index.js:211:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:74:17)
PS C:\temp1\node_modules\node-sass\vendor>
```

This issue appears to be specific to node 0.12, going back to 10.36 appears to fix this problem.

**Comment by am11** [comment] 2015-02-10 07:02
Next version of node-sass will support node v0.12.
Duplicate of https://github.com/sass/node-sass/issues/653.

**Closed by am11** 2015-02-10 07:02 UTC
Labels: Duplicate

**Comment by akuseru** [comment] 2015-02-11 05:28
ah thanks for the info.
