### ISSUE TITLE
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.

### ISSUE THREAD

**Issue by Rqcker** [sass/node-sass#3185] opened 2021-09-27 15:09 UTC
I am trying to use yarn and react to call my website locally for testing. As a result, I encountered a version incompatibility problem. I tried many methods and suggestions on the Internet to reinstall the 4.14.1 version of sass. But it doesn't work.

My npm version is 7.24.1
The version of node is 16.10.0
The version of yarn is 1.22.1
Firefox's version is 91.0.2
The platform used is manjaro21 of ArchLinux

The screenshot of the problem is as follows:

![image](https://user-images.githubusercontent.com/20661419/134935244-2cb420c1-3944-4ad6-ba31-1a3296ce7657.png)

The error message is as follows:

```
Failed to compile.

./src/style/main.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/style/main.scss)
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.
```

**Comment by nschonni** [comment] 2021-09-27 15:14
Duplicate of #3103

**Closed by nschonni** 2021-09-27 15:14 UTC

**Comment by pablomongo** [comment] 2021-12-04 11:55
I have the same problem. Could you solve it?

**Comment by EFF** [comment] 2022-01-14 02:29
> I have the same problem. Could you solve it?

Duplicate of https://github.com/sass/node-sass/issues/3103 , I guess you'd find your answer there

**Comment by zhaochengxian** [comment] 2022-02-24 06:12
i just want to say ,the node-sass is so sluck(goushi),when i update the node,it error  6.0.1 is incompatible with ^4.0.0, i try the most way to solve it ,it still error ,fuck

**Comment by Sarra-94** [comment] 2022-05-27 10:39
Please, anyone, get the solution for this problem?

**Comment by qirong77** [comment] 2022-06-28 14:09
For me , this problem was solved by installing nvm(a tool for node version management). in my mac, my node version was 16.17 and I also install node 10.13 by nvm .when I install depended packages I use the old node version 10.13 and it works. In my opinion, this issue due to the different version of node, you can just use a low version of node.
