### ISSUE TITLE
Fails to compile arithmetic on result of map-get

### ISSUE THREAD

**Issue by akiellor** [sass/node-sass#1966] opened 2017-05-13 04:16 UTC
- NPM version: 3.10.10
- Node version: v6.10.0
- Node Process:
```
{ http_parser: '2.7.0',
  node: '6.10.0',
  v8: '5.1.281.93',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```
- Node Platform: linux
- Node architecture: x64
- node-sass version:
```
node-sass	4.5.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
- npm node-sass versions (`npm ls node-sass`): 4.5.2

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

Minimal reproducible scenario:

```
root@f55809ebd5c9:/usr/src/app# node-sass <<EOS
\$map-spaces: (
  xs: 3rem / 16
);
\$var: map-get(\$map-spaces, 'xs') * 5;

.size {
  height: \$var;
}
EOS
{
  "status": 1,
  "file": "stdin",
  "line": 4,
  "column": 7,
  "message": "Undefined operation: \"3rem/16 times 5\".",
  "formatted": "Error: Undefined operation: \"3rem/16 times 5\".\n        on line 4 of stdin\n>> $var: map-get($map-spaces, 'xs') * 5;\n   ------^\n"
}
```

This example works fine in https://www.sassmeister.com/ and outputs the following:
```
.size {
  height: 0.9375rem;
}
```

**Comment by nschonni** [comment] 2017-05-16 16:32
Can you file an issue with https://github.com/sass/libsass/issues and link it back here, thanks!

**Comment by xzyfer** [comment] 2017-05-16 16:41
This is already fixed on LibSass master and will be in node-sass on the next bump.

**Comment by gauthierm** [comment] 2017-12-12 16:20
What's the ETA for this fix? libsass 3.5.0.beta.3 was released in February and `node-sass` is still using 3.5.0.beta.2 containing the bug.

**Comment by gauthierm** [comment] 2017-12-12 16:21
https://github.com/sass/libsass/issues/2309 is the fixed issue in libsass.

**Comment by gauthierm** [comment] 2017-12-19 12:47
https://github.com/sass/node-sass/issues/1935 is a duplicate of this issue.

**Comment by nschonni** [comment] 2017-12-20 04:09
Duplicate of #1935

**Closed by nschonni** 2017-12-20 04:09 UTC
Labels: External - LibSass
