### ISSUE TITLE
Azure DevOps .Net Core Build Task fails. Cannot download win32-x64-72_binding.node

### ISSUE THREAD

**Issue by ohdihe** [sass/node-sass#2781] opened 2019-11-09 21:25 UTC
The win32-x64-64_binding.node cannot be found when the .Net Core build tasks tries to download the binding.node from 
https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-72_binding.node. 
And I think this is why the task is failing to build to solution.

When I try to access the link, I see a 404. Did someone remove the binding.node file?

output code below

[section]Starting: Build
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.158.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
[command]C:\windows\system32\chcp.com 65001
Active code page: 65001
[command]"C:\Program Files\dotnet\dotnet.exe" build D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj...
  Restoring packages for D:\a\1\s\src\PartsUnlimited.Models\PartsUnlimited.Models.csproj...
  Restore completed in 1.02 sec for D:\a\1\s\src\PartsUnlimited.Models\PartsUnlimited.Models.csproj.
  Restore completed in 1.02 sec for D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj.
  Restoring packages for D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj...
  Restore completed in 284.83 ms for D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj.
  
  > node-sass@3.13.1 install D:\a\1\s\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
  > node scripts/install.js
  
  Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-72_binding.node
  Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-72_binding.node": 
  
  HTTP error 404 Not Found
  
  Hint: If github.com is not accessible in your location
        try setting a proxy via HTTP_PROXY, e.g. 
  
        export HTTP_PROXY=http://example.com:1234
  
  or configure npm proxy via
  
        npm config set proxy http://example.com:8080
  
  > node-sass@4.11.0 install D:\a\1\s\src\PartsUnlimitedWebsite\node_modules\node-sass
  > node scripts/install.js
  
  Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
  Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node": 
  
  HTTP error 404 Not Found
  
  Hint: If github.com is not accessible in your location
        try setting a proxy via HTTP_PROXY, e.g. 
  
        export HTTP_PROXY=http://example.com:1234
  
  or configure npm proxy via
  
        npm config set proxy http://example.com:8080
  
  > node-sass@3.13.1 postinstall D:\a\1\s\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
  > node scripts/build.js

**Comment by nschonni** [comment] 2019-11-10 01:12
Duplicate of #2779 
404 issues are also explained in the issue template and troubleshooting guide

**Closed by nschonni** 2019-11-10 01:12 UTC

**Comment by ohdihe** [comment] 2019-11-10 01:58
Thanks!
