### ISSUE TITLE
Where is the win32-x64-59_binding.node？

### ISSUE THREAD

**Issue by baihech** [sass/node-sass#2132] opened 2017-11-02 10:39 UTC
I can't install "node-sass": "4.5.3" by npm.
```
> node-sass@4.5.3 install C:\git\static-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found
```

**Comment by ox-michaelradionov** [comment] 2017-11-02 10:58
I have the same error for linux `linux_musl-x64-59_binding.node`:

```
> node-sass@4.5.3 install /builds/CEVP/cevp-web/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux_musl-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux_musl-x64-59_binding.node": 

HTTP error 404 Not Found
```

**Comment by ox-michaelradionov** [comment] 2017-11-02 11:01
@baihech , seems like a duplicate. See this issue: https://github.com/sass/node-sass/issues/2129
Solution would be to downgrade the node to v8

**Comment by baihech** [comment] 2017-11-02 11:34
@ox-michaelradionov I' try.

**Comment by nschonni** [comment] 2017-11-02 14:25
Duplicate of https://github.com/sass/node-sass/issues/2129

**Closed by nschonni** 2017-11-02 14:25 UTC
