### ISSUE TITLE
Support for index Sass or SCSS File

### ISSUE THREAD

**Issue by sarsamurmu** [sass/node-sass#2749] opened 2019-10-10 14:23 UTC
In Dart Sass, we can import a directory and the import takes the index.scss or index.sass file from the directory. Like if I use `@import "directory"` in Sass, Dart Sass will try to import `directory/index.{sass, scss}`. Can we get a similar feature like that? This feature will be really useful.

**Comment by nschonni** [comment] 2019-10-10 16:51
Duplicate of #2339

**Closed by nschonni** 2019-10-10 16:51 UTC
