### ISSUE TITLE
Why the precision option change string values and not just the integer values?

### ISSUE THREAD

**Issue by Karklis** [sass/node-sass#1530] opened 2016-05-05 22:41 UTC
I started using scss from [font-awesome](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss).  
The node-sass default precision is 5
The length of the icon strings is 5

If you change the precision to lower than 5, e.g. 3, you lost your icons info, but if you leave the precision to the default value nothing change. My question is:

Why the precision option change string values and not just the integer values?

My ENV
- Nodejs 6, Grunt, [grunt-sass](https://github.com/sindresorhus/grunt-sass), windows.

**Comment by xzyfer** [comment] 2016-05-10 10:33
I an unable to reproduce this. Please provide a copy-pastable reproduction.

**Comment by Karklis** [comment] 2016-05-10 16:51
I trying to reproduce the behavior again, but without success. After some searching I think there is a link between [https://github.com/sass/sass/issues/1395](https://github.com/sass/sass/issues/1395) about the output codification and https://github.com/sass/node-sass/issues/1095 that generate some condition not everytime. For watching files I use grunt-contrib-watch with connect-livereload.

**Comment by xzyfer** [comment] 2016-05-15 03:49
Closing this since it appears to be a Sass language feature request.

**Closed by xzyfer** 2016-05-15 03:49 UTC
Labels: Awaiting Response, Bug - Maybe
