### ISSUE TITLE
File to read not found or unreadable

### ISSUE THREAD

**Issue by mayate** [sass/node-sass#1140] opened 2015-09-12 19:28 UTC
Hello everyone.

i have just installed node-sass on a windows machine im using thru VPN.
i have it installed on my mac and everything works great but when i installed
it on the windows machine thru vpn i get this error when i try to save/compile
an .sass file.

FILE:
undefined
 
ERROR:
File to read not found or unreadable: \\filesrv91.gaia.local\Public\UserMappar\Mayate\Documents\Visual Studio 2012\Projects\BendersLageradmin\BendersLageradmin\css\styles.sass
 
LINE:    undefined
COLUMN:  undefined

anyone know how to solve this issue? i cant use sass in VS2012 so i rather
use Atom and node-sass to do my css work for the asp.net application.

this is my output line: // out: styles.css,; compress: false

please help me im going nuts doing my sass in osX to tab over to my
rdc to paste and save the css output there.

**Comment by saper** [comment] 2015-09-12 20:20
Can you go through our 

Besides - you cannot use Atom with node-sass, we don't support that. You can use node releases 0.10, 0.12, 4.0 and io.js up to 3.0.

Another thing: you seem to be using UNC path (Windows network path) `\\filesrv91.gaia.local\Public\UserMappar\Mayate\Documents\Visual Studio 2012\Projects\BendersLageradmin\BendersLageradmin\css\styles.sass` - this may not work as expected.

**Comment by mayate** [comment] 2015-09-12 21:58
Hello Saper.

What do you mean i cant use node-sass with atom? i downloaded an atom package that uses node-sass? [sass autocompile](https://atom.io/packages/sass-autocompile)

I have now gone through the troubleshooting.md guide. and here are the results:

```
npm -v = 2.14.2
node -v = v4.0.0
node -p process.versions =
{
  http_parser: 2.5.0
  node: 4.0.0
  v8: 4.4.103.30
  uv: 1.7.3
  zlib: 1.2.8
  ares: 1.10.1-DEV
  modules: 46
  openssl: 1.0.2d
}
node -p process.platform = win32
node -p process.arch = x64
node-sass --version = 
node-sass   3.3.2    wrapper    javascript
libsass    3.2.5    sass-compiler    c/c++
node -p "console.... = the same as above.
```

install seems to be sucessful since the .err file ended with ok.

thank you so much for that quick respond. I really need to get this to work for me :)

**Comment by saper** [comment] 2015-09-12 22:03
On Sat, 12 Sep 2015, mayate wrote:

> What do you mean i cant use node-sass with atom? i downloaded an atom package that uses node-sass? [sass autocompile](https://atom.io/packages/sass-autocompile)

Quoting the page above: ^^

> At the moment, you can only use this package when you install node.js
> and node-sass on you system. It's important that you install node-sass
> globally (command: npm install node-sass -g), so it's possible to
> access it via CLI.

So it just does the trick - it calls real node js (not atom) and uses node-sass
CLI script.


> I have now gone through the troubleshooting.md guide. and here are the results:
> 
> ```
> npm -v = 2.14.2
> node -v = v4.0.0
> node -p process.versions =
> {
>   http_parser: 2.5.0
>   node: 4.0.0
>   v8: 4.4.103.30
>   uv: 1.7.3
>   zlib: 1.2.8
>   ares: 1.10.1-DEV
>   modules: 46
>   openssl: 1.0.2d
> }
> node -p process.platform = win32
> node -p process.arch = x64
> node-sass --version = 
> node-sass   3.3.2    wrapper    javascript
> libsass    3.2.5    sass-compiler    c/c++
> node -p "console.... = the same as above.
> ```
> 
> install seems to be sucessful since the .err file ended with ok.

Yes, everything above seems fine. Can we close this?

**Comment by mayate** [comment] 2015-09-12 22:12
The problem maintains.

I had node js installed the whole time i forgot to write that in the first post so i didn't try to run node-sass through Atom but i use it in Atom, sorry for the ambiguity but i'm from Sweden so what can i say to my defense :) 

then it has to be a problem because i use it on a vpn client machine?

**Comment by saper** [comment] 2015-09-12 22:15
> The problem maintains.
> 
> I had node js installed the whole time i forgot to write that in the first post so i didn't try to run node-sass through Atom but i use it in Atom, sorry for the ambiguity but i'm from Sweden so what can i say to my defense :) 
> 
> then it has to be a problem because i use it on a vpn client machine?

Sorry, I don't understand what the problem is.

**Comment by mayate** [comment] 2015-09-12 22:36
the problem is that when i try to save an .sass file in atom i get this error back from node-sass:

```
FILE:
undefined

ERROR:
File to read not found or unreadable: \filesrv91.gaia.local\Public\UserMappar\Mayate\Documents\Visual Studio 2012\Projects\BendersLageradmin\BendersLageradmin\css\styles.sass

LINE: undefined
COLUMN: undefined
```

**Comment by saper** [comment] 2015-09-12 22:40
> the problem is that when i try to save an .sass file in atom i get this error back from node-sass:

This has nothing to do with node-sass. Try not to use UNC paths (\\server\directory).

You can map a network drive for example to avoid that.

**Comment by mayate** [comment] 2015-09-12 22:45
Thank you saper.

ok then i have to figure out how to do that. i thank you very much for all the help anyways. and i have to say that local on my mac i love it, could not live without it. Thats why this is so disturbing.

are you the author of this awesome stuff?

**Closed** 2015-09-12 23:14 UTC
