### ISSUE TITLE
'libsass bindings not found. Try reinstalling 'node-sass'?

### ISSUE THREAD

**Issue by Milkbone** [sass/node-sass#918] opened 2015-05-01 14:23 UTC
I'm having a problem when running the command `gulp` I keep getting this error:
```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/vagrant/Code/Auth/node_modules/gulp-sass/node_modules/n
ode-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/gulp-sass/node_m
odules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/gulp-sass/index.
js:3:17)
    at Module._compile (module.js:456:26)
```
below is my package.json file:
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^0.0.7",
    "gulp-sass": "^2.0.0-alpha.1",
    "gulp-util": "^3.0.4",
    "laravel-elixir": "*"
  }
}
```
anyone have any ideas or thoughts on what could be going on?

**Comment by saper** [comment] 2015-05-01 15:06
Which node? Which npm? Which platform, operating system?

**Comment by xzyfer** [comment] 2015-05-04 07:31
Please follow the relevant in our [Troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and reply if the problem persists.

**Comment by Milkbone** [comment] 2015-05-05 00:23
ran through all the steps on the troubleshooting guide, and have provided the results below.
```
npm -v: 2.7.4
node -v: v0.12.2
node -p process.versions: { http_parser: '2.3',
						  node: '0.12.2',
						  v8: '3.28.73',
						  uv: '1.4.2-node1',
						  zlib: '1.2.8',
						  modules: '14',
						  openssl: '1.0.1m' }
node -p process.platform: win32
node -p process.arch: x64
.\node_modules\.bin\node-sass --version: 2.1.1
```
I'm still having this issue, hopefully we can get it resolved.

**Comment by saper** [comment] 2015-05-05 00:25
Running `npm install` as root?

**Comment by Milkbone** [comment] 2015-05-05 00:28
Yes, even when installing from root, the problem still occurs.

**Comment by saper** [comment] 2015-05-05 00:32
Can you post a complete log to gist.github.com?

Can you try as a non-root user?

**Comment by Milkbone** [comment] 2015-05-05 00:41
can't seem to find any log files to copy over. I've tried as both non-root and root.

**Comment by saper** [comment] 2015-05-05 00:49
Do you have a `vendor` subdirectory under `node-sass`? If yes, what's there?

**Comment by Milkbone** [comment] 2015-05-05 01:20
there is a ```win32-x64-node-0.12``` file, and in that is ```binding.node``` thats everything thats under the ```vendor``` file.

**Comment by chrishomer** [comment] 2015-05-05 04:09
We ran into this when upgrading from 0.10.x to 0.12.2. Fixed by deleting the node_modules directory and  then reinstalling from scratch with ```npm install```.

**Comment by xzyfer** [comment] 2015-05-05 11:40
@Milkbone since `.\node_modules\.bin\node-sass --version` isn't producing an error node-sass has installed fine. The appears to be with the version of gulp-sass you're using.

I can't find any reference to `gulp-sass@^2.0.0-alpha.1`. Please try a stable version.

**Comment by Milkbone** [comment] 2015-05-05 17:41
Thanks for the extended support with this everyone, I really appreciate it. I searched through the ```gulp-sass``` github-discussion and it seems like ```gulp-sass 1.3.3``` was one of the most stable builds available. I used ```npm uninstall gulp-sass``` then, ```npm install gulp-sass@1.3.3 --save-dev``` then ssh'd back into my vagrant/homestead vm and ran ```gulp``` and still received the following error 
```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/vagrant/Code/Auth/node_modules/node-sass/lib/index.js:2
2:11)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/node-sass/lib/in
dex.js:188:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/gulp-sass/index.
js:3:17)
    at Module._compile (module.js:456:26)
```

**Comment by saper** [comment] 2015-05-05 18:16
So, do I understand this correctly - `node-sass` installed fine, it only happens when you run `gulp'?

Can you try running `home/vagrant/Code/Auth/node_modules/node-sass/bin/node-sass` and process some very simple document, like `/* ..... */`

**Comment by Milkbone** [comment] 2015-05-05 18:21
Correct, everything installs with no errors. one I run ```gulp``` I get the error, do you think it could be a problem with gulp? and sure I can try and display the results here.

**Comment by saper** [comment] 2015-05-05 18:25
On Tue, 5 May 2015, Milkbone wrote:

> Correct, everything installs with no errors. one I run ```gulp``` I get the error, do you think it could be a problem with gulp? and sure I can try and display the results here.

Most probably you have some node_modules with an older/wrong node-sass somewhere down there, and gulp pickes up that.

You can try

     node -e "console.log(require.resolve('node-sass'))"

to see where you current node-sass is.

**Comment by Milkbone** [comment] 2015-05-05 18:35
here's what I get when I run that, it seems to the correct install
```
\Projects\Auth> node -e "console.log(require.resolve('node-sass'))"

\Projects\Auth\node_modules\node-sass\lib\index.js
```

**Comment by saper** [comment] 2015-05-05 18:39
On Tue, 5 May 2015, Milkbone wrote:

> here's what I get when I run that, it seems to the correct install

> \Projects\Auth> node -e "console.log(require.resolve('node-sass'))"
> 
> \Projects\Auth\node_modules\node-sass\lib\index.js

And what is in the \Projects\Auth\node_modules\node-sass\vendor ?

Does \Projects\Auth\node_modules\node-sass\bin\node-sass work?

**Comment by Milkbone** [comment] 2015-05-05 18:51
``` Projects\Auth\node_modules\node-sass\vendor\win32-x64-node-0.12 ```inside that is ```binding.node```.

and no just running ```\Projects\Auth\node_modules\node-sass\bin\node-sass``` does not work, maybe im not understanding what your asking exactly? my apologize.

**Comment by saper** [comment] 2015-05-05 18:54
On Tue, 5 May 2015, Milkbone wrote:

> ``` Projects\Auth\node_modules\node-sass\vendor\win32-x64-node-0.12 ```inside that is ```binding.node```.
> 
> and no just running ```\Projects\Auth\node_modules\node-sass\bin\node-sass``` does not work, maybe im not understanding what your asking exactly? my apologize.

Does not work? An error message? It does say nothing and just waits?

Can you just type /* .... */ and give it enter and ctrl-z ?

**Comment by Milkbone** [comment] 2015-05-05 18:55
here is whats I get 
```
\Projects\Auth> \Projects\Auth\node_modules\node-sass\bin\node-sass /* .... */
The system cannot find the path specified.
```

**Comment by saper** [comment] 2015-05-05 19:05
what about `\Projects\Auth\node_modules\node-sass\.bin\node-sass`

(with a dot before `bin`)

**Comment by Milkbone** [comment] 2015-05-05 19:17
```
Projects\Auth> \Projects\Auth\node_modules\node-sass\.bin\node-sass
The system cannot find the path specified.
```
same thing...

**Comment by saper** [comment] 2015-05-05 19:25
On Tue, 5 May 2015, Milkbone wrote:

> ```
> Projects\Auth> \Projects\Auth\node_modules\node-sass\.bin\node-sass
> The system cannot find the path specified.
> ```

What is below your \Projects\Auth\node_modules\node-sass ?

**Comment by Milkbone** [comment] 2015-05-05 19:32
this is whats in my node-sass file http://puu.sh/hCDmj/fef017598b.png

**Comment by saper** [comment] 2015-05-05 19:37
On Tue, 5 May 2015, Milkbone wrote:

> this is whats in my node-sass file http://puu.sh/hCDmj/fef017598b.png

Can you do

      cd \Projects\Auth\node_modules\
      dir node-sass /s > contents.txt

and post 'contents.txt' to http://gist.github.com ?

**Comment by Milkbone** [comment] 2015-05-05 19:40
https://gist.github.com/Milkbone/b78c658266b040358c85 hope it helps abit more.

**Comment by saper** [comment] 2015-05-05 20:30
Thanks, so now if you start `node` and then

> require('node-sass')

you get something, right?

**Comment by saper** [comment] 2015-05-05 20:37
Hold on,

you have 

    \Projects\Auth\node_modules\node-sass

and

    Auth/node_modules/gulp-sass/node_modules/node-sass

which is broken, right? (notice the second one is "under" gulp-sass).

**Comment by saper** [comment] 2015-05-05 20:38
And your vagrant is running which operating system?

**Comment by Milkbone** [comment] 2015-05-05 21:55
Vagrant is running ubuntu 12.02 I believe, okay ill look into messing with the one under gulp-sass and see if I can get it working

**Comment by Milkbone** [comment] 2015-05-05 21:57
funny, I don't seem to have a node-sass in the gulp-sass node_modules file... not sure whats going on there.

**Comment by saper** [comment] 2015-05-05 21:58
You definitely need two different binaries for Windows and for Ubuntu! You can put all binaries needed in the `vendor` directory together.

**Comment by saper** [comment] 2015-05-05 22:02
Seems like your original problem was on Ubuntu and we were troubleshooting Windows.

**Comment by Milkbone** [comment] 2015-05-05 22:25
Actually I had many many problems with node.js and npm on ubunutu that was fixed as soon as I used the windows to install dependencies. I did so on the recommendation of many people having similar issues to mine, the errors I was having was in relation to the symlink with the virtual machine

**Comment by saper** [comment] 2015-05-05 22:38
Ok, but we cannot continue troubleshooting like this.

**Comment by josiahsprague** [comment] 2015-05-08 20:52
Like @chrishomer we ran into this when switching between 0.10.x and 0.12.2 (we have a Vagrant plugin that switches node versions in our Vagrant box automatically depending on our project's `engines` field in package.json). Deleting `rm -rf node_modules && npm install` clears things up. But it would be nice to get some more insight on exactly what's happening, since we switch node versions often and we'd like to avoid running into this problem.

**Comment by xzyfer** [comment] 2015-05-09 03:18
Please update to gulp-sass@2 to solve this issue.

**Comment by saper** [comment] 2015-05-09 06:10
@josiahsprague the solution is relatively east, you need to build or download all the binaries you need and to put then under `vendor` subdirectory. We cannot launch automatic download or build one for you every time the environment https://github.com/sass/sass-spec/issues/361changes.

This concerns all binary modules, not only  `node-sass`

**Comment by josiahsprague** [comment] 2015-05-11 14:55
Thanks @saper. As I understand it now, the binaries that are installed may be different depending on the environment, and if that environment changes after the install, a `rm -rf node_modules` and `npm install` should give us the right ones. Thanks for clarifying! :)

**Comment by saper** [comment] 2015-05-11 22:21
Well, no need to remove all node_modules. You can just do `npm install` in the `node-sass` directory, or try `node scripts/install.js` there. You can have multiple binaries in one directory.

**Comment by xzyfer** [comment] 2015-05-12 12:13
>if that environment changes after the install

This is no long the case in node-sass@3.0.0. Running `npm install` in a new environment should generate the new binaries automatically.

I could be that this behaviour is not respected when node-sass is a dependency of another modules i.e. gulp-sass. This is worth testing.

**Comment by mardiros** [comment] 2015-06-11 09:27
:+1: I don't count the number of time this error appears....

**Comment by mehany** [comment] 2015-06-18 22:26
<blockquote>This concerns all binary modules, not only node-sass</blockquote>

@saper I have a shared folder between two different environments ( Mac, Windows) is that why I get this error? if yes, should I do <em>npm install</em> every time I switch the environment?

I got rid of it by removing node_modules and did <em>nom install </em>

**Comment by saper** [comment] 2015-06-19 06:47
Just `npm install` once from Windows and once from Mac and make sure your `vendor` subdirectory contains both Mac and Windows bindings.

**Comment by xzyfer** [comment] 2015-06-29 02:36
This appears to be resolved. TLDR; if you've recently updated your version of node, or node-sass be sure to remove you node_modules dir because we use native extensions. In the future https://github.com/sass/node-sass/issues/1017 will prevent or warn about these types of issues.

**Closed by xzyfer** 2015-06-29 02:36 UTC
Labels: Bug - Maybe, NPM - Install

**Comment by isochronous** [comment] 2015-07-29 15:33
This is still happening on my machine. Windows Server 2012 R2 Standard, using the following package.json file:

```js
{
  "name": "LaunchTechnologies.Web.LaunchSite",
  "version": "0.1.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-sass": "^2.0.4"
  }
}
```

And this is the error I'm getting:

```
D:\Projects\Launch\ai5\launchsite\source\LaunchTechnologies.Web.LaunchSite\node_modules\gulp-sass\node_modules\node-sass\lib\ext
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in D:\Projects\Launch\ai5\launchsite\source\LaunchTechnologies.Web.LaunchSite\node_modules\g
vendor\win32-ia32-11\binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (D:\Projects\Launch\ai5\launchsite\source\LaunchTechnologies.Web.LaunchSite\node_modules\gulp-s
xtensions.js:148:11)
    at Object.<anonymous> (D:\Projects\Launch\ai5\launchsite\source\LaunchTechnologies.Web.LaunchSite\node_modules\gulp-sass\nod
:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Projects\Launch\ai5\launchsite\source\LaunchTechnologies.Web.LaunchSite\node_modules\gulp-sass\ind
    at Module._compile (module.js:456:26)
```

Things I've tried with no success:

1. Completely deleting the node_modules directory and doing a fresh `npm install`
2. Doing a `npm uninstall` of gulp and gulp-sass, then a fresh `npm install`
3. Doing a global install of node-sass, and doing a global uninstall of node-sass.
4. Doing a `npm rebuild node-sass` from within the node_modules/gulp-sass directory
5. Doing a `npm install` with node-sass@2, then node-sass@3 when that didn't work
6. Banging my head repeatedly against my desk

I should mention that when I do the fresh `npm install` everything seems to install just fine with no errors.  Whenever I do a `npm rebuild node-sass` it just tells me my existing binaries are fine.

**Comment by pflannery** [comment] 2015-08-01 19:20
Windows 10 64bit
Node 0.12.7
Npm 2.11.3

I got this message today from inside the task runner built in with Visual Studio 2015. 
But when I ran `node-sass` from a console it worked.

I had nodejs 0.12.7 64bit installed but turns out Visual Studio 2015 only runs as a 32bit process. So when I tried to run `node-sass` via VS 2015 it was trying to find the `vendor\win32-ia32-11.bindings` file which didn't exist. Instead I had the 64bit bindings file compiled via node-gyp.

I fixed my problem by uninstalling node js 64bit and installing nodejs 32bit version so now it works from within Visual Studio 2015 and the console :)

I'm not quite sure how this scenario happens but it seems that node-gyp was compiling the 64bit bindings but node when run under a 32bit process was trying to resolve the 32bit binding which didn't exist.

**Comment by saper** [comment] 2015-08-01 19:26
> I'm not quite sure how this scenario happens but it seems that node-gyp was compiling the 64bit bindings but node when run under a 32bit process was trying to resolve the 32bit binding which didn't exist.

you need bindings compiled to much your OS, architecture and the version if node.
if you need to use node-sass across multiple engines, you need to download bindings
for everybengine you are using. you can keep multiple versions in the vendor directory,
and node-sass will pick up the right one.

**Comment by isochronous** [comment] 2015-08-02 01:30
Hmmm, good to know. I'm was running the commands from a PowerShell console
within ConEmu, so I'll verify that it was running in x64 mode and then
report back.

**Comment by saper** [comment] 2015-08-02 02:39
I would recommend not to use PowerShell because it recognizes any kind of output to the standard error channel as a fatal error of the executed subprocess (example issue causing the failure is: https://github.com/npm/npm/pull/8841). Just try `npm install node-sass` with `cmd.exe`

**Comment by isochronous** [comment] 2015-08-02 06:10
I'll try that, though this would be the first time in 3 years of using node
that powershell has gotten in the way.

**Comment by saper** [comment] 2015-08-02 09:47
> I'll try that, though this would be the first time in 3 years of using node
> that powershell has gotten in the way.

Well, we've run into it and it is a confirmed problem with npm.
One can use node for many years without touching any binary modules at all
and certainly PowerShell works in 99% of situations.

The issues we face here are not specific to node-sass - similar
problems are to be expected whenever native code is used.

**Comment by isochronous** [comment] 2015-08-04 19:35
Just an update - I tried using both 64 and 32 bit cmd.exe instead of powershell with the same result. I did just realize that I'm using an old version of node (v0.10.28) so I'm going to update that and see if that makes any difference.

**Comment by isochronous** [comment] 2015-08-04 19:45
Updated to v0.12.7, still have the same issue after deleting `node_modules` and re-running `npm install` :(

**Comment by saper** [comment] 2015-08-04 19:59
I have not enough details to help. Can you dump a full log according to our [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide?

One thing that I noticed is that the system was trying to load 32-bit binding. That should work but I hope that is what is expected.

**Comment by isochronous** [comment] 2015-08-04 21:13
Sure thing - I didn't update the error I was getting, but I opened both a 64-bit and 32-bit cmd side-by-side and tried everything in both of them just to make sure I was covering my bases.  The binding it was attempting to use may have changed (that should show up in the logs I suppose) but the general error was the same.

**Comment by isochronous** [comment] 2015-08-04 21:29
```
D:\LaunchSite>npm -v
2.11.3

D:\LaunchSite>node -v
v0.12.7

D:\LaunchSite>node -p process.versions
{ http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }

D:\LaunchSite>node -p process.platform
win32

D:\LaunchSite>node -p process.arch
x64
```

At this point I went into node_modules/gulp-sass and ran `npm install node-sass`.
There were no errors on install.

```
D:\LaunchSite\node_modules\gulp-sass\node_modules\node-sass>type package.json
{
  "name": "node-sass",
  "version": "3.2.0",
  "libsass": "3.2.5",
  /* snip */
}

D:\LaunchSite\node_modules\gulp-sass\node_modules\.bin>node-sass --version
node-sass       3.2.0   (Wrapper)       [JavaScript]
libsass         3.2.5   (Sass Compiler) [C/C++]

D:\LaunchSite\node_modules\gulp-sass\node_modules\.bin>node -p "console.log(require('node-sass').info)"
node-sass       3.2.0   (Wrapper)       [JavaScript]
libsass         3.2.5   (Sass Compiler) [C/C++]
undefined  // <-- what's this?
```

And here's the error when running from an 64-bit cmd.exe - though I notice it's
using the ia32 binding rather than the x64 binding, which seems like it could
be a (the?) problem:

```
D:\LaunchSite>gulp sass

Error: `libsass` bindings not found in D:\LaunchSite\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (D:\LaunchSite\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:148:11)
    at Object.<anonymous> (D:\LaunchSite\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\LaunchSite\node_modules\gulp-sass\index.js:163:21)
    at Module._compile (module.js:456:26)
```

**Comment by isochronous** [comment] 2015-08-04 21:31
I should also mention that the troubleshooting guide says to go to https://github.com/sass/node-sass-binaries/tree/v , but that's a 404.

**Comment by saper** [comment] 2015-08-04 21:36
So gulp is making us believe we run on 32-bit node, while running on 64-bit?

**Comment by hexogen** [comment] 2015-08-05 00:49
had the same problem but on Ubuntu 14.04(vagrant laravel homestead) host was an Ubuntu 14.04 too.
Solved after apt-get update, apt-get upgrade, npm install with sudo permission.

**Comment by iGeordie** [comment] 2015-08-05 10:17
I'm also seeing the exact same error messages when using grunt and grunt-sass on windows.  

```
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found in D:\repos\test\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-ia32-14\binding.node. Try reinstalling `node
-sass`?
Warning: Task "sass" failed. Use --force to continue.
```

**Comment by isochronous** [comment] 2015-08-05 17:36
I don't know if it's gulp doing it or what. However! I can verify that downloading the "missing" ia32 binding file into the appropriate directory fixes the problem.  I don't know exactly what is causing node-sass to try using the ia32 bindings, but since 64-bit is perfectly capable of running 32-bit apps, including both x64 and ia32 bindings seems to suffice for a workaround until the actual cause can be identified.

**Comment by saper** [comment] 2015-08-05 17:48
Are you using VisualStudio to run some tasks? I think it comes with 32-bit node.

**Comment by isochronous** [comment] 2015-08-05 18:45
No, I'm running everything in a cmd.exe shell within ConEmu.

**Comment by ckihneman** [comment] 2015-09-10 23:36
I just went through the process of updating node on my system via homebrew. This lead to this error message popping on me, and not letting me move forward. It seemed to come down to old versions of files floating around, and deleting my `node_modules` folder then running a fresh `npm install` after ensuring all packages were referencing their latest versions. Ran right through after that. Here are my steps.

Update node via homebrew:

```
brew update
brew doctor
brew upgrade node
```

I recommend using `npm-check-updates` to update your node modules to latest. Install it and run that command to do a dry run, then pass `-u` to actually update your `package.json` file.

Update your global modules: `npm update -g`

Delete your current `node_modules` folder.

Run `npm install` to get a fresh version of everything.

**Comment by isochronous** [comment] 2015-09-14 15:35
I assume from the fact that you're using homebrew that you're on OSX.  The
problem I'm having is on a x64 Windows Server 2012 R2 box, and it's been
confirmed by at least one other windows x64 user.  I've already done
everything you mentioned except for the npm-check-updates step, because, in
this particular case, node-sass is just a dependency on another third party
package (gulp-sass). Regardless, at the time I reported this bug gulp-sass
was already using the most recent version of node-sass, so that wouldn't
have helped.

**Comment by mellatone** [comment] 2015-09-17 22:41
I appreciate the continued attention this thread is receiving. I'm running into similar issues with NVM using node v4.0.0 and npm 2.14.2 on OSX 10.9.5

```
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/[redacted]/ember_dev/projects/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/Users/[redacted]/.nvm/versions/node/v4.0.0/bin/node" "/Users/[redacted]/ember_dev/projects/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/[redacted]/ember_dev/projects/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
```

**Comment by xzyfer** [comment] 2015-09-17 22:48
It looks like you're using a version of node-sass that doesn't support Node
4. Either down grade to an older version of nose or updated to a node-sass
>= 3.3.2.

**Comment by saper** [comment] 2015-09-17 22:50
Somewhere in your system 64-bit and 32-bit environments got mixed. It is enough that even if you are certain you start in 64-bit environment - something, somewhere (some stupid batch file for example) executes 32-bit node for you. We really depend on the `process.arch` variable from the node engine we run on to pick up a right binary.

Try logging `node -p process.arch` at various stages of your pipeline and see where it changes.

**Comment by saper** [comment] 2015-09-19 14:46
To everyone who has read up to this point:

## This message means that you are using an outdated version of node-sass. You should try to use the newest version: just try the following command and try again:

     npm install node-sass

This is the end. Thank you for your attention!
