### ISSUE TITLE
3.9.3 install throwing with gauge/render-template error

### ISSUE THREAD

**Issue by grantmcconnaughey** [sass/node-sass#1707] opened 2016-09-06 16:14 UTC
We are installing gulp-sass, which installs node-sass. I noticed that version 3.9.0 was messed up, but it looks like 3.9.3 should have fixed these installation issues. However, we're still having issues installing 3.9.3. 

Here's our issue:

```
RAN: '/usr/local/bin/npm install'
  STDOUT:
> node-sass@3.9.3 install /srv/www/project/node_modules/node-sass
> node scripts/install.js
Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/linux-x64-11_binding.node
  STDERR:
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
 [?25l
 [K [?25h
/srv/www/project/node_modules/gauge/render-template.js:67
          throw new error.MissingTemplateValue(cloned, values)
                ^
Error: Missing template value "progressbar"
    at cloneAndObjectify (/srv/www/project/node_modules/gauge/render-template.js:67:17)
    at Array.map (native)
    at prepareItems (/srv/www/project/node_modules/gauge/render-template.js:83:25)
    at module.exports (/srv/www/project/node_modules/gauge/render-template.js:16:15)
    at Object.Plumbing.show (/srv/www/project/node_modules/gauge/plumbing.js:45:10)
    at Object.Gauge._doRedraw (/srv/www/project/node_modules/gauge/index.js:219:40)
    at Timer.<anonymous> (/srv/www/project/node_modules/gauge/index.js:15:19)
    at Timer.wrapper (timers.js:252:14)
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.9.3 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@3.9.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/project/npm-debug.log
```

**Comment by xzyfer** [comment] 2016-09-07 11:23
I am unable to reproduce this locally. Can you try following the [installation debugging guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx) and see if it still happens?

**Comment by xzyfer** [comment] 2016-09-08 10:27
Closing awaiting a response.

**Comment by ryanhanks-wf** [comment] 2016-09-09 17:11
@xzyfer we're seeing this issue reproduce on our CI builders as well. In your attempt to reproduce, what OS were you on? I'm not able to repro on OS X, but we do seem to still be having the same problem on linux.

```
> node-sass@3.9.3 install /smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/linux-x64-11_binding.node
[?25l
[?25h
/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/render-template.js:67
          throw new error.MissingTemplateValue(cloned, values)
                ^
Error: Missing template value "progressbar"
    at cloneAndObjectify (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/render-template.js:67:17)
    at Array.map (native)
    at prepareItems (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/render-template.js:83:25)
    at module.exports (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/render-template.js:16:15)
    at Object.Plumbing.show (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/plumbing.js:45:10)
    at Object.Gauge._doRedraw (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/index.js:219:40)
    at null.<anonymous> (/smithy-builder/builds/Workiva/books/workspace/node_modules/w-annotation-ui/node_modules/web-skin/node_modules/node-sass/node_modules/npmlog/node_modules/gauge/index.js:15:19)
    at wrapper (timers.js:270:14)
    at Timer.unrefdHandle (timers.js:304:14)
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.9.3 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@3.9.3 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /smithy-builder/builds/Workiva/books/workspace/npm-debug.log
```

**Comment by saper** [comment] 2016-09-09 17:46
Can you dump your npm tree and see which versions of npm log and gauge come into play?

**Comment by xzyfer** [comment] 2016-09-09 23:23
I was trying to reproduce with node 10 on OSX, with npm v2.15.0. OS doesn't matter because this appears to be an issue with guage.

**Comment by saper** [comment] 2016-09-10 09:10
Is this because of #1694 ? Those little nice features

**Comment by xzyfer** [comment] 2016-09-10 14:48
It's related to that library but the issue is environment specific. I can't
reproduce on that version of node, and it's a library used by npm itself.

**Comment by saper** [comment] 2016-09-10 18:52
@xzyfer gauge module is a pretty kid on the block, and it might not [have been extensively tested](https://github.com/npm/npm/issues/13274#issuecomment-230630921) on old node engines.

**Comment by saper** [comment] 2016-09-10 19:43
This might be similar to https://github.com/iarna/gauge/issues/59 I think one needs a "slow" output device that causes `stream.write` to return `false` and this way we get into the `drain` event handler.

**Comment by chrislong** [comment] 2016-09-27 19:56
In case it helps: I get the same originally reported error (with node-sass 3.10.0) when I run it in an emacs compilation buffer, but when I run it in a terminal (Konsole), it works just fine.

**Comment by saper** [comment] 2016-09-27 22:30
@Chrislong thanks a lot! that would confirm my theory about the impact of the progressbar on some pseudo terminals.

**Comment by xzyfer** [comment] 2016-09-30 07:44
We knew these types of issues could be a possibility. For this reason we moved from the `progress` module to the `gauge` module which is used by npm@3. If you're unable to use npm in an environment then the issue is moot. For this reason we also respect the npm `progress` config flag.

**Comment by saper** [comment] 2016-10-04 17:06
@Xzyfer I don't think that npm bugs should be our bugs :) I am not convinced that gauge underwent hard testing everywhere. But it is unacceptable that the gadget prevents installation of node-sass.

**Comment by xzyfer** [comment] 2016-10-05 12:03
I'm convinced the progress bar provides value to users.

We could disable the progress bar in npm@2. As of December npm@3 is the default for all actively supported node releases.

If npm is broken on a system then node installation is already prevented :) 
Running `install.js`out of the npm is not something we support.

**Comment by saper** [comment] 2016-10-05 14:32
@xzyfer You know we disagree on that one, but it is okay. Obviously in this case the OP is getting npm working with all bangs and whistles, so what should be investigated is the question "why npm works with its progress bar but not with node-sass's install.js"?

**Comment by xzyfer** [comment] 2016-10-05 15:09
OP is using npm 2 which is before gauge was implemented in npm. This is why I suggested we could disable the progress bar in npm < 3 as npm 4 is on the horizon.

**Comment by giosh94mhz** [comment] 2016-10-18 16:33
I'm experiencing the same issue, with node `v4.4.6`. Here a simple snippet to reproduce on the console:

    ( npm install ) 2> /tmp/logfile || echo "dead"

I'm not a skilled node developer, so can you suggest a workaround for this?

**Comment by giosh94mhz** [comment] 2016-10-18 16:40
[Gavin Joyce](https://twitter.com/gavinjoyce/status/691783314261331969) is my personal hero today. Here's the workaround:

    npm set progress=false

**Comment by ian** [comment] 2016-11-15 02:31
Just ran into this issue out of nowhere today.  Did two separate heroku deploys and then started failing out of nowhere. 

If you're on Heroku and run into this, the `NPM_CONFIG_PROGRESS` fix worked for me: https://github.com/heroku/heroku-buildpack-nodejs/issues/312

**Comment by chriswait** [comment] 2016-11-15 03:46
Also experiencing this issue for the first time as of today, with 3.12.4:
`Failed at the node-sass@3.12.4 install script 'node scripts/install.js'.`

```
> node-sass@3.12.4 install C:\a\1\s\Source\...\node_modules\node-sass
> node scripts/install.js
http node-sass install Downloading binary from https://github.com/sass/node-sass/releases/download/v3.12.4/win32-x64-47_binding.node
##[error]C:\a\1\s\Source\...\node_modules\gauge\render-template.js:67
          throw new error.MissingTemplateValue(cloned, values)
```

**Comment by bryannaegele** [comment] 2016-11-15 03:46
Running into this tonight. Node Boron (6.9.1) in docker.

Setting progress to false is not resolving the issue. This is currently breaking my builds and dev env.

My $0.02 - progress bars for libs installing doesn't provide any value to me. If I need to see progress I'll leave the logs spitting out normally and set it to quiet when I don't.

Progress bars have their place. I understand their value. Installation of a node lib is not one of them.

```
webpack_1  | npm info using npm@3.10.8
webpack_1  | npm info using node@v6.9.1
webpack_1  | npm info config set "progress" "false"
webpack_1  | npm info ok
webpack_1  | npm info it worked if it ends with ok
webpack_1  | npm info using npm@3.10.8
webpack_1  | npm info using node@v6.9.1
webpack_1  | > node-sass@3.12.4 install /src/node_modules/node-sass
webpack_1  | > node scripts/install.js
webpack_1  |
webpack_1  | http node-sass install Downloading binary from https://github.com/sass/node-sass/releases/download/v3.12.4/linux-x64-48_binding.node
webpack_1  | /src/node_modules/gauge/render-template.js:67
webpack_1  |           throw new error.MissingTemplateValue(cloned, values)
webpack_1  |           ^
webpack_1  |
webpack_1  | Error: Missing template value "progressbar"
webpack_1  |     at cloneAndObjectify (/src/node_modules/gauge/render-template.js:67:17)
webpack_1  |     at Array.map (native)
webpack_1  |     at prepareItems (/src/node_modules/gauge/render-template.js:83:25)
webpack_1  |     at module.exports (/src/node_modules/gauge/render-template.js:16:15)
webpack_1  |     at Object.Plumbing.show (/src/node_modules/gauge/plumbing.js:45:10)
webpack_1  |     at Object.Gauge._doRedraw (/src/node_modules/gauge/index.js:219:40)
webpack_1  |     at Timeout.<anonymous> (/src/node_modules/gauge/index.js:15:19)
webpack_1  |     at ontimeout (timers.js:365:14)
webpack_1  |     at Timer.unrefdHandle (timers.js:466:3)
```

**Comment by xzyfer** [comment] 2016-11-15 03:48
@chriswait @bryannaegele I believe your issues are a duplicate of #1805. Please try 3.12.5.

**Comment by ian** [comment] 2016-11-15 03:49
Just started for me about 4 hours ago.  Not sure if something got published on npm?

**Comment by xzyfer** [comment] 2016-11-15 03:50
@ian see #1805. Please try 3.12.5.

**Comment by xzyfer** [comment] 2016-11-15 03:51
Closing in favour of #1805. Please focus discussion there.

**Closed by xzyfer** 2016-11-15 03:51 UTC
Labels: Awaiting Response, Node 0.10
