### ISSUE TITLE
Missing bindings on Windows 10 with 3.2.0

### ISSUE THREAD

**Issue by ALF-er** [sass/node-sass#1067] opened 2015-08-12 08:02 UTC
Hello, receive this error on installation

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/win32-x64-45_binding.node": HTTP error 404 Not Found
```

Setup:
iojs 3.0.0
node-sass 3.2.0
windows 10

**Comment by saper** [comment] 2015-08-12 10:30
Duplicate of #1053

**Closed** 2015-08-12 10:30 UTC
