### ISSUE TITLE
Err ELIFECYCLE 3221225477 please for your help

### ISSUE THREAD

**Issue by exlibrusss** [sass/node-sass#2723] opened 2019-08-29 12:09 UTC
![IMG_20190828_221859](https://user-images.githubusercontent.com/54670375/63938843-7a628100-ca6e-11e9-8f7d-95fdb53ad760.jpg)
Please for your help , I've got such an error.

My Package.json: 
{
  "name": "natours",
  "version": "1.0.0",
  "description": "Landing page for natours",
  "main": "index.js",
  "scripts": {
    "compile:sass" : "node-sass sass/main.scss css/style.css -w"
  },
  "author": "Sviatoslav",
  "license": "ISC",
  "devDependencies": {
    "node-sass": "^4.12.0"
  },
  "dependencies": {}
}

**Comment by nschonni** [comment] 2019-08-29 13:11
Duplicate of a bunch of issues with more details https://github.com/sass/node-sass/search?q=3221225477&type=Issues

**Closed by nschonni** 2019-08-29 13:11 UTC
