### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by strawlion** [sass/node-sass#1339] opened 2016-01-13 02:10 UTC
Hey all, I'm encountering a race condition when compiling my sass.

As you can see, the first run works correctly, but the second fails to find a mixin (which should be available)
![32c39200-b3e1-11e5-8f46-20b8aa6df1c7](https://cloud.githubusercontent.com/assets/3640788/12283013/ddb6c30a-b957-11e5-8f6a-dba8af4f3164.png)

The gulp code itself is straightforward
![6e6b33da-b3e1-11e5-9d4c-18e2348378a4]
(https://cloud.githubusercontent.com/assets/3640788/12134158/6e6b33da-b3e1-11e5-9d4c-18e2348378a4.png)

Node: v5.2.0
Gulp: v4.0.0-alpha2
gulp-sass: v2.1.1
node-sass: v3.4.2

It's failing about 50% of the time. Any ideas?

**Comment by saper** [comment] 2016-01-13 16:35
Can you check if node-sass (possibly multiple versions) got installed under node_modules? This happens usually when two different versions are available in the tree.

The solution there would be to make sure all dependencies are up to date and some older node-sass version does not get loaded by accident.

**Comment by strawlion** [comment] 2016-01-13 23:55
Unfortunately that doesn't appear to be the case. Do you think this issue is at the node-sass level?

Global Modules
![image](https://cloud.githubusercontent.com/assets/3640788/12311685/c2f47736-ba0d-11e5-9816-bda35b2c3fae.png)

Project Modules
![image](https://cloud.githubusercontent.com/assets/3640788/12311694/d1328aea-ba0d-11e5-80cd-8ba4f00ed06d.png)

**Comment by strawlion** [comment] 2016-01-14 23:39
Does my configuration look correct to you? 

Source files include both `*.scss` and `_*.scss` files. 
includePaths is a path to the base of the sass folder (something like `src/sass/`)

**Comment by saper** [comment] 2016-01-20 19:29
I don't know. I think there is something wrong with the include order. Try to take gulp-sass out of the equation and try to reproduce the issue.

**Comment by xzyfer** [comment] 2016-03-23 13:37
@strawlion please create a small github repo that has this issue so we can debug it on our own machines. We are unable to reproduce this problem.

**Comment by xzyfer** [comment] 2016-03-26 07:23
We are unable to reproduce this problem. Closing until someone provides the requested minimal reproduction as a GitHub repository we can debug it locally.

**Closed by xzyfer** 2016-03-26 07:23 UTC
Labels: Awaiting Response, Bug - Maybe
