### ISSUE TITLE
ARM binary is missing

### ISSUE THREAD

**Issue by StigoSvK** [sass/node-sass#3266] opened 2022-05-03 10:48 UTC
Hi. I'm unable to install node-sass on mac because `darwin-arm64-93_binding.node` is missing in GH. There is only `darwin-x64-93_binding.node`

Node version: 16.13.2
node-sass version: 7.0.1
MacBook Pro 14", M1 Pro chip, Monterey 12.3.1 

Output from `yarn --verbose`
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v7.0.1/darwin-arm64-93_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v7.0.1/darwin-arm64-93_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via
```

My colleague with same setup has the same issue.
Thanks

**Comment by nschonni** [comment] 2022-05-03 21:02
Duplicate of https://github.com/sass/node-sass/issues/3033

**Closed by nschonni** 2022-05-03 21:02 UTC
