### ISSUE TITLE
The /*comment*/ syntax causes all SCSS afterwards to not be included

### ISSUE THREAD

**Issue by chrismbarr** [sass/node-sass#1118] opened 2015-08-31 15:10 UTC
I found this issue while using the Web Compiler extention for Visual Studio.  I [originally opened a bug with them](https://github.com/madskristensen/WebCompiler/issues/92), but I was directed here. 

----

I've noticed that as soon as any SCSS with a multi-line comment is encountered, any following code does not seem to be included.

:arrow_forward: **SCSS input:**
```SCSS
#test1{
	color: red;
}

/*#test2{
	color: blue;
}*/

#test3{
	color: green;
}
```

:x: **Incorrect CSS Output:** (missing the `#test3` selector that should appear after the comment)
```CSS
#test1 {
  color: red; }

/*#test2{
	color: blue;
}*/
```

However, switching to the single-line comments will fix this, so this is my temporary workaround
:arrow_forward: **SCSS input:**
```SCSS
#test1{
	color: red;
}

//#test2{
//	color: blue;
//}

#test3{
	color: green;
}
```
:white_check_mark: **Correct CSS Output:** (Comments not included, and only uncommented code is output)
```CSS
#test1{
	color: red; }

#test3{
	color: green; }
```

**Comment by mgreter** [comment] 2015-08-31 15:26
Cannot reproduce either on sassmeister (libsass 3.2.5) or on latest master!?

**Comment by xzyfer** [comment] 2015-09-01 02:41
@chrismbarr can you please confirm which version of node-sass you are using. This issue should be resolved in newer versions.

**Comment by chrismbarr** [comment] 2015-09-01 09:18
It turns out to be an issue with the visual studio extension that I mentioned above. That issue was further investigated and it was re-opened. Sorry about that!

**Closed** 2015-09-01 10:22 UTC
Labels: Awaiting Response
