### ISSUE TITLE
Install: Problem with the binary, then won't do manual build; can't install

### ISSUE THREAD

**Issue by niceredfrog** [sass/node-sass#1665] opened 2016-08-12 22:07 UTC
On OSX. Am actually trying to install harp with "npm install -g harp" and the installation fails at the node-sass step. Have tried with node versions 4.4.7, 5.11.1, and 6.3.1. Followed the steps in the Troubleshooting page at https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md to install node-sass in a clean new work space. Output from those steps is at https://gist.github.com/niceredfrog/e3a05010abd41be53c0c2f1cb6da66e1. Output from one of my earlier efforts is at https://gist.github.com/niceredfrog/6537290d6587461e1cb5da9134a3dafb.

**Comment by am80l** [comment] 2016-08-16 20:46
+ 1

**Comment by am80l** [comment] 2016-08-16 20:46
+1

**Comment by am80l** [comment] 2016-08-16 21:42
+1

4 out of 4 people on my team can not install with a simple `npm install node-sass``

Reverting the project to earlier versions does not resolve the issue.

**Comment by xzyfer** [comment] 2016-08-17 00:32
Relevant log lines

```
> mkdir ~/temp1
> cd ~/temp1
> ls
> npm -v
3.8.6
> node -v
v5.11.1
>  node -p process.versions
{ http_parser: '2.7.0',
  node: '5.11.1',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2h' }
>  node -p process.platform
darwin
>  node -p process.arch
x64
> sudo npm install node-sass
Password:

> node-sass@3.8.0 install /Users/j/temp1/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/j/temp1/node_modules/node-sass/vendor/darwin-x64-47/binding.node

> node-sass@3.8.0 postinstall /Users/j/temp1/node_modules/node-sass
> node scripts/build.js

"/Users/j/temp1/node_modules/node-sass/vendor/darwin-x64-47/binding.node" exists. 
 testing binary.
Problem with the binary:
Error: dlopen(/Users/j/temp1/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): Symbol not found: __ZNKSt3__119__shared_weak_count13__get_deleterERKSt9type_info
  Referenced from: /Users/j/temp1/node_modules/node-sass/vendor/darwin-x64-47/binding.node
  Expected in: flat namespace
 in /Users/j/temp1/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Manual build incoming.
```

**Comment by saper** [comment] 2016-08-17 13:43
what is the OS X version affected? which X code was installed?
@xzyfer which OS and X code are we using to build the binary? I suspect C++ runtime library mismatch somewhere.

**Comment by saper** [comment] 2016-08-20 23:26
So this was Darwin 10.8.0 (Mac OS X v10.6.8) and the `g++` compiler does not understand C++11.

@niceredfrog I think your compiler is a bit too old, can you check which version of `g++` do you have? (`g++ --version` might give the right output).

You might need to upgrade your Xcode or use a more recent GCC (like 4.9 for example) to compile node-sass. You can set `CC` and `CXX` environment variables to point npm to the right compiler.

**Comment by saper** [comment] 2016-08-21 00:18
Well this seems to be a  duplicate of https://github.com/sass/node-sass/issues/1160 - Mac OS X v10.6.8 (Snow Leopard) has too old C++ library and is not supported.

**Closed by saper** 2016-08-21 00:18 UTC
Labels: Invalid - Duplicate, NPM - Install, OS - OSX
