### ISSUE TITLE
Sourcemap sources have wrong paths

### ISSUE THREAD

**Issue by itsnydell** [sass/node-sass#731] opened 2015-03-02 20:30 UTC
I'm using the latest version of grunt-sass which uses node-sass 2.0.1 in a project at my company. We are running into an issue where our css sourcemaps have wrong url paths. 

In chrome dev tools, the correct scss file is mentioned:
![01](https://cloud.githubusercontent.com/assets/1850809/6448851/c05f66ec-c0ea-11e4-9439-8358a239bda1.jpg)

However, when you go to click the scss file to view the specific line of scss, it links to the wrong file:
![02](https://cloud.githubusercontent.com/assets/1850809/6448853/c26c607a-c0ea-11e4-913d-d4adf48194a0.jpg)

Incorrect path: ```http://sample.dev/common/_common.scss```
**Correct path: ```http://sample.dev/css/desktop/common/_common.scss```**

On the homepage of our site, the ```home.css``` file is called with the url: ```http://sample.dev/css/desktop/home.css```

#### The css folder structure is as follows:
```
├─┬ public
│ ├─┬ css
│ │ ├─┬ desktop
│ │ │ ├─┬ common
│ │ │ │ ├── _common.scss
│ │ │ ├── home.css
│ │ │ ├── home.css.map
│ │ │ ├── home.scss
├── Gruntfile.js
```

#### Inside the home.css.map file:
```
{
	"version": 3,
	"file": "home.css",
	"sources": [
		"../../../home.scss",
		"../../../common/_common.scss",
	],
	"sourcesContent": [],
	"mappings": ".........",
	"names": []
}
```

#### The grunt-sass setup in Gruntfile.js:
```
sass: {
    options: {
        sourceMap: true
    },
    desktop: {
        files: [{
            expand: true,
            cwd: 'public/css/desktop',
            src: ['*.scss'],
            dest: 'public/css/desktop',
            ext: '.css'
        }]
    },
    mobile: {
        files: [{
            expand: true,
            cwd: 'public/css/mobile',
            src: ['*.scss'],
            dest: 'public/css/mobile',
            ext: '.css'
        }]
    }
},
```

**Comment by am11** [comment] 2015-03-02 20:35
Thanks for reporting this issue.

It may come as a surprise, but it is by design. It is generally caused by the confusion at setting paths. We should update that part of the documentation. 

In short, please try one of four solutions described here: https://github.com/sass/libsass/issues/908#issuecomment-76452477.

**Comment by itsnydell** [comment] 2015-03-02 20:59
@am11 Thanks for the quick reply. By nature of our large website, we have many scss files that need to be compiled between multiple devices. We have separated them into different css files for each type of page on our site so that we can minimize unneeded css on every page. So defining a new file in the Gruntfile for every css file we need a map for just isn't practical, at least this is what it looks like based on the solution. 

Is there anyway to add a prefix to the paths or sourceRoot?

**Comment by am11** [comment] 2015-03-02 21:22
@itsnydell, currently `sourceRoot` is not supported by libsass unfortunately yet. 

@mgreter, should we consider adding it in libsass, in effort to address sass/libsass#908?

Back to @itsnydell, if you could share a gist, isolating Grunt code to assemble pure node-sass API code, I might be able to help you with pre-processing paths. In general, it is a matter of understanding how node-sass is resolving the `outFile` and `sourceMap` paths with respect to the input `file` (as opposed to `cwd`). The input `file` itself, however, is resolved with respect to `cwd` by libsass. Therefore, node-sass allows you to set absolute or relative paths for each `file`, `outFile` and `sourceMap` with addition to a special syntactic sugar: `sourceMap: true` which essentially resolves to `outFile = resolveWithRespectToInputPath(outFile); sourceMap = outFile + '.map';`.

 In my experience of dealing with paths, there is always a (cross-platform) way out for this kind of situation. I am not denying that it will be the nifty workaround, especially when the core component (like `sourceRoot`) is missing.

**Comment by itsnydell** [comment] 2015-03-02 22:27
@am11 I hope this is what you meant:

https://gist.github.com/itsnydell/6c51c9e9c944678a958c 
This is an example of one of the scss files that the grunt-sass wrapper makes

**Comment by mgreter** [comment] 2015-03-02 22:39
Wouldn't `sourceRoot` be the same as changing the working directory there for compiling? IMO if you don't move the files (as IMO it is the case in https://github.com/sass/libsass/issues/908) it libsass should be able to produce usable paths, if the working directory is at an apropriate place. But I honestly haven't looked into that code for a long time, I'm just pretty sure I tested all variation so the ouput makes sense!

**Comment by am11** [comment] 2015-03-02 22:56
@mgreter, `sourceRoot` is path of the source-map [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1#heading=h.75yo6yoyk7x5), which states:

> **Resolving Sources**
If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).

We can expose it to API and pass it to libsass. Later, libsass can just stamp it out in map JSON as is. This gives the final implementer to control over the path prefixes, and hence dictate the browser to where to look.

**Comment by mgreter** [comment] 2015-03-02 23:00
OK, I see it is actually an option in sourceMaps itself, but only some string that gets prepended to each url for the actual source (if they are not already absolute). I will have to think about it, but a pass-through is probably a no-brainer!

**Comment by itsnydell** [comment] 2015-03-02 23:03
@am11 @mgreter Thanks guys for looking into this. A pass-through, at least, would be very useful.

**Comment by xzyfer** [comment] 2015-03-03 00:42
IMHO for us it comes down to "what does Ruby Sass do". For the time being our aim is to be a drop in replacement for Ruby Sass. If this behaviour differs it should be addressed. If it can be improved even better, but there should be Ruby Sass BC compatible equivalent.

**Comment by am11** [comment] 2015-03-03 01:32
I don't think `sourceRoot` is supported in ruby sass either, and there is no open issue for that. 

Depending on how much we can rely on GH search:

https://github.com/sass/sass/search?utf8=%E2%9C%93&q=sourceRoot&type=Code
vs.
https://github.com/sass/sass/search?utf8=%E2%9C%93&q=sourcesContent&type=Code

Apparently, node community is more "dialed in" when it comes to this kind of ultra geeky stuff. :wink:

**Comment by itsnydell** [comment] 2015-03-03 15:36
With the built-in command ```sass --update ./public/css/desktop```, in sass, it creates the map files with the correct sources urls. Here is the same map file generated by the above command. 

```
{
	"version": 3,
	"mappings": "........",
	"sources": [
		"common/_common.scss"
	],
	"names": [],
	"file": "home.css"
}
```

You'll notice that the sources url is correct here for the ```common/_common.scss``` file, but it's also missing the file that generated it ```home.scss```.  Everything works great in chrome and correctly shows you the right SCSS files and lines. The only issue is that the built-in command takes minutes to update the site, versus node-sass, which takes about 2.3 seconds to recompile everything.

**Comment by am11** [comment] 2015-03-03 16:40
@itsnydell, consider this hierarchy:

```
{web-root}
     |
     assets
         |
         styles
              \
                home.scss
               \
                common
                      \
                     _commons.scss
```

home.scss:

```scss
@import 'common/_commons';

a{b:c}
```

common/_commons.scss:

```scss
x{y:z}
```

Enter node interactive console (REPL):

```javascript
> process.cwd()
'C:\\temp\\assets\\styles'
> var sass = require('node-sass');
undefined
> console.log(sass.info())
node-sass version: 2.0.1
libsass version: 3.1.0
undefined
> sass.render({
...   file: 'home.scss',
...   outFile: 'compiled.css',
...   sourceMap: true,  // can be set as string
...   success: function (result) { console.log(result.map); },
...   error: function (error) { console.log(error); }
... });
> {
        "version": 3,
        "file": "compiled.css", // makes sense!
        "sources": [
                "home.scss", // makes sense!
                "common/_commons.scss" // makes sense!
        ],
        "sourcesContent": [],
        "mappings": "ACAA,AAAE,AAAE,ADEJ,AAAE,AAAE",
        "names": []
}

// now if cwd was the web root or something else:

> process.chdir('../..')
undefined
> process.cwd()
'C:\\temp'
> sass.render({
... file: 'assets/styles/home.scss',
... outFile: 'compiled.css',  // <-- this is the key, outFile is relative to file, not cwd
... sourceMap: true,  // same story, we can set it as ..  sourceMap: 'compiled.css.map'
... success: function (result) { console.log(result.map); },
... error: function (error) { console.log(error); }
... });
undefined
> {
        "version": 3,
        "file": "compiled.css",  // makes sense!
        "sources": [
                "home.scss",  // makes sense!
                "common/_commons.scss" // makes sense!
        ],
        "sourcesContent": [],
        "mappings": "ACAA,AAAE,AAAE,ADEJ,AAAE,AAAE",
        "names": []
}

// one more 

> sass.render({
... file: 'assets/styles/home.scss',
... outFile: 'compiled.css', 
... sourceMap: 'maps/my-favorite-name.map',  // <-- notice this
... success: function (result) { console.log(result.map); },
... error: function (error) { console.log(error); }
... });
undefined
> {
        "version": 3,
        "file": "../compiled.css", // makes sense!
        "sources": [
                "../home.scss", // makes sense!
                "../common/_commons.scss" // makes sense!
        ],
        "sourcesContent": [],
        "mappings": "ACAA,AAAE,AAAE,ADEJ,AAAE,AAAE",
        "names": []
}
```

**Comment by am11** [comment] 2015-03-03 17:02
@xzyfer, I have opened an issue in ruby sass tracker: https://github.com/sass/sass/issues/1660. :)

**Comment by itsnydell** [comment] 2015-03-03 17:25
@am11 Hello, unfortunately, we cannot use the above situations. We are using grunt-sass which just is a wrapper for adding the values to node-sass, and an example of just one of our SCSS files being compiled looks like this: https://gist.github.com/itsnydell/6c51c9e9c944678a958c

That's based on our config:
```
sass: {
    options: {
        sourceMap: true
    },
    desktop: {
        files: [{
            expand: true,
            cwd: 'public/css/desktop',
            src: ['*.scss'],
            dest: 'public/css/desktop',
            ext: '.css'
        }]
    },
    mobile: {
        files: [{
            expand: true,
            cwd: 'public/css/mobile',
            src: ['*.scss'],
            dest: 'public/css/mobile',
            ext: '.css'
        }]
    }
},
```

It takes every file in the folder and triggers an async call to node-sass for each. 

By attempting to recreate your settings in your examples by removing the path in destination, it just adds all of the compiled css files to the home directory of our site (This is by design in grunt). Adding each file manually to be compiled is also very impractical, since our site is so large. 

In our ```public/css/desktop``` folder, there are many SCSS files which pull in different combinations of SCSS from our multiple site-specific and shared folders to generate a specific page type's CSS. Such as home.css, article.css, static.css, list.css, feature.css etc. 

I believe the ```sourceRoot``` option or updating the "by design" logic to handle cases such as this, for generating the sources in the sourcemap files would be the only way to solve this. I'm sure many other large sites won't be able to use any grunt project that uses node-sass unless there is a better way of handling folders of scss files to be compiled instead creating a defined list of files to be compiled.

**Comment by am11** [comment] 2015-03-03 17:38
@itsnydell, grunt-sass should had implement the node-sass API correctly. 

Lets try this: in your `node_modules` directory, open `node-sass/lib/index.js` and apply this patch and retry:

```diff
diff --git a/lib/index.js b/lib/index.js
index 8e8a149..7a22078 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -45,7 +45,7 @@ function getOutFile(options) {
     return outFile;
   }

-  return path.resolve(path.dirname(file), outFile);
+  return path.resolve(process.cwd(), outFile);
 }

 /**
@@ -114,7 +114,7 @@ function getSourceMap(options) {
     if (typeof sourceMap !== 'string') {
       sourceMap = outFile ? outFile + '.map' : '';
     } else if (outFile) {
-      sourceMap = path.resolve(path.dirname(file), sourceMap);
+      sourceMap = path.resolve(process.cwd(), sourceMap);
     }
   }

@@ -132,7 +132,7 @@ function getOptions(options, cb) {
   options = options || {};
   options.sourceComments = options.sourceComments || false;
   options.data = options.data || null;
-  options.file = options.file || null;
+  options.file = path.resolve(process.cwd(), options.file) || null;
   options.outFile = getOutFile(options);
```

**Comment by itsnydell** [comment] 2015-03-03 17:45
@am11 I applied those 3 line changes but to the sources still look like this:

```
	"sources": [
		"../../../home.scss",
		"../../../main.scss",
		"../../../partials/_viewport-slider.scss",
		"../../../partials/_ad-related.scss",
		"../../../partials/_tags.scss",
		"../../../partials/_agenda-slider.scss",
		"../../../partials/_news-module.scss",
		"../../../../shared/common.scss",
		"../../../_mixins.scss",
		"../../../reset.scss",
		"../../../common/_common.scss",
		"../../../common/_aside_navigation.scss",
		"../../../common/_top_navigation.scss",
		"../../../common/_desktop_responsive.scss",
		"../../../common/_footer.scss",
		"../../../common/_not-found-article-feed.scss",
		"../../../../shared/editors-picks.scss",
		"../../../../google-fonts.scss",
		"../../../../normalize.scss",
		"../../../../angular-carousel.scss",
		"../../../../oo_footer.scss",
		"../../../../shared/social-bar.scss",
		"../../../../shared/social-buttons.scss",
		"../../../common/_reset.scss",
		"../../../../lib/bootstrap/mixins/_responsive-visibility.scss",
		"../../../../lib/bootstrap/_responsive-utilities.scss"
	],
```

**Comment by itsnydell** [comment] 2015-03-03 17:52
Also just for your reference, here is the grunt-sass file that triggers the node-sass render.

```
'use strict';
var path = require('path');
var eachAsync = require('each-async');
var assign = require('object-assign');
var sass = require('node-sass');

module.exports = function (grunt) {
	grunt.verbose.writeln('\n' + sass.info() + '\n');

	grunt.registerMultiTask('sass', 'Compile Sass to CSS', function () {
		eachAsync(this.files, function (el, i, next) {
			var opts = this.options({
				precision: 10
			});

			var src = el.src[0];

			if (!src || path.basename(src)[0] === '_') {
				next();
				return;
			}

			sass.render(assign({}, opts, {
				file: src,
				outFile: el.dest,
				success: function (res) {
					grunt.file.write(el.dest, res.css);

					if (opts.sourceMap) {
						grunt.file.write(opts.sourceMap === true ? (el.dest + '.map') : path.relative(process.cwd(), opts.sourceMap), res.map);
					}

					console.log(process.cwd());

					next();
				},
				error: function (err) {
					grunt.log.error(err.message + '\n  ' + 'Line ' + err.line + '  Column ' + err.column + '  ' + path.relative(process.cwd(), err.file) + '\n');
					grunt.warn('');
					next(err);
				}
			}));
		}.bind(this), this.async());
	});
};
```

**Comment by am11** [comment] 2015-03-03 18:12
Ops, it was untested. Please revert it back.  :)

In that grunt-sass code, try changing:

```javascript
outFile: el.dest,
```

to:

```javascript
outFile: path.resolve(path.resolve(src), path.resolve(el.dest)),
```

**Comment by itsnydell** [comment] 2015-03-03 18:51
@am11 Apologies, when I made the updates to node-sass it was to the separate version I installed. I went ahead and updated the node-sass that was included with grunt-sass and the sources look correct now:

```
"sources": [
		"home.scss",
		"main.scss",
		"partials/_viewport-slider.scss",
		"partials/_ad-related.scss",
		"partials/_tags.scss",
		"partials/_agenda-slider.scss",
		"partials/_news-module.scss",
		"../shared/common.scss",
		"_mixins.scss",
		"reset.scss",
		"common/_common.scss",
		"common/_aside_navigation.scss",
		"common/_top_navigation.scss",
		"common/_desktop_responsive.scss",
		"common/_footer.scss",
		"common/_not-found-article-feed.scss",
		"../shared/editors-picks.scss",
		"../google-fonts.scss",
		"../normalize.scss",
		"../angular-carousel.scss",
		"../oo_footer.scss",
		"../shared/social-bar.scss",
		"../shared/social-buttons.scss",
		"common/_reset.scss",
		"../lib/bootstrap/mixins/_responsive-visibility.scss",
		"../lib/bootstrap/_responsive-utilities.scss"
	],
```

**Comment by am11** [comment] 2015-03-03 19:28
Glad to know it worked out for you! :+1:

**Closed by am11** 2015-03-03 19:28 UTC
Labels: By Design, Discussion

**Comment by itsnydell** [comment] 2015-03-03 19:30
@am11 Will this functionality not be added? If not, I'll be sure to fork this project so that we can roll-out with the grunt-sass & node-sass for our site.

**Comment by am11** [comment] 2015-03-03 19:57
Are you still facing the issue? Do you mean `sourceRoot` in source-map?

**Comment by am11** [comment] 2015-03-03 20:35
@itsnydell, what is the v8 version of your node? `node -p process.versions.v8`

**Comment by itsnydell** [comment] 2015-03-03 20:39
@am11 The issue was fixed by hacking the code of node-sass inside a dependency of grunt-sass. The 3 line changes you suggested above. It wasn't a solution, just a hack that would need to be applied every time we run npm install on one of our developer's machines. 

I'm wondering if this fix would be committed to the code in node-sass, so future npm installs of node-sass or grunt-sass would pull code that works out of the box. If there is no intention of applying this fix, then I will fork these two repositories so that we can pull an updated version for all of the developers at my company to use. 

```ShellSession
node -e "console.log(process.versions.v8)"
3.14.5.10
```

**Comment by am11** [comment] 2015-03-03 20:51
Yes it will be applied. I have already opened a PR.  :)

Sent from my Windows Phone
________________________________

**Comment by itsnydell** [comment] 2015-03-03 20:54
@am11 Appreciated! I'll keep watch on the PR so we can get this introduced into our workflow as soon as possible.

**Comment by am11** [comment] 2015-03-03 21:41
@itsnydell, can you test verify that commit? Since there are some breaking changes, gulp-sass code would need to be updated.

```bash
cd into/gulp-sas-directory
cd node_modules
rm -rf node-sass # delete existing node-sass
git clone https://github.com/am11/node-sass --recursive
cd node-sass
npm install  # ignore errors if any
mkdir vendor ; cd vendor
mkdir linux-x64-3.14.5  #are you using linux x64 or darwin (Mac)? change it accordingly
cd linux-x64-3.14.5  # same here, change it accordingly
wget https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-node-0.10/binding.node
cd ../../../../tasks
```

Next, edit sass.js and replace the content with https://gist.github.com/am11/47fc07b5d6de73697ee9. 

Finally, give it a shot! :rugby_football:

**Comment by am11** [comment] 2015-03-03 21:44
`npm -p 'console.log(process.arch, process.platform)'` will tell you the exact arch and platform names.

Disclaimer, I haven't tested the grunt-sass code.

**Comment by itsnydell** [comment] 2015-03-03 22:08
@am11 Hey, we aren't actually using gulp-sass, but I'll make these changes with grunt-sass and let you know how it goes. 

It's all being run on local dev environment and can be reverted at any time.

**Comment by itsnydell** [comment] 2015-03-03 22:19
```Shell
grunt sass
Loading "sass.js" tasks...ERROR
>> TypeError: Property 'info' of object #<Object> is not a function
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-03 22:16:37 UTC)
loading tasks  428ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 429ms
```

**Comment by am11** [comment] 2015-03-03 22:30
@itsnydell, lol I mixed up the names. The gist I made has code for grunt-sass. I have updated the code.

**Comment by itsnydell** [comment] 2015-03-03 22:33
@am11 That worked perfectly with the updated script.

**Comment by am11** [comment] 2015-03-03 22:35
Awesome! So the PR is good to go. :sunglasses: 

Thanks for your quick replies. :+1:

**Comment by itsnydell** [comment] 2015-03-03 22:39
@am11 Great, I'll keep my eye out for the update and see about getting this fixed in Grunt-sass. I do appreciate all of your help!

@sindresorhus

**Comment by am11** [comment] 2015-03-03 22:47
@itsnydell FYI: https://github.com/sass/libsass/pull/915, `sourceRoot` is also coming! :)

It might not land in node-sass vNext but surely in vNext->next. :zap:

**Comment by itsnydell** [comment] 2015-03-03 22:55
@am11 I look forward to these changes and hope it helps many other people use it in their projects.

**Comment by rakesh-nakrani** [comment] 2022-06-22 05:57
I made resolution after comment on the css beautify code in gulpfile.js

`//.pipe(cssbeautify())`
