### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node":

### ISSUE THREAD

**Issue by donruperto** [sass/node-sass#2780] opened 2019-11-09 06:51 UTC
- NPM version (`npm -v`): 6.12.0

We are using NPM to restore packages in our Azure DevOps build pipeling. Everythink worked until today. Now we are getting the following error:

Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node":
HTTP error 404 Not Found

When I paste the URL into the browser I also get a 404, so it´s not a problem on the build server. When I change the URL in the browser to **v4.12.0** the file is downloaded. 

But I need the file with **v4.10.0** because I cannot change the version in the npm build plugin that is performing the download. Has the file been removed for a special reason?

Thx in advance

**Comment by nschonni** [comment] 2019-11-09 06:53
Duplicate of #2779

**Closed by nschonni** 2019-11-09 06:53 UTC
