### ISSUE TITLE
Can't use either 2.0.1 nor 1.2.3; 

### ISSUE THREAD

**Issue by haf** [sass/node-sass#753] opened 2015-03-12 15:24 UTC
With node v0.12.

Error message:

    `libsass` bindings not found. Try reinstalling `node-sass`

Cross-posted here https://github.com/webpack/webpack/issues/880

**Comment by am11** [comment] 2015-03-12 15:29
@haf, please see our [bug reporting guidelines](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md#bug-reports). If you need help, you need to at least specify, which platform, version, etc.

Also see:
https://github.com/sass/node-sass/issues/751#issuecomment-78501068.

**Comment by haf** [comment] 2015-03-12 15:33
Sure,

It's CentOS 7 x64, Node v0.12 from their home page.

**Comment by am11** [comment] 2015-03-12 15:37
Thank you. 
Can you show the output of:

```bash
cd /tmp
npm install node-sass@3.0.0-pre
```

**Comment by haf** [comment] 2015-03-12 15:37
Actually, I just did that, hehe.

**Comment by am11** [comment] 2015-03-12 15:40
And did it work? :checkered_flag:

**Comment by haf** [comment] 2015-03-12 15:44
```
Step 8 : RUN /usr/local/node/bin/npm install -g node-sass
 ---> Running in 92bae569cbbe
/usr/local/node/bin/node-sass -> /usr/local/node/lib/node_modules/node-sass/bin/node-sass

> node-sass@3.0.0-pre install /usr/local/node/lib/node_modules/node-sass
> node scripts/install.js

sh: node: command not found
npm ERR! Linux 3.18.1
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "-g" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.0.0-pre install: `node scripts/install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the node-sass@3.0.0-pre install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

**Comment by haf** [comment] 2015-03-12 15:44
But are you saying that v3.0 works well with webpack and there are no incompats?

**Comment by haf** [comment] 2015-03-12 15:47
Ok, I updated the `PATH` to contain node, now it's installing, let's see if the next major version is the solution to my woes :)

**Comment by haf** [comment] 2015-03-12 15:49
Now I'm getting

```
npm WARN package.json sass@0.5.0 No repository field.
npm WARN locking Error: EACCES, open '/home/builder/.npm/_locks/fractional-82a7cea1b094897d.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/builder/.npm/_locks/fractional-82a7cea1b094897d.lock failed { [Error: EACCES, open '/home/builder/.npm/_locks/fractional-82a7cea1b094897d.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/builder/.npm/_locks/fractional-82a7cea1b094897d.lock' }
npm ERR! Linux 3.18.1
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/builder/src/node_modules/fractional, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/builder/src/npm-debug.log
```
instead.

**Comment by am11** [comment] 2015-03-12 15:49
Yup. I built the Linux binaries on CentOS v5.11 (against the lowest glibc, so it is forward compatible).

Do you have node in your path? I would try using nvm: http://github.com/creationix/nvm/.

**Comment by haf** [comment] 2015-03-12 15:50
Yes, I added it to the path. See latest entry in this thread.

**Comment by haf** [comment] 2015-03-12 15:52
![screen shot 2015-03-12 at 16 52 26](https://cloud.githubusercontent.com/assets/193115/6621664/30e982f4-c8d8-11e4-87c3-f834e47eeb77.png)

**Comment by haf** [comment] 2015-03-12 16:09
So it doesn't work installing it globally, because you don't have ownership (why on earth would you need to? isn't it enough to be able to read it?) -- but installing it locally seems to work -- with `npm install --save-dev node-sass@3.0.0-pre`! Yey!

But we get this warning:

```
npm WARN unmet dependency /Users/src/logibit.se/node_modules/sass-loader requires node-sass@'^2.0.1' but will load
npm WARN unmet dependency /Users/src/logibit.se/node_modules/node-sass,
npm WARN unmet dependency which is version 3.0.0-pre
```

**Comment by haf** [comment] 2015-03-12 16:11
Sorry, that was on my mac, where it works (faster feedback cycle for me), but on centos:

```
npm WARN package.json qvitoo.com@0.0.5 No repository field.
npm WARN package.json sass@0.5.0 No repository field.
npm WARN unmet dependency /home/builder/src/logibit.se/node_modules/sass-loader requires node-sass@'^2.0.1' but will load
npm WARN unmet dependency /home/builder/src/logibit.se/node_modules/node-sass,
npm WARN unmet dependency which is version 3.0.0-pre

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/home/builder/src/logibit.se/node_modules/node-sass/lib/extensions.js:126:11)
    at Object.<anonymous> (/home/builder/src/logibit.se/node_modules/node-sass/lib/index.js:14:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/builder/src/logibit.se/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:460:26)
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/home/builder/src/logibit.se/node_modules/node-sass/lib/extensions.js:126:11)
    at Object.<anonymous> (/home/builder/src/logibit.se/node_modules/node-sass/lib/index.js:14:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/builder/src/logibit.se/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:460:26)
```

**Comment by am11** [comment] 2015-03-12 16:13
Yay! Yes I think somewhere we need to chown some directory. Similar issue was reported before: https://github.com/sass/node-sass/issues/736. I can't reproduce it locally. :confused:

**Comment by am11** [comment] 2015-03-12 16:16
I am presuming its your local system where you have access to `/tmp`? Can you run [this](https://github.com/sass/node-sass/issues/753#issuecomment-78504973)?

**Comment by haf** [comment] 2015-03-12 16:18
on CentOS 7:

```
$ pwd
/home/builder/src/node_modules/node-sass/vendor/darwin-x64-14
$ ls
binding.node
```

**Comment by haf** [comment] 2015-03-12 16:21
Yes, running that works, and also seems to create the correct folder. Let me verify that.

**Comment by haf** [comment] 2015-03-12 16:26
Ok, so the bug seems to be in npm which doesn't verify its bindings match the operating system they are on? Or is that in the install file for node-sass?

Yup... [here](https://github.com/sass/node-sass/blob/master/scripts/install.js#L79) is the bug. It should probably be more like bundler which verifies the OS against the compiled native extensions.

**Comment by am11** [comment] 2015-03-12 16:42
@haf, that is not a bug. you did not show the output of [this](https://github.com/sass/node-sass/issues/753#issuecomment-78504973).

I am closing this as a duplicate of https://github.com/sass/node-sass/issues/751. Lets continue this discussion there.

**Closed by am11** 2015-03-12 16:42 UTC
Labels: Duplicate

**Comment by haf** [comment] 2015-03-12 16:54
No that's wrong.

It's not a duplicate. I've already covered that in the previous comments.

As I said, it successfully installs when you have the node binary on the path, and that is not the problem I'm discussing in this thread.

This thread is about two things: the first thing is that I can't use sass-loader with webpack - because it's linking to 2.x and you're not supporting it; hence the title of this thread -- preferrably should @browniefed talk in this thread about that.

The second thing is that when I copy the context of my build from os x to the docker daemon, the node_modules where I have local npm packages installed, comes along. This means that in the vendor directory of your gem, is a darwin-compiled binary, despire npm install being called again. This is the bug I linked to.

So to be really clear: cd /tmp && npm install node-sass@3.0.0-pre works like expected, but you have a bug in the installer which chooses the compiled binary.

**Comment by am11** [comment] 2015-03-12 17:00
That is not a bug. This is by design. Our installer installs the binary for current operating system. If you need to keep binary for other operating system, then you should download it from release assets you can find here: https://github.com/sass/node-sass/releases/tag/v3.0.0-pre.

Also, here we do not discuss about issues of external modules.

**Comment by haf** [comment] 2015-03-12 17:01
Ok, well then make this issue about version 2.x not working.

**Comment by haf** [comment] 2015-03-12 17:01
And you're missing the point; your installer *doesn't* install the binary for the current OS, that's the bug.

**Comment by am11** [comment] 2015-03-12 17:03
@haf, you are keep changing your statements. Its not helping.

**Comment by haf** [comment] 2015-03-12 17:07
I'm sorry, I'm bad at explaining some times.

If I had been using only a single OS, the bug would not be exposed.

I am using two, one where I actually download the binary through your installer, and everything is OK! Another, which has access to the dirty git tree, with all the installed node modules - the inner OS.

The inner OS also runs npm install, but since the install.js file checks that just the *directory* of the native file exists, it assumes that directory has the right contents for the operating system; but at this point, it's not.

It might also be that npm doesn't call install.js at all, I'm not sure it does, but it seems likely it does. In that case it might be a bug in NPM.

Then there's the question of being able to use webpack with this repo. Right now, I'm getting: ``libsass` bindings not found. Try reinstalling `node-sass`` if using the latest non-prerelease version, and that's what I've been saying all along...

Do you see?

**Comment by am11** [comment] 2015-03-12 17:10
Would you like to talk about it on gitter chat instead? 
https://gitter.im/sass/node-sass/  (uses GitHub credentials)

**Comment by monokrome** [comment] 2015-03-12 22:53
Not sure if it helps, but I just ran into this same issue. Although the error make it look like it came from `none-sass`, it was actually because I was running `gulp` and hadn't installed `gulp-sass` yet. I'm not even sure how it reported the issue from `node-sass` in the first place, but figured that this may be a similar issue.

**Comment by xzyfer** [comment] 2015-03-12 23:06
>The second thing is that when I copy the context of my build from os x to the docker daemon, the node_modules where I have local npm packages installed, comes along. 

For the record this is a bug in 2.0.1 which is the current stable release. However 3.0.0-pre doesn't' have this issue as it downloads the binaries into a different path based on the OS and runtime version.

For example given the following node-sass node-sass@3.0.0-pre will work in both environments but node-sass@2.0.1 (or lower) will not

- boot a linux docker contain on OSX host with a mounted filesystem
- `npm install node-sass@3.0.0-pre` on OSX host
- ssh in to the linux container
- `npm install node-sass@3.0.0-pre` on linux container

This is because the downloaded binary is put into a different path based on the OS and runtime node-sass is being run in. So you can now have it install for two environments at the same time with no issues. This is great if you check you node_modules into git for example.

**Comment by xzyfer** [comment] 2015-03-12 23:12
>This thread is about two things: the first thing is that I can't use sass-loader with webpack - because it's linking to 2.x and you're not supporting it;

2.0.1 is the current stable release. There is however a bug with the installer if you've downloaded the binary for one OS and then try to run or re-install node-sass on another OS (as noted above).

**Comment by xzyfer** [comment] 2015-03-12 23:16
Can you confirm the following works (or doesn't)

```
cd /tmp/foo
npm install sass-loader
```

This should install sass-loader and node-sass@2.0.1 as a dependency of it.

**Comment by am11** [comment] 2015-03-13 01:21
> There is however a bug with the installer if you've downloaded the binary for one OS and then try to run or re-install node-sass on another OS 

Actually there is a way for it:

```bash
# I am in host OS
npm install node-sass@3.0.0-pre
# yay! I got the latest bits
# now for some special use-case, I wan't to move this thing to guest OS
scp ./node-sass <username>@<my-host-ip>:/home/myprojects/projectX/node_modules/node-sass
# moved!
ssh <username>@<my-host-ip>
# password? 
cd /home/myprojects/projectX
npm rebuild node-sass
# should download the binary for guest OS, while keeping that of host
```

**Comment by yasinuslu** [comment] 2015-09-26 01:30
I think this might help tracking the issue.
TL:DR; I was also having this issue and i found out that npm checks for `darwin-x64-46` while node.js checks for `darwin-x64-11` when running.

-

```
Error: The `libsass` binding was not found in /Users/nepjua/code/react/meteor-webpack-react-kickstart/node_modules/node-sass/vendor/darwin-x64-11/binding.node
```

Npm logs:
```
 /Users/nepjua/code/react/meteor-webpack-react-kickstart/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.3.3 node_modules/node-sass
```

npm checks if `darwin-x64-46` binaries exists, and then node.js fails complaining `darwin-x64-11` doesn't exists. First i created a symlink `darwin-x64-11  =>  darwin-x64-46` and i got a `SIGTRAP` error instead. Then i downloaded https://github.com/sass/node-sass-binaries/raw/master/darwin-x64-11_binding.node to `darwin-x64-11/binding.node`, now everything works :)

PS: node-sass version `3.3.3`

**Comment by saper** [comment] 2015-09-26 07:33
Do you have node 0.10 installed somewhere? -11 binary is for node 0.10

**Comment by yasinuslu** [comment] 2015-09-26 11:12
I'm using nvm, here is the node.js installations i have:
```
   iojs-v2.5.0
        v0.12.7
->       v4.0.0
```

I was getting the error with [this](https://github.com/thereactivestack/meteor-webpack-react-kickstart) project, i thought webpack was running in v4.0.0 but i just realized that it was running under meteor which probably using node 0.10 as you're saying, sorry for the confusion :)

**Comment by xzyfer** [comment] 2015-09-27 08:45
@yasinuslu anytime you switch node/iojs versions with nvm you will need to rebuild the binary with `npm rebuild`. This is simply how node and npm work.
