### ISSUE TITLE
Rebuild with NodeJS 6 makes huge trace every time node-sass used

### ISSUE THREAD

**Issue by iddqdidkfa** [sass/node-sass#1493] opened 2016-04-27 13:49 UTC
After `npm rebuild node-sass` appeared: http://pastebin.com/S4wetaaX
and each time I use `grunt-sass` this huge trace appears in console.
Someone forgot to disable debug info?

**Comment by xzyfer** [comment] 2016-04-27 13:51
Duplicate of https://github.com/sass/node-sass/issues/1484

**Closed by xzyfer** 2016-04-27 13:51 UTC

**Comment by xzyfer** [comment] 2016-05-03 10:03
node-sass@v3.7.0 has been released.
