### ISSUE TITLE
SassError: Internal Error: Incompatible units: '%' and 'px' on using min/max  css function

### ISSUE THREAD

**Issue by rahul3v** [sass/node-sass#2963] opened 2020-09-04 05:36 UTC
While using css functions produces error as: 

css code:
```css
width:max(50%,500px)
/*or*/
width:min(50%,500px)
```

error:
```error
failed to compile


./src/assets/scss/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!.
/node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!.
/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/index.scss)

SassError: Internal Error: Incompatible units: '%' and 'px'.
```

using ` "node-sass": "^4.14.1"`

**Comment by nschonni** [comment] 2020-09-04 18:41
Duplicate of #2815

**Closed by nschonni** 2020-09-04 18:41 UTC
