### ISSUE TITLE
segmentation fault in materialize css 

### ISSUE THREAD

**Issue by tjastine** [sass/node-sass#1479] opened 2016-04-25 13:17 UTC
Hi. I'm having trouble in node-sass v3.5.3. the materializecss when compiled has a segmentation fault error. can you look on this?

**Comment by mgreter** [comment] 2016-04-25 13:47
Duplicate of #1416 - please [use the search] [1] before opening new issues :exclamation: 

[1]: https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue+segmentation+fault+in+materialize+css

**Closed by mgreter** 2016-04-25 13:47 UTC

**Comment by jrm2k6** [comment] 2016-04-25 14:49
Isn't it more related to this https://github.com/sass/node-sass/issues/1464?
Any idea when the version will be marked as stable?
We are using laravel-elixir using gulp-sass, using node-sass which means we don't have the option of controlling the dependencies version.

**Comment by xzyfer** [comment] 2016-04-25 15:02
it'll be stable in the next 24 hours

On 4/26/16, Jeremy Dagorn <notifications@github.com> wrote:
> Isn't it more related to this
> https://github.com/sass/node-sass/issues/1464?
> Any idea when the version will be marked as stable?
> We are using laravel-elixir using gulp-sass, using node-sass which means we
> don't have the option of controlling the dependencies version.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/node-sass/issues/1479#issuecomment-214370413


-- 
Regards,
Michael

**Comment by jrm2k6** [comment] 2016-04-25 17:02
Thanks!
