### ISSUE TITLE
The obj.map returned to the success callback is a string in Libsass 3.next

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#623] opened 2015-01-14 05:35 UTC
Disclaimer: I'm beta testing Libsass 3.2 (master). 

The recent sourcemaps refactor must've have changed something because the `obj.map` returned to the `success` callback is `'{}'` (string) rather than `{}` (object) when `sourceMap: false` is set.

**Comment by am11** [comment] 2015-01-14 06:07
This is by design. We are [forwarding the source-map string](https://github.com/sass/node-sass/blob/7daf37364356992b9439cf15a4402282dbd930a7/lib/index.js#L169) from libsass as is. This was an experimental change in beta that we were parsing the string (with `JSON.parse(..)`) and returning the object, but it doesn't make sense because the consumer can do the same if required. 

This way the large JSON object parsing (no matter how fast it is) wouldn't be imposed on the consumer who just wanted to write source-map string to the file without any modification -- which in fact is a very viable use-case; they would have to `JSON.strigify()` it again and encounter the perf hit twice.

However, we do parse [error JSON as object](https://github.com/sass/node-sass/blob/7daf37364356992b9439cf15a4402282dbd930a7/lib/index.js#L150), so user gets a well-composed error object:


```javascript
    error: function(error) {
        // error is an object: v2 change
        console.log(error.message);
        console.log(error.code);
        console.log(error.line);
        console.log(error.column); // new in v2
    },
```

**Comment by xzyfer** [comment] 2015-01-14 06:25
Am I correct in understanding this change will land in the 2.0.0 stable?

Asking in regards to https://github.com/dlmanning/gulp-sass/pull/168

**Comment by am11** [comment] 2015-01-14 09:30
Yes this is correct. 2.0.0-stable will bring this behavior to the mix. :)

Regarding gulp-sass, I am not sure why is it required to post-process path resolution? In principle, node-sass should manufacture correct options (even altering those coming from upstreams) before passing to  libsass, so to get correct paths for source-map and `sourceMappingURL` (CSS comment) in return.

Can you shed some light what are the input options and expected result? The canonical path functionality in libsass is very promising. No matter how many times I tried to prove it wrong, it always turns out to node-sass fault, @mgreter has covered all bases there! :wink:. So after trial and error, we have perfected that part (but we never know). :warning: 

PS: this will be a great time to fix the last moment bugs, when we are waiting for someone to stepup and build Linux binaries.

**Comment by xzyfer** [comment] 2015-01-14 11:06
> Can you shed some light what are the input options and expected result

Frankly I had no clue :) this is square @mgreter territory.

> this will be a great time to fix the last moment bugs

do you have any particular bugs in mind? A lot of work has gone into Libsass since the 3.1.0 release so unless there is a critical bug the next release will be 3.2.0.

**Comment by am11** [comment] 2015-01-14 11:10
Nops, I was just asking; why are you post-processing source-map's `sources[]` array in gulp-sass commit? libsass via node-sass should emit the correct path in first place (hint: configurable node-sass options). :)

**Comment by xzyfer** [comment] 2015-01-14 11:12
That code was already there, I just changed indenting because I wrapped it in an `if` :)

I've closed that PR now since this is going to be API change in 2.0.0 stable it needs to be fixed properly in gulp-sass.

**Comment by am11** [comment] 2015-02-12 17:51
The *stringly-typed* source-map has landed with v2. :sunglasses:

**Closed by am11** 2015-02-12 17:51 UTC
Labels: Discussion, Source Map, v2
