### ISSUE TITLE
Please add 'watch' option to Javascript options object to make watcher work running in nodejs too

### ISSUE THREAD

**Issue by Friksel** [sass/node-sass#2707] opened 2019-07-09 19:17 UTC
It's great to have a watcher feature on the terminal command, but I also like to use it when using node-sass inside node. Not sure why it's not already there, but a property for node-sass running in javascript to set `watch` to `true` would be very welcome!

**Comment by saper** [comment] 2019-10-17 03:12
Watching adds additional complexity that could not possibly be squeezed into the `render()` function.

Feel free to build an own module based on https://github.com/sass/node-sass/blob/e3ab6e18c54a1cf2f1954508942188038a4f19a1/bin/node-sass#L237 and https://github.com/sass/node-sass/blob/e3ab6e18c54a1cf2f1954508942188038a4f19a1/lib/watcher.js

Such a module could be a great contribution to making CLI a separate module altogether https://github.com/sass/node-sass/issues/1156

**Comment by xzyfer** [comment] 2019-10-17 05:05
I believe this is exposed on the v5 branch

**Comment by saper** [comment] 2019-10-17 12:17
This is actually duplicate of the issue https://github.com/sass/node-sass/issues/1056

We have so many issues around watching feature - maybe this should become a separate project altogether...

**Closed by saper** 2019-10-17 12:17 UTC
Labels: Feature - Request, Invalid - Duplicate, Module - Watcher
