### ISSUE TITLE
Installation failure on Linux when process.execPath is relative

### ISSUE THREAD

**Issue by bobbwal** [sass/node-sass#1323] opened 2015-12-31 01:12 UTC
I've been through the troubleshooting but no node-sass/vendor folder is created so that's as far as I can go. Here's my output https://gist.github.com/bobbwal/f4ce61210ff88d9f9f85

Thanks

**Comment by bobbwal** [comment] 2015-12-31 13:19
Also the server is running Ash shell, not sure if this could be a problem. I noticed this comment in another issue:
"npm install executes a normal shell and tells it to run node scripts/install.js. If it can't find node (or this is some kind of funky restricted shell), things won't work."

**Comment by saper** [comment] 2016-01-01 00:45
`bash` is by no means mandatory; I am using FreeBSD's `/bin/sh` without any issues. The shell needs to understand `sh -c` convention and be able to find node interpreter using `PATH` environmental variable. What is your `SHELL` set to? Does `/bin/sh -c node` invoke your node interpreter?

**Comment by bobbwal** [comment] 2016-01-01 01:18
Hi, I'm guessing that command invokes the interpreter, no errors.
    
    $ echo $SHELL
    /bin/ash

    $ /bin/sh -c node
    >

**Comment by abhijitghogre** [comment] 2016-01-01 14:28
Facing this issue on OS X El Capitan!

**Comment by saper** [comment] 2016-01-01 19:22
@bobbwal is /bin/sh and /bin/ash the same binary? Does it help if you try bash? Is the current directory symlinked?

**Comment by bobbwal** [comment] 2016-01-01 19:59
/bin/sh and /bin/ash are identical but I'm not sure what this means. Bash is not installed but I can have a statically compiled bash added on request. The directory is symlinked `www -> /www`

**Comment by saper** [comment] 2016-01-02 01:11
This symlink is interesting - can you elaborate more on the directory structure used? Where is your  `node_modules` directory? Is this some well-known hosting environment (maybe there are public accounts to test and try to reproduce the issue)?

**Comment by saper** [comment] 2016-01-02 01:32
What is your `process.execPath` ?

**Comment by saper** [comment] 2016-01-02 01:49
Can you try running the following snippet under your `node`:
````js
var fs=require('fs'); console.log(process.execPath); console.log(fs.lstatSync(process.execPath)); fs.realpathSync(process.execPath);
````

**Comment by bobbwal** [comment] 2016-01-02 01:59
Here you go:

    > var fs=require('fs'); console.log(process.execPath); console.log(fs.lstatSync(process.execPath)); fs.realpathSync(process.execPath);
    node
    Error: ENOENT: no such file or directory, lstat 'node'
        at Error (native)
        at Object.fs.lstatSync (fs.js:839:18)
        at repl:1:69
        at REPLServer.defaultEval (repl.js:248:27)
        at bound (domain.js:280:14)
        at REPLServer.runBound [as eval] (domain.js:293:12)
        at REPLServer.<anonymous> (repl.js:412:12)
        at emitOne (events.js:82:20)
        at REPLServer.emit (events.js:169:7)
        at REPLServer.Interface._onLine (readline.js:210:10)
    >
Directory structure (only included the stuff I thought was relevant):

    root
    ├── bin
    ├── www
    │   └── node_modules
    └── home
        ├── .gem
        ├── .npm
        ├── .npmi
        ├── .ssh -> /.ssh
        ├── log -> /log
        └── www -> /www

**Comment by saper** [comment] 2016-01-02 02:01
Do you know why `process.execPath` is relative? where is your node really located?

**Comment by saper** [comment] 2016-01-02 03:20
Do you have `/proc` filesystem available? What does `ls -lF /proc/self/exe` do when executed from the shell?

**Comment by saper** [comment] 2016-01-02 03:32
This is most probably caused by https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt

> Non-standard behavior
> ---------------------

(...)

> Symlinks in /proc/PID/ and /proc/PID/fd which point to a non-directory
> object in overlayfs will not contain valid absolute paths, only
> relative paths leading up to the filesystem's root.  This will be
> fixed in the future.

(kudos to https://gist.github.com/shimarin/5c1833dcbb3ea4c04256#gistcomment-1546393)

**Comment by xzyfer** [comment] 2016-01-02 04:47
Sounds like this should be fixed by #1322.

**Comment by saper** [comment] 2016-01-02 12:59
Don't think so, as this is the problem occurring in our installer, not the CLI. The fix will be simple once we fully understand the issue.

**Comment by bobbwal** [comment] 2016-01-02 15:46
Hi, not really sure about the `/proc` file system, appears not?

    $ ls -lF /proc/self/exe
    ls: /proc/self/exe: No such file or directory

**Comment by saper** [comment] 2016-01-02 16:50
> Hi, not really sure about the `/proc` file system, appears not?

Is there a `mount` command you can possibly run?

**Comment by bobbwal** [comment] 2016-01-02 22:32
Struggling a little on this but `mount` doesn't appear to be an available command.

**Comment by saper** [comment] 2016-01-03 00:06
@bobbwal can you check if #1325 fixes this for you?

**Comment by bobbwal** [comment] 2016-01-03 00:47
@saper it works!

**Comment by saper** [comment] 2016-01-03 00:52
Happy to hear that! Thank you for helping us to locate this issue .... and lots of luck working in your ehm environment :)

**Comment by bobbwal** [comment] 2016-01-03 00:56
Thanks, and good work :)

**Comment by xzyfer** [comment] 2016-01-20 09:15
This fix is on master and will be the next release.

**Closed by xzyfer** 2016-01-20 09:15 UTC
Labels: Bug - Confirmed, NPM - Install, OS - Linux
