### ISSUE TITLE
where is linux_musl-x64-67_binding.node ?

### ISSUE THREAD

**Issue by uncleGena** [sass/node-sass#2535] opened 2018-11-02 17:35 UTC
error when building docker
```
> node-sass@4.9.0 install /web/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/linux_musl-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/linux_musl-x64-67_binding.node": 

HTTP error 404 Not Found
```
all info that I can provide is version of node inside container
- node -v v11.0.0:

Why it tries to download that version?

**Comment by csh0rt** [comment] 2018-11-02 18:52
Are you using node:alpine as your starter image? If so, try changing your Dockerfile's FROM to a different version of node:alpine. node:10-alpine worked for me after I cleared all images, npm cache, rebuilt sass, etc.

Seems like an issue with the newest version of node:alpine (11). They pushed a small update ~6 hours ago.

**Comment by ToogiiB** [comment] 2018-11-02 19:50
yeah, it worked 10-alpine. required couple of hours to figure out why it stopped working today :)

**Comment by bfaulk96** [comment] 2018-11-02 22:02
I opened an issue on the official docker-node repo (the one that makes updates to node:alpine and such) https://github.com/nodejs/docker-node/issues/895

**Comment by nschonni** [comment] 2018-11-02 22:05
Duplicate of #2521 please subscribe to that issue to be notified when it is resolved

**Closed by nschonni** 2018-11-02 22:05 UTC
