### ISSUE TITLE
Issue with imports in same directory

### ISSUE THREAD

**Issue by tHBp** [sass/node-sass#1588] opened 2016-06-11 07:20 UTC
I have a issue with imports of node-sass.
According to the error message, it cannot seem to find the **scss** import in the same directory structure.
Example, I have two files in my **X:\random\path\**
>   **foo.scss**
> **_foobar.my.import.file.scss**

And I **@import "foobar.my.import.file"** inside my **foo.scss** and try to compile **foo.scss**, the task fails and returns with cannot find file **foobar.my.import.file** inside **X:\random\path**

I have tried debugging the code with **node-inspector** too.
I have tracked down the error to **bindings.renderFile** function inside the **index.js** file.
I can't seem to proceed further because it is a **bindings.node** file and I don't know how to handle it.

**Comment by xzyfer** [comment] 2016-06-14 02:30
I am unable to reproduce this issue.

```sass
// index.scss
@import "foobar.my.import.file"
```
```sass
// _foobar.my.import.file.scss
a { b: c }
```
```
$ ./node_modules/.bin/node-sass index.scss
a {
  b: c; }
```

**Comment by tHBp** [comment] 2016-06-14 07:02
I tried compiling **https://github.com/oracle/oraclejet.** 
Specifically **/master/dist/scss/alta/oj-alta.scss**
My sass-compile file is 
```javascript
var sass = require('node-sass');
var fs = require('fs');
sass.render({
    file: 'oj-alta.scss',
    outputStyle: 'compressed'
}, function(error, result) {
	console.log('callback');
    if (error) {
        console.log('status:', error.status);
        console.log('column:', error.column);
        console.log('message:', error.message);
        console.log('line:', error.line);
    } else {
        fs.writeFileSync('./main.css', result.css);
        console.log('done css');
    }
});
```
It doesn't even print **callback**
The **oj-alta.scss** file is this 
```css
@import "oj.alta.variables";
@import "../3rdparty/normalize/normalize";
@import "oj.alta.widgets";
```

**Comment by xzyfer** [comment] 2016-06-14 10:16
Can you try adding `includePaths: [__dirname]` to the `render` config object?

**Comment by tHBp** [comment] 2016-06-14 15:13
I tried the same to no difference.
Although, I tried compiling font-awesome and it worked without even specifying the ```importer``` function and ```includePath```.
I wonder what is different in this case.

**Comment by nschonni** [comment] 2016-06-15 06:45
Can't reproduce either
 1. Download `oraclejet`
 1. cd into downloaded directory
 1. `npm i node-sass`
 1. copy script from above
 1. edit script to adjust file path to 'dist/scss//alta/oj-alta.scss'
 1. run script
```
callback
done css
```
menu.css created in the root with compressed output.

**Comment by tHBp** [comment] 2016-06-15 10:24
@nschonni  I tried your solution and it worked like a charm. Thanks for your input.
However, I do have one question. I was trying to do the same inside the **dist/scss/alta/** folder and I had done `npm install node-sass` inside that folder and my script was inside that folder too with scss file's path as '**oj-alta.scss**'. It was replicating the situation I mentioned earlier. So, is it somehow possible that `node-sass` might need a better importer function in the case when some of the imports are a level up from the directory in which the node script is running? Or is it something else?

**Comment by tHBp** [comment] 2016-06-17 08:01
@nschonni @saper @xzyfer Can you please confirm the same working for [**Oracle JET 2.0.1**](https://github.com/oracle/oraclejet/tree/2.0.1)
 instead of [**Oracle JET 2.0.2**](https://github.com/oracle/oraclejet/tree/2.0.2-b1) **(Pre-release)** version? I was trying the same on [**Oracle JET 2.0.1**](https://github.com/oracle/oraclejet/tree/2.0.1) and by the time of posting your comment, Oracle came out with their pre-release which seems to compile fine with node-sass.

This begets the question whether the library had buggy code or not.
To test that, I used compass (ruby) , and it compiled without any issue.

Any nudge in the right direction is highly appreciated. Thanks a lot.

**Comment by saper** [comment] 2016-06-17 18:51
@tHBp may I ask which node version are you running? Is it on Windows? If running Windows, is x: a real drive? Or a subst, networked or anything special?

**Comment by tHBp** [comment] 2016-06-17 19:28
@saper Thanks for reverting so quickly.
I'm on Windows 7 - x64.
The `X:` drive is an example. It is a normal `D:` drive. No networking, nothing special, normal HDD just.

I tried the solution @nschonni suggested and it worked perfectly for [**Oracle JET 2.0.2**](https://github.com/oracle/oraclejet/tree/2.0.2-b1) **(Pre-release)** version.

It required me to be outside the `scss` directory whilst running my node script.

I was trying the same with [**Oracle JET 2.0.1**](https://github.com/oracle/oraclejet/tree/2.0.1) and was unable to compile the scss.

I then tried Ruby Compass on JET 2.0.1 and it worked perfectly well.

My node script is mentioned in the thread above.

My question is, do I always have to be outside all sass directories which a code might import for node-sass to work? I'm asking because I can seem to compile font-awesome without any `includePath` paradigm and without any `importer` function and regardless of where I am executing my script.

Secondly, regarding the versions 2.0.1 and 2.0.2, I have tried debugging the code to find what might be cause for not rendering the css, but as I'm new to binding C++ libs with Node, I'm struggling to debug beyond the bindings.node file. So far the node-sass code is passing my parameters well to the `render` function of `bindings.node`, can it be a issue with Libsass?

**Comment by tHBp** [comment] 2016-06-27 03:59
Any sort of help would really be appreciated.
Thanks.

**Comment by xzyfer** [comment] 2016-06-29 11:25
> regarding the versions 2.0.1 and 2.0.2

Is this referring to your node-sass version? If so please update to a newer version. We no longer support node-sass < 3.8.0 because of the many changes in LibSass.

**Comment by tHBp** [comment] 2016-06-29 11:48
@xzyfer It refers to the versions of the library in question (Oracle JET) and not the node-sass version.
node-sass version I'm using is 3.8.0 only

**Comment by nschonni** [comment] 2016-06-30 03:11
@tHBp the JET library is large (and fixed in their master), if you want us to troubleshoot something we need [Short, Self Contained, Correct (Compilable), Example](http://www.sscce.org/) as explained in the [CONTRIBUTING.md]( https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by tHBp** [comment] 2016-06-30 03:18
@nschonni Okay sure, will keep that in mind for future reports. Thanks a bunch.

**Closed** 2016-06-30 03:19 UTC
Labels: Awaiting Response, Invalid - Not Reproducible
