### ISSUE TITLE
Node Sass version 9.0.0 is incompatible with ^4.0.0.

### ISSUE THREAD

**Issue by real-artswan** [sass/node-sass#3369] opened 2023-06-07 23:41 UTC
- NPM version (`npm -v`):
8.11.0

- Node version (`node -v`):
v16.15.1

- Node Process (`node -p process.versions`):
{
  node: '16.15.1',
  v8: '9.4.146.24-node.21',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1o+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
- Node Platform (`node -p process.platform`):
linux

- Node architecture (`node -p process.arch`):
x64

- node-sass version (`node -p "require('node-sass').info"`):
node-sass       9.0.0   (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`):
- node-sass@9.0.0

So the problem is here `Node Sass version 9.0.0 is incompatible with ^4.0.0.` what does it mean actually? Does it come from the `node-sass` I believe? What lib is "^4.0.0"?

```
yarn run v1.22.19
$ GENERATE_SOURCEMAP=false node_modules/.bin/react-scripts --max_old_space_size=4096 build
Creating an optimized production build...
Failed to compile.

./src/app.sass
Error: Node Sass version 9.0.0 is incompatible with ^4.0.0.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Imported to the App.tsx so 
`import './app.sass';`

**Comment by nschonni** [comment] 2023-06-08 05:54
Duplicate of #3103

**Closed by nschonni** 2023-06-08 05:54 UTC
