### ISSUE TITLE
Binary outputting to stderr instead of stdout

### ISSUE THREAD

**Issue by jwerre** [sass/node-sass#1543] opened 2016-05-11 21:59 UTC
You can duplicate this error like so:

	var spawn = require('child_process').spawn;
	var sass = spawn('./node_modules/.bin/node-sass', options);

	// This is always called even if there is no error
	sass.stderr.on('data', function(err) {
		console.log(err.toString().trim());
	});

	// This is never called
	sass.stdout.on('data', function(data) {
		console.log(data.toString().trim()); 
	});

	sass.on('close', function(code) {
		console.log(code);
	});

**Comment by nschonni** [comment] 2016-05-12 04:20
Duplicate of #1353

**Closed by nschonni** 2016-05-12 04:20 UTC
