### ISSUE TITLE
Webpack build randomly crash when using node-sass 4.8.1

### ISSUE THREAD

**Issue by Guymestef** [sass/node-sass#2285] opened 2018-03-13 10:02 UTC
- NPM version (`npm -v`):5.6.0
- Node version (`node -v`):9.80
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '9.8.0',
  v8: '6.2.414.46-node.21',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '2',
  openssl: '1.0.2n',
  icu: '60.2',
  unicode: '10.0',
  cldr: '32.0.1',
  tz: '2017c' }
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.8.1   (Wrapper)       [JavaScript]
libsass         3.5.0   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`):-- node-sass@4.8.1

After upgrading node-sass to v4.8.1, I have random crash with webpack. If I downgrade to node-sass v4.7.2 everything is working fine.
I'm using webpack 4 with CleanWebpackPlugin, ExtractTextPlugin, DllReferencePlugin.

The debug log of a crash:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-vs' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prebuild-vs', 'build-vs', 'postbuild-vs' ]
5 info lifecycle publication@1.0.0~prebuild-vs: publication@1.0.0
6 info lifecycle publication@1.0.0~build-vs: publication@1.0.0
7 verbose lifecycle publication@1.0.0~build-vs: unsafe-perm in lifecycle true

10 silly lifecycle publication@1.0.0~build-vs: Args: [ '/d /s /c',
10 silly lifecycle   'node node_modules/webpack/bin/webpack.js --mode development' ]
11 silly lifecycle publication@1.0.0~build-vs: Returned: code: 3221226356  signal: null
12 info lifecycle publication@1.0.0~build-vs: Failed to exec build-vs script
13 verbose stack Error: publication@1.0.0 build-vs: `node node_modules/webpack/bin/webpack.js --mode development`
13 verbose stack Exit status 3221226356
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid publication@1.0.0
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-vs"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 3221226356
22 error publication@1.0.0 build-vs: `node node_modules/webpack/bin/webpack.js --mode development`
22 error Exit status 3221226356
23 error Failed at the publication@1.0.0 build-vs script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221226356, true ]

**Comment by xzyfer** [comment] 2018-03-13 10:08
Likely a duplicate of #2280. You try replacing the node-sass `vendor/win32-x64-59/binding.node` with the latest pre-release binding to see if it resolves the issue.

https://github.com/sass/node-sass/releases/download/v4.8.2/win32-x64-59_binding.node

**Comment by Guymestef** [comment] 2018-03-13 13:29
@xzyfer with the binding.node of v4.8.2 everything seems fine :thumbsup:

**Comment by xzyfer** [comment] 2018-03-13 13:30
Thank you

**Closed by xzyfer** 2018-03-13 13:30 UTC
