### ISSUE TITLE
Node v9.2.0 not supported

### ISSUE THREAD

**Issue by brendonco** [sass/node-sass#2152] opened 2017-11-15 02:03 UTC
When do you plan to support Node v9.2.0 not supported

Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3

**Comment by nschonni** [comment] 2017-11-15 02:54
Duplicate of https://github.com/sass/node-sass/issues/2129

**Closed by nschonni** 2017-11-15 02:54 UTC
Labels: Invalid - Old Node-Sass, Node 9
