### ISSUE TITLE
Import order has changed. Sass::SyntaxError: Undefined variable: "$import_counter".

### ISSUE THREAD

**Issue by subbu** [sass/node-sass#2486] opened 2018-08-31 13:13 UTC
I am using webpack in a Rails project and as part of compilation process node-sass is getting installed and I get the following error:

```
[4/4] Building fresh packages...
Done in 8.69s.
rake aborted!
Sass::SyntaxError: Undefined variable: "$import_counter".
/var/sg/releases/20180831104602/node_modules/node-sass/test/fixtures/depth-first/_vars.scss:1
/var/sg/releases/20180831104602/node_modules/node-sass/test/fixtures/depth-first/_common.scss:1

```
$import_counter is being declared in index.scss.
```

cat ./node-sass/test/fixtures/depth-first/index.scss
$import_counter: 0;
@import "a";
@import "common";
@import "b";

#the-last {
    content: "LAST";
}

```

But its not being loaded before _vars.scss.

Any idea how to change this order? Or is there a different way to fix this issue.

**Comment by nschonni** [comment] 2018-09-04 22:01
What version are you running? You deleted the issue template so it's harder to help.
This appears to be because you're running our internal test suite, which wouldn't be normal execution of the library.

**Comment by subbu** [comment] 2018-09-05 03:56
I am sorry, I thought it was meant to be removed. Should I create a new ticket?

**Comment by nschonni** [comment] 2018-09-05 23:45
Looks like a duplicate of #1750 because you're glob is including our test files

**Closed by nschonni** 2018-09-05 23:45 UTC
Labels: CLOSE - Issue template ignored
