### ISSUE TITLE
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.3/binding.node

### ISSUE THREAD

**Issue by miguelmota** [sass/node-sass#703] opened 2015-02-25 02:01 UTC
```
$ iojs -v
v1.3.0
$ node -v
v1.3.0
$ npm -v
2.5.1
$ npm install node-sass
npm WARN package.json path@0.4.10 path is also the name of a node core module.
|
> node-sass@2.0.1 install /Users/moogs/Dropbox/Development/project/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-iojs-1.3/binding.node

> node-sass@2.0.1 postinstall /Users/moogs/Dropbox/Development/project/node_modules/node-sass
> node scripts/build.js

module.js:322
    throw err;
          ^
Error: Cannot find module '/Users/moogs/Dropbox/Development/project/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:111:16)
    at node.js:799:3
Build failed
npm WARN unmet dependency /Users/moogs/Dropbox/Development/project/node_modules/broccoli-sass requires node-sass@'1.0.3' but wil
l load
npm WARN unmet dependency /Users/moogs/Dropbox/Development/project/node_modules/node-sass,
npm WARN unmet dependency which is version 2.0.1
node-sass@2.0.1 node_modules/node-sass
├── get-stdin@4.0.1
├── object-assign@2.0.0
├── replace-ext@0.0.1
├── nan@1.6.2
├── semver@4.3.1
├── shelljs@0.3.0
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── sass-graph@1.0.3 (commander@2.6.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── npmconf@2.1.1 (uid-number@0.0.5, inherits@2.0.1, osenv@0.1.0, ini@1.3.3, once@1.3.1, nopt@3.0.1, config-chain@1.1.8)
├── meow@3.0.0 (minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.1)
├── gaze@0.5.1 (globule@0.1.0)
├── mocha@2.1.0 (escape-string-regexp@1.0.2, diff@1.0.8, growl@1.8.1, commander@2.3.0, debug@2.0.0, glob@3.2.3, jade@0.26.3)
└── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, tunnel-agent@0.4.0,
 oauth-sign@0.6.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.9, tough-cookie@0.12.1,
 http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
```

**Comment by xzyfer** [comment] 2015-02-25 02:53
Duplicate of https://github.com/sass/node-sass/issues/699

**Closed by xzyfer** 2015-02-25 02:53 UTC

**Comment by fdambrosio** [comment] 2015-10-06 12:02
I have this problem

**Comment by xzyfer** [comment] 2015-10-06 14:20
@fdambrosio update to the latest node-sass@^3. If your problem persists open a new issue.
