### ISSUE TITLE
Could not find binding during install

### ISSUE THREAD

**Issue by karkcoder** [sass/node-sass#1768] opened 2016-10-26 05:33 UTC
I am getting the following issue while trying to install node-sass. It seems like the bindings are not online?

********************************************************************************
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.10.1 install C:\Web\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/win32-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.1/win32-x64-51_binding.node": ode:

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

********************************************************************************
- NPM version (`npm -v`): 4.0.0
- Node version (`node -v`): 7.0.0
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '7.0.0',
  v8: '5.4.500.36',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '51',
  openssl: '1.0.2j' }

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): N/A
- npm node-sass versions (`npm ls node-sass`): N/A

**Comment by xzyfer** [comment] 2016-10-26 05:35
Please search for issues before creating a new one. Duplicate of #1764, #1765, #1766

**Closed by xzyfer** 2016-10-26 05:35 UTC
