### ISSUE TITLE
Combination of length() and % causing abrupt exit

### ISSUE THREAD

**Issue by Bumxu** [sass/node-sass#692] opened 2015-02-21 17:14 UTC
I'm not sure if this is a bug and, if it is from **node-sass** or from **libsass**.

Apply **mod** operator to a ```length()``` function terminates **node-sass** abruptly with anything over it (middleware, express, etc...) without errors or messages.

```css
.item {
  left: length(('a','b','c')) % 3;
}
```

With **gem 3.4.12** result in:
```css
.item {
  prop: 0;
}
```

Doing things like ```3 % 3``` or ```length(('a','b','c')) / 3``` is OK.

**Comment by am11** [comment] 2015-02-21 17:21
The syntax issues belong to libsass. 

This is a duplicate of https://github.com/sass/libsass/issues/884. LibSass throws `SIGSEG`. Lets follow the progress there.

**Closed by am11** 2015-02-21 17:21 UTC
Labels: LibSass
