### ISSUE TITLE
SunOS support?

### ISSUE THREAD

**Issue by sanderson** [sass/node-sass#981] opened 2015-06-01 17:33 UTC
Trying to use node-sass on a SmartOS server which is a Solaris variant. Any chance node-sass will be compiled for SunOS? Currently it isn't.

**Comment by am11** [comment] 2015-06-01 18:32
This is an open issue for SunOS in binary repo: https://github.com/sass/node-sass-binaries/issues/32.

Technically, there shouldn't be any issue building binaries with GCC 4.7+ against SPARC, x86 and ia64. The only reason it never happened is because nobody contributed SunOS binaries to binaries repo. :) I tried configuring SunOS VM but ran into issues. If you have access to SunOS, would you like to contribute binaries? 

Here is the Linux Dockerfile for your reference (which we use to build Linux binaries): https://gist.github.com/am11/1529b2458b1a1f4bdba8. You may want to handle SPARC architecture separately for node.js (AFAICR, io.js doesn't support SunOS).

**Comment by xzyfer** [comment] 2015-06-11 03:13
Unless there a community advocate for AIX willing to generate binaries for release, or provide an automated solution we cannot not actively support it.

**Comment by saper** [comment] 2015-06-11 08:25
I think @xzyfer mean Solaris but this applies to AIX too (#988)

**Comment by djensen47** [comment] 2015-07-06 17:20
It also appears that compiling node-sass on SmartOS/Solaris is broken, again.

**Comment by saper** [comment] 2015-07-07 00:31
We need:

- [ ] to know how many platform variants do we have/need to support
- [ ] to have a good C++11 compiler (can be `gcc`, `clang`, possibly some other)
- [ ] it should be researched what kind of C++ runtime libraries need to supported (GNU's `libstdc++`, clang's `libc++`, any other?)
- [ ] ability to install and switch between various versions of `node` and `iojs`. (`NODE_MODULE_VERSION` values 11, 14, 42, 43, 44)
- [ ] ability to automate all those builds and running `npm test` on them.
- [ ] ability to extract and package generated binding files

**Comment by xzyfer** [comment] 2015-07-13 03:43
>Does this mean that SmartOS/Solaris is no longer supported by the Sass community.

No. We want LibSass and node-sass to run everywhere. We however do not currently have a hosted CI solution for SunOS to monitor breakages, or anyone in with SunOS experience volunteering to help with building binaries (or helping with an automated solution). 

This is why we continue to see regressions in building LibSass on SunOS, and why don't offer prebuilt SunOS binaries for node-sass. If this is something you have the experience and time for we'd love to have your help maintaining SunOS support.

**Comment by xzyfer** [comment] 2016-01-20 09:44
Closing due to lack of interest.

**Closed by xzyfer** 2016-01-20 09:44 UTC
Labels: BLOCKED, Community - Help Wanted, Discussion - Proposal, OS - Other
