### ISSUE TITLE
Error installing 3.13.1

### ISSUE THREAD

**Issue by shravan2x** [sass/node-sass#2051] opened 2017-07-22 23:19 UTC
- NPM version (`npm -v`): 5.3.0
- Node version (`node -v`): 8.2.1
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
```
- npm node-sass versions (`npm ls node-sass`):
```
`-- (empty)
```

**Error**:
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

This is followed by some other resulting errors.

**Steps to reproduce**:
```
npm install node-sass@3.13.1
```

**Comment by nschonni** [comment] 2017-07-22 23:24
Duplicate of #2034

**Closed by nschonni** 2017-07-22 23:24 UTC

**Comment by DanielRuf** [comment] 2017-11-28 09:03
This still happens. It seems there is no release for 3.13.1. At least there is no tag for it.
