### ISSUE TITLE
Issue using ionic start helloWorld blank

### ISSUE THREAD

**Issue by TrevorBedsaul** [sass/node-sass#2388] opened 2018-05-20 23:46 UTC
When creating it, I run into a weird issue and I don't understand what I am doing wrong? Is it simply not compatible with my computer so I have to do this on a different one? This is the error I get:

> npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        > node-sass@4.7.2 install C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js

        > node-sass@4.7.2 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@10.1.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp ERR! System Windows_NT 10.0.16299
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        gyp ERR! node -v v10.1.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.7.2 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**The notable lines to me are these**

 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2

        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python

        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by nschonni** [comment] 2018-05-21 00:35
Duplicate of #2387
You've already been explained that you need to either downgrade your Node install or upgrade your node-sass install. Please do not post duplicate issues

**Closed by nschonni** 2018-05-21 00:35 UTC

**Comment by TrevorBedsaul** [comment] 2018-05-21 00:40
@nschonni It is a duplicate because I have further understood my issue, and as you can see by the comments in my previous issue, it was never actually solved, yet somebody closed it...

**Comment by xzyfer** [comment] 2018-05-21 05:18
As @nschonni just said. The resolution is to update node-sass to 4.9.0 or
downgrade Node to < 10. You're currently using node-sass@4.7.2 which does
not support Node 10.

**Comment by TrevorBedsaul** [comment] 2018-05-21 05:41
@xzyfer @nschonni 
**Although, here is another example of where I have installed node-sass 4.9.0:**

$ npm install node-sass
C:\Users\student\AppData\Roaming\npm\node-sass -> C:\Users\student\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass

> node-sass@4.9.0 install C:\Users\student\AppData\Roaming\npm\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\student\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node

> node-sass@4.9.0 postinstall C:\Users\student\AppData\Roaming\npm\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\student\AppData\Roaming\npm\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
+ node-sass@4.9.0
added 187 packages from 139 contributors in 28.778s



**And still have run into the same error when I run this right after:**

$ ionic start helloWorld blank
√ Creating directory .\helloWorld - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS an
√ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  *   IONIC  DEVAPP  *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):



        > node-sass@4.7.2 install C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js


        > node-sass@4.7.2 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@10.1.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp ERR! System Windows_NT 10.0.16299
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        gyp ERR! node -v v10.1.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.7.2 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\student\AppData\Roaming\npm-cache\_logs\2018-05-21T05_37_07_513Z-debug.log


**So isn't something else going on? My professor told me to install the latest version of Node so I don't have the option to downgrade the node, but I shouldn't need to since my node-sass is at 4.9.0**

**Comment by nschonni** [comment] 2018-05-21 05:46
Sorry, we don't support Ionic, it has it's own quirks and we can't help you. Looking at their own docs they only appear to support Node 6 currently https://ionicframework.com/docs/cli/#installation

**Comment by xzyfer** [comment] 2018-05-21 06:02
>node-sass@4.7.2 install C:\Users\student\AppData\
Roaming\npm\helloWorld\node_modules\node-sass

There appear to be two versions on node-sass being used. You can confirm
with `npm ls node-sass`

**Comment by TrevorBedsaul** [comment] 2018-05-21 16:47
@xzyfer It only shows one version:

$ npm ls node-sass
C:\Users\student\AppData\Roaming\npm
`-- node-sass@4.9.0

**Comment by TrevorBedsaul** [comment] 2018-05-21 16:47
@nschonni So I should downgrade Node to Node 6? Do I have to downgrade node-sass as well?

**Comment by xzyfer** [comment] 2018-05-21 17:07
There's definitely two versions according to the output you pasted above. Try deleting node_modules and running npm install again

**Comment by TrevorBedsaul** [comment] 2018-05-21 17:21
I deleted it, reinstalled, and now I have this when I type npm ls node-sass: 
$ npm ls node-sass
C:\Users\student\AppData\Roaming\npm
`-- (empty)

Should I create my own node_modules?

**Comment by xzyfer** [comment] 2018-05-21 17:38
Running npm install should do that

**Comment by TrevorBedsaul** [comment] 2018-05-21 19:47
This is what happens when I run npm install:

student@DFRM9S72 MINGW64 ~/AppData/Roaming/npm (master)
$ ls
cordova*  cordova.cmd  etc/  ionic*  ionic.cmd  node-sass*  node-sass.cmd  npm*  npm.cmd  npx*  npx.cmd

student@DFRM9S72 MINGW64 ~/AppData/Roaming/npm (master)
$ npm install
up to date in 0.05s

student@DFRM9S72 MINGW64 ~/AppData/Roaming/npm (master)
$ ls
cordova*  cordova.cmd  etc/  ionic*  ionic.cmd  node-sass*  node-sass.cmd  npm*  npm.cmd  npx*  npx.cmd

**Comment by xzyfer** [comment] 2018-05-21 19:50
I'm sorry. This is notl longer a node-sass issue. We can't offer support
onnhownto use node and npm. Please talk to your lecturers or post on
stackpverflow for support.

**Comment by t-kalra** [comment] 2018-06-06 05:30
I was facing the similar issue. as mentioned above i rollback the node from v8.11.2 to v7.10.1 and uninstall node-sass and then reinstall again v4.9.0. It resolved the python 2 issue.
