### ISSUE TITLE
Import directives may not be used within control directives or mixins

### ISSUE THREAD

**Issue by vchyzhevskyi** [sass/node-sass#2059] opened 2017-08-03 10:05 UTC
- NPM version (`npm -v`): `5.2.0`
- Node version (`node -v`): `8.2.1`
- Node Process (`node -p process.versions`): ```{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.8.283.41',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }```
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`): ```node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]```
- npm node-sass versions (`npm ls node-sass`): `4.5.3`

Hello, I have experienced an error when using the next statement:

```
@if variable-exists(main-compile) == false 
    @import "../_themes"
```

Does anyone know how to workaround this or how to fix this?

**Comment by nschonni** [comment] 2017-08-03 15:55
Duplicate of #1471

**Closed by nschonni** 2017-08-03 15:55 UTC
