### ISSUE TITLE
Unable to install node-sass on FreeBSD11/amd64

### ISSUE THREAD

**Issue by gczuczy** [sass/node-sass#1946] opened 2017-04-07 15:32 UTC
Apparently it fails to find a binary package for FreeBSD11:

```
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> node-sass@4.4.0 install /usr/home/gczuczy/work/aegir/aegir-ui/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.4.0/freebsd-x64-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.4.0/freebsd-x64-51_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.4.0 postinstall /usr/home/gczuczy/work/aegir/aegir-ui/node_modules/node-sass
> node scripts/build.js
```

npm: 4.1.2
node: 7.6.0
```
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '7.6.0',
  v8: '5.5.372.40',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.12.0',
  modules: '51',
  openssl: '1.0.2k-freebsd',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```
node platform: freebsd
node arch: x64

And the followup build is failing due to a certificate issue, however I think this might not be a node-sass issue:
```
gyp http GET https://nodejs.org/download/release/v7.6.0/node-v7.6.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '7.6.0' ]
gyp verb remove using node-gyp dir: /usr/home/gczuczy/.node-gyp
gyp verb remove removing target version: 7.6.0
gyp verb remove removing development files for version: 7.6.0
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1081:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:186:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:599:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:429:38)
gyp ERR! System FreeBSD 11.0-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/home/gczuczy/work/aegir/aegir-ui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
```
ssl-strict is set to false.

Could you please help how could I get node-sass installed? Apparently everything depends on it.

**Comment by saper** [comment] 2017-04-14 22:31
My fault. The binaries are not yet there. But in general it should compile, can you install root certificates from ports to make sure downloader is happy?

**Comment by gczuczy** [comment] 2017-04-15 10:54
Actually I've turned off cert verification, and after that it was fine. Tho, it would really be some help if you provided these package.

**Comment by HeavenlyHost** [comment] 2017-04-19 09:24
Well I have tried to do the same but no luck

I am sitting behind an application called Artifactory which is the thing going out on the web to get my web dependencies. Any other request like the above is met with the company firewall stating that we can't do that.

I tried to download gulp in the same manner and it worked but I do not think it was attempting to download binaries directly from github...!

Can you give us an ETA on when this will be fixed ???

**Comment by nschonni** [comment] 2017-04-24 21:01
Closing as duplicate of #1911

**Closed by nschonni** 2017-04-24 21:01 UTC
Labels: NPM - Install
