### ISSUE TITLE
Invalid UTF-8

### ISSUE THREAD

**Issue by MarkusPint** [sass/node-sass#716] opened 2015-02-27 14:44 UTC
I have a very simple node-sass script:

    var sass = require('node-sass');
    var stats = {};
    sass.render({
    file: "./src/sass/test.scss",
    outFile: "./src/css/test.css",
    success: function(css) {
        console.log(css);
        console.log(stats);
    },
    error: function(error) {
        console.log(error);
    },
    stats: stats
    });

    console.log(stats);

Which prints in the console:

    {
    "status": 3,
    "message": "Invalid UTF-8",
    "code": 3
    }
What am I doing wrong?

**Comment by am11** [comment] 2015-02-27 14:54
Well, it depends on:

* the contents of `test.scss`.
* version of node-sass.

**Comment by MarkusPint** [comment] 2015-02-27 14:56
Version:
    "node-sass": "^2.0.1"

Contents of test.scss:
    $font-stack:    Helvetica, sans-serif;
    $primary-color: #333;
    
    body {
      font: 100% $font-stack;
      color: $primary-color;
    }

**Comment by MarkusPint** [comment] 2015-02-27 15:14
My Windows username is in Cyrillic, ie. it is included in the absolute path of my WebStorm workspace.
Could that be causing the issue?

**Comment by am11** [comment] 2015-02-27 15:30
Please test it like this:

```cmd
:: this is cmd
mkdir \temp && cd \temp
npm install node-sass
notepad test.scss :: paste your code and close notepad
node
:: entered the node interactive shell (REPL)
```

then copy the following and paste in cmd (Ctrl+C to copy and Alt+Space+E+P to paste):

```javascript
// using single quotes because its JS! :)

var sass = require('node-sass');

// in v2.0.1, user don't need stats

sass.render({
  file: 'test.scss',
  outFile: 'test.css',
  success: function(result) { // because 'result' here is an object as per the readme
    console.log(result.css);
    console.log(result.stats);  // stats will always be returned as part of result
    // console.log(result.map);
  },
  error: function(error) {
    console.log(error);
  }
});
```

**Comment by MarkusPint** [comment] 2015-02-27 15:49
This results in:
{ entry: 'test.scss',
  start: 1425052164090,
  includedFiles: [ 'C:/temp/test.scss' ],
  end: 1425052164093,
  duration: 3 }

**Comment by MarkusPint** [comment] 2015-02-27 17:08
Sorry, it also prints out the processed CSS:

body {
  font: 100% Helvetica, sans-serif;
  color: #333; }

Is there anything else I can do? I would really like to get it working.

**Comment by am11** [comment] 2015-02-27 19:10
> Is there anything else I can do? I would really like to get it working.

It IS working! :sunny:

**Comment by MarkusPint** [comment] 2015-02-28 00:39
But why is it not producing a CSS file? :(

**Comment by am11** [comment] 2015-02-28 01:09
Starting with v2, node-sass does not write files to disk, but returns data to user. The `outFile` option is used by LibSass to produce correct sourceMap paths. If you are not using source-map, you can omit `outFile` as well. See the release notes: https://github.com/sass/node-sass/releases/tag/v2.0.0.

Meaning:

```javascript
var fs = require('fs');

require('node-sass').render({
  file: 'path/to/my/file.scss',
  success: function(result) {
     fs.writeSync(result.css, 'my/outFile.css');
    // we don't want to do this^ for you because you may want to
    // write it in database or send as response to web service etc.
    // in which case it is bad for performance to write on disk.
  }
})
```

Note if you want source-maps as well, then you need to set `outFile` like this:


```javascript
var myOutFile = 'c:\\project\\styles\\output-styles.css',
    myMapFile = myOutFile + '.map';

require('node-sass').render({
  file: 'path/to/my/file.scss',
  outFile: myOutFile,
  sourceMap: myMapFile, // you can set it to `true` as well, see readme
  success: function(result) {
     fs.writeSync(result.css, myOutFile);
     fs.writeSync(result.map, myMapFile);
  }
})
```

**Comment by am11** [comment] 2015-02-28 07:28
Closing it as not reproducible. Feel free to ask questions on node-sass gitter channel: https://gitter.im/sass/node-sass/.

**Comment by MarkusPint** [comment] 2015-02-28 10:42
Thanks for the explanation, I got it working now :)

Just to point out:

Using file: 'C:/Users/самсунг/test.scss' fails with "Invalid UTF-8" whereas
using file: 'C:/Users/test.scss' works perfectly.

Using relative paths fails because the full path includes a  folder name written in cyrillic.

**Comment by am11** [comment] 2015-02-28 14:03
@MarkusPint, I cannot reproduce it. Here is my test:

```powershell
mkdir самсунг
cd самсунг
notepad test.scss
# type in ->    a{b:c}
# saved and closed notepad
cd ..
node

# node.js REPL

require('node-sass').render({
  file: 'самсунг/test.scss',
  success: function(result) { console.log(result) },
  error: function(error) { console.log(error) }
})

# output:

> { css: 'a {\n  b: c; }\n',
  map: '{}',
  stats:
   { entry: 'самсунг/test.scss',
     start: 1425131594461,
     includedFiles: [ 'C:/Users/Adeel/Source/Projects/Experiments/node-sass/самсунг/test.scss' ],
     end: 1425131594465,
     duration: 4 } }
```

Can you try to modify this example so I know how to reproduce the UTF-8 path issue?

**Comment by Lisaj** [comment] 2015-03-21 09:17
Hello,
trying new Visual Studio 2015, and I found the same problem.

system:
clean install windows 10 9926
Visual Studio 2015 ctp6
node-sass 2.0.1
grunt-sass 0.18.1

When a project is in the directory 'C:\Users\Ludvík\Documents\Visual Studio 2015\Projects\Test1' is an error Invalid UTF-8.
If the project move to the directory 'C:\prace\Test1' everything works.

To view the error from grunt-sass need this patch https://github.com/sindresorhus/grunt-sass/issues/194

**Comment by Lisaj** [comment] 2015-03-21 09:55
I mody repro for this error.

```ruby
mkdir Ludvík
cd Ludvík
notepad test.scss
# type in ->    a{b:c}
# saved and closed notepad
node

# node.js REPL

require('node-sass').render({
  file: 'test.scss',
  success: function(result) { console.log(result) },
  error: function(error) { console.log(error) }
})

# output:

> { status: 3, message: 'Invalid UTF-8', code: 3 }
```

**Comment by am11** [comment] 2015-03-21 16:58
@Lisaj, thanks for the bug report. 

I can confirm that this issue was present in v2.0.1 and is not reproducible with v3.0.0-alpha.x anymore.

```cmd
:: considering you have git in your PATH
npm install sass/node-sass#v3.0.0-alpha.1

node  :: REPL
```
```javascript
// notice the API change:
require('node-sass').render({
  file: 'test.scss'
}, function(err, result) {
  console.log(err, result);
  assert(!err); //  <-- true
  assert(err === undefined); //  <-- true
});
```

To use grunt-sass with node-sass v3-alpha, you can use this gist: https://gist.github.com/am11/47fc07b5d6de73697ee9..

**Comment by rudarobson** [comment] 2015-04-23 12:27
I'm using node-sass@3.0.0-beta.7
and still getting this error using the data option

sass.renderSync({ data: contents });

running windows

**Comment by xzyfer** [comment] 2015-04-23 12:41
@rudarobson what exactly are you doing to produce this issue?

Also please make a gist for output of this:
https://gist.github.com/am11/9f429c211822a9b15aee replacing `npm install node-sass` with `npm install node-sass@beta`.

**Comment by rudarobson** [comment] 2015-04-23 13:03
![node-sass](https://cloud.githubusercontent.com/assets/2481621/7297431/1b181732-e99f-11e4-9686-138f9e15bd96.png)

(console output, with a few hidden stuff,sorry :))

just running unit tests, using:

var sass = require('node-sass');
var fs = require('fs');
var contents = fs.readFileSync('......'); /*some contents read from a file*/
sass.renderSync({ data: contents });

the console outputed error at node-sass/lib/index.js at line 394

**Comment by frio** [comment] 2015-11-16 22:53
Hi, I note that this issue has been closed as Not Reproducible, but there's evidence of people having this problem if they have UTF-8 characters somewhere in their path.  Is there another bug tracking this issue?  It still appears to be ongoing.

**Comment by saper** [comment] 2015-11-17 05:05
@frio the last comment is from 7 months ago, the code has changed significantly. If you are using the newest version which is 3.4.2 now and still have an issue please report. You might want to search https://github.com/sass/libsass/issues as well.

**Comment by frio** [comment] 2015-11-17 22:06
I mentioned this ticket in the other bug (rather than the other way around, woops), but https://github.com/dlmanning/gulp-sass/issues/322 indicates people have been having this issue as recently as two days ago.

I'm not personally affected, but am tracking down another bug to do with filenames in sourcemaps and a quirk of my environment at the time led me down this (wrong) rabbit-hole.

**Comment by Atvaark** [comment] 2015-12-04 13:36
I went to the trouble of creating an example for this issue and dlmanning/gulp-sass#322.

https://github.com/Atvaark/SassUtf8 
If there are any non-ASCII characters before or in the project root directory and an @import directive is used then the problem arises.
Tested on Windows 7 using the win32-x64-47 binding.

**Comment by am11** [comment] 2015-12-04 15:20
Thanks for the steps to repro @Atvaark.

I am able to reproduce this issue. The exception being thrown from libsass.

As a temporary workaround, try replacing:
https://github.com/Atvaark/SassUtf8/blob/12a3c686957bd53f2dc375624713a19ed5f99d3a/S%C3%A1ssUtf8/index.js#L2

with:

```javascript
var absPath = require('path').resolve('src/bar').replace(/\\/g, '/');
var opts = { data : '@import \" ' + absPath + '\";', includePaths : [ 'src' ] };

// the other workaround is to keep the second line intact and use a
// `custom importer` function and return the absPath
// to override LibSass import path resolution.
```

@mgreter, the issue is when the path has non-ASCI characters, one of the import is relative and at the step where LibSass tries to resolve the absolute import path (to read the file contents). I haven't pinpointed the exact location in the code. Is there any issue tracking in libsass tracker for this? If none I will open one.

**Comment by mgreter** [comment] 2015-12-04 19:07
I'm just guessing, but do you know in what encoding node-sass passes that non ascii chars to libsass? AFAIK we expect utf8 everywhere, so if those chars are passed in latin1 would probably explain it. But great that we have a test repo for this, should be easy to verify now.

**Comment by am11** [comment] 2015-12-05 18:40
@mgreter, the non-ASCII part of path in this case seems to be coming from `cwd` which libsass gets from the OS.
This is fixed in https://github.com/sass/libsass/pull/1774.

**Comment by xzyfer** [comment] 2015-12-10 13:01
@am11's patch has been merged into LibSass. It'll be in the next LibSass release.

**Closed** 2015-12-28 10:50 UTC
Labels: Bug - Confirmed, External - LibSass
