### ISSUE TITLE
Segmentation fault on Node 8 alpine (docker)

### ISSUE THREAD

**Issue by ForsakenHarmony** [sass/node-sass#2031] opened 2017-06-27 21:22 UTC
Works with node 6 and on my host machine ( debian, node 8 )

this is my project, can also try to make a smaller testcase if required
https://github.com/ForsakenHarmony/portfolio

```
yarn build v0.24.6                                                                                                  
$ cross-env NODE_ENV=production npm run webpack                                                                     
npm info it worked if it ends with ok                                                                               
npm info using npm@5.0.3                                                                                            
npm info using node@v8.1.2                                                                                          
npm info lifecycle portfolio@0.1.0~prewebpack: portfolio@0.1.0                                                      
npm info lifecycle portfolio@0.1.0~webpack: portfolio@0.1.0                                                         
                                                                                                                    
> portfolio@0.1.0 webpack /usr/src/app                                                                              
> webpack --progress --colors --config webpack.config.js                                                            
                                                                                                                    
 12% building modules 20/21 modules 1 active ...!/usr/src/app/client/styles/main.scssSegmentation fault (core dumped
)                                                                                                                   
npm info lifecycle portfolio@0.1.0~webpack: Failed to exec webpack script                                           
npm ERR! code ELIFECYCLE                                                                                            
npm ERR! errno 139                                                                                                  
npm ERR! portfolio@0.1.0 webpack: `webpack --progress --colors --config webpack.config.js`                          
npm ERR! Exit status 139                                                                                            
npm ERR!                                                                                                            
npm ERR! Failed at the portfolio@0.1.0 webpack script.                                                              
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                  
                                                                                                                    
npm ERR! A complete log of this run can be found in:                                                                
npm ERR!     /root/.npm/_logs/2017-06-26T22_44_11_188Z-debug.log                                                    
error Command failed with exit code 139.                                                                            
Removing intermediate container 5cb53913df5e
```

- NPM version (`npm -v`):
5.0.3
- Node version (`node -v`):
v8.1.2
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0', 
  node: '8.1.2',
  v8: '5.8.283.41',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform (`node -p process.platform`):
linux
- Node architecture (`node -p process.arch`):
x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]

**Comment by nschonni** [comment] 2017-06-27 21:29
Can you add the log to a Gist? I'm not seeing anything in the current output, besides that it failed around a Sass file, that indicates this is a node-sass issue.

I'd also suggest just trying to reproduce it without webpack

**Comment by ForsakenHarmony** [comment] 2017-06-28 11:59
https://gist.github.com/ForsakenHarmony/3ddcfcab7e932a5a6a48094eda7854c7

I'm not quite sure what's going on, it only seems to happen in the docker build script, not if I run it inside the container

may also be my code, because this doesn't crash

```Dockerfile
FROM node:8-alpine

RUN mkdir -p /usr/app
WORKDIR /usr/app

RUN yarn add node-sass
ENV NODE_ENV production
RUN node -e "require('node-sass').renderSync({data: '* {height: 2px}'});"
```

**Comment by saper** [comment] 2017-06-28 19:06
It does not seem to crash. Looks like a permission problem, people usually run as root inside a container, check our troubleshooting guide for info on unsafe permissions

**Comment by ForsakenHarmony** [comment] 2017-06-28 20:06
Segmentation fault is a type of crash to me

**Comment by saper** [comment] 2017-06-28 20:20
I am sorry, didn't scroll that far right. Can you try to get the core file?

**Comment by saper** [comment] 2017-06-28 20:22
Quick question, are project files copied from Debian?

**Comment by xzyfer** [comment] 2017-06-30 01:49
You'll need to delete your `node_modules` and reinstall your modules inside the container. Copying files from (or reusing a cache) between debian and alpine is going to result in segfaults.

**Comment by ForsakenHarmony** [comment] 2017-06-30 16:15
@saper the core file?
also yes, copied from debian
`node_modules` doesn't get copied ( doesn't exist )
I get the feeling it's the build itself

**Comment by saper** [comment] 2017-06-30 21:11
probably your `binding.node` is copied/cached from Debian, this way it has to crash.

**Comment by ForsakenHarmony** [comment] 2017-06-30 21:46
it also happens in ci

**Comment by ForsakenHarmony** [comment] 2017-06-30 21:56
oops

**Comment by mikestead** [comment] 2017-07-02 05:32
Having exact same issue. Fails with `segmentation fault` after a clean build and run inside Alpine image based on this [Dockerfile](https://github.com/nodejs/docker-node/blob/12ba2e5432cd50037b6c0cf53464b5063b028227/8.1/alpine/Dockerfile) (Node 8.1)

Works fine when doing the same thing inside image from this [Dockerfile](https://github.com/nodejs/docker-node/blob/e2b78b4bde9440f2189007004a2ae4880f3eb030/6.11/alpine/Dockerfile) (Node 6.11)

**Comment by nschonni** [comment] 2017-07-03 01:02
Between 6 and 8, the node images changed from Alpine 3.4 to 3.6 so there may be some difference there. We did use their image to build our binaries though

**Comment by xzyfer** [comment] 2017-07-03 01:11
@mikestead can you run `npm rebuild node-sass --force` within the Node 8.1 container and confirm whether the segfault is still present?

Also can you supply a minimal scss code sample the produces the segfault so we can investigate further?

**Comment by frankn11** [comment] 2017-07-03 16:44
Having the same problem with node:alpine latest. 
For me it crash with the import of Susy @xzyfer 

`@import '~susy/sass/susy';`

**Comment by ForsakenHarmony** [comment] 2017-07-03 18:17
tried rebuilding in the Dockerfile, didn't change anything

**Comment by xzyfer** [comment] 2017-07-04 01:57
@ForsakenHarmony thanks. If a fresh local recompiled binary is still segfaulting I'm not sure what we can do. This could be an issue with Node 8 or Nan.

**Comment by djskinner** [comment] 2017-07-07 15:54
FWIW I'm seeing something similar but nothing to do with `node-sass`.

I've had a node application running `FROM node:8-alpine` for a while now with no problems. I've been toying with using `babel-preset-env` to transpile code in a version-aware manner. Presumably this means that more of my code is now using native ES features that are available in node 8 features rather than transpiled ES5 code.

Anyway, something has changed and the app crashes with `Segmentation Fault` when I try to log in (works fine up until this point). Switching the `Dockerfile` back to `FROM node:8` fixes the issue.

**Comment by ForsakenHarmony** [comment] 2017-07-07 17:09
https://gist.github.com/ForsakenHarmony/7efb3659dac985a90598b869b07c7e46

this is the dockerfile I tested with, project is linked in the main comment

**Comment by willdurand** [comment] 2017-07-13 15:16
I am experiencing the same problem with a switch from Node 6 to 8.1.4 (alpine-based images).

**Comment by saper** [comment] 2017-07-13 23:15
Can anyone provide a backtrace for this?

**Comment by pawelpalka81** [comment] 2017-07-18 10:17
I could not reproduce this bug on this example but on my case it happen too. This is a trace from me app
https://gist.github.com/pawelpalka81/b6899c60551f7db20376b5e330aa1702

**Comment by idmontie** [comment] 2017-07-21 20:07
Having the same problem with Node 8.0.0 and Alpine, specifically this docker image: `mhart/alpine-node:8.1.3`. node-sass version 4.5.3.  Nothing to really go off of in my logs from my CI except:

```
Segmentation fault (core dumped)
error Command failed with exit code 139.
```

This only happens on GitlabCI when using Docker in Docker. It works on my local MacOSX machine.

**Comment by saper** [comment] 2017-07-22 00:35
Hello everyone participating in this bug: I have seen similar reports addressed to different projects using node alpine docker images. There is little evidence that node-sass is at fault here currently. (Just because something breaks with node-sass is not enough, this is only one of native modules that may cause trouble).

Unless somebody comes up with a working debugger and a stack trace it will be very hard to help and we will need to close this issue. Please keep in mind that node-sass is very picky about using the same versions of libc(musl) and C++ runtime libraries, which mostly means the same C++ compiler has to be used for node-sass and for the node itself.

Maybe the maintainers of the docker image can help you better, at least with getting the debugger running.

**Comment by DianaOlympos** [comment] 2017-07-26 09:53
Not on node 8, node 7 but....

would it be possible that the difference between what the global install does compare to local in term of sass binary in use...

```/node_modules/node-sass/vendor/linux_musl-x64-51/
/node_modules/node-sass/vendor/linux-x64-51/``` ?

**Comment by ForsakenHarmony** [comment] 2017-07-26 14:15
@saper guess I should stop using sass then

**Comment by pandada8** [comment] 2017-07-31 09:03
same here

**Comment by vinaykharecha** [comment] 2017-08-01 14:17
I have Dockerfile which is using ubuntu base image and it tries to install pm2 via npm i.e. npm install -g pm2.


My build works when **docker host os is ubuntu**; but my build is failing with same error when i'm using **docker host os as alpine** even though my docker base image is ubuntu

`Segmentation fault`
`The command '/bin/sh -c npm install -g pm2' returned a non-zero code: 139`

**Comment by nschonni** [comment] 2017-08-01 17:26
Has anyone tried the recommendation of adding in the libc6 compat from the Node image repo? https://github.com/nodejs/docker-node#nodealpine

**Comment by jackbrown** [comment] 2017-08-02 04:30
@nschonni adding libc6-compat didn't work for me

**Comment by nschonni** [comment] 2017-08-02 04:31
@jackbrown thanks for trying ❤️

**Comment by enko** [comment] 2017-08-07 13:13
I managed to procure a stacktrace! I used the node7-alpine docker image. I used the following steps to reproduce:

* docker run --security-opt seccomp:unconfined --cap-add SYS_PTRACE -it node7-alpine /bin/bash
* cd /tmp
* git clone https://github.com/sass/node-sass/
* cd node-sass
* yarn
* node scripts/build.js --force --debug
* gdb node
* set args bin/node-sass node_modules/sass-spec/spec/scss/huge/input.scss
* run
* bt

I have attached a backtrace that I got:

[Stacktrace](https://github.com/sass/node-sass/files/1204901/bt.txt)

**Comment by saper** [comment] 2017-08-07 15:44
This is great @enko. I think the root cause of the problem is http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Thread_stack_size 

If that is confirmed, there is not much we can do about it.

**Comment by jubel-han** [comment] 2017-08-27 07:38
Here is [my workaround](https://github.com/jubel-han/dockerfiles/blob/master/node/Dockerfile) for this issue.

**Comment by saper** [comment] 2017-08-27 07:52
If the stackfix is doing what I think it is doing, is that a confirmation that we have a stack problem? Of course, it is possible that the newer libsass or the newer node need more stack for some reason, but until that does not loop forever it is not a bug.

That would mean closing this bug and declaring musl docker images unusable for node-sass.

**Comment by johnwebbcole** [comment] 2017-09-01 17:08
@jubel-han Thanks!  Your workaround worked for me

**Comment by codeofsumit** [comment] 2017-09-06 12:07
having the same issue.
Found this in my research as well: https://github.com/sass/node-sass/issues/1589

**Comment by carlodicelico** [comment] 2018-01-24 18:59
I experienced this issue, as well. I think https://github.com/sass/node-sass/issues/2169 is also related. My fix was to change the build stage's image to one based on alpine 3.7, which brings with it node 8. I also build force an npm rebuild of node-sass in that image. This resolves the issue for me.

**Comment by jwalton** [comment] 2018-02-01 21:45
Related? https://github.com/libuv/libuv/issues/1507

**Comment by saper** [comment] 2018-02-01 21:48
@jwalton it is exactly this problem

**Comment by jwalton** [comment] 2018-02-01 21:51
This was merged in August.  I wonder when and where it landed?

**Comment by cw789** [comment] 2018-02-09 09:10
Different kind of fix could possibly be the following addition in your Dockerfiles.
Fix: https://github.com/nodejs/docker-node/issues/588

I had the same issue not using Sass.
It only occurs if the docker host itself has a hardened linux kernel (alpine in my case).

**Comment by saper** [comment] 2018-02-27 00:24
This has been worked around by increasing thread stack size in the libuv libary (https://github.com/libuv/libuv/issues/1507) and became available in node 8. 

Therefore using anything older than node 8 with alpine is discouraged.

**Comment by paulmaraireland** [comment] 2018-03-18 01:10
In a nightcourse, we were asked to setup a node http server in docker. 

I looked up what was good for docker and found it was alpine linux so I installed that in a VM. 
Then  I installed docker in that and then I followed a few basic tutorials to try and get node going.
None worked and I kept getting the error code 139.

Example 1:
Segmentation fault
The command '/bin/sh -c npm install' returned a non-zero code: 139

Example 2:
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS
107a1b769d33        webapp              "node index.js"     9 seconds ago       Exited (139)

I searched for a very long time and eventually I found this thread and saw the reply from @jubel-han which helped. It did not explain what I should do but I pieced it together from looking at the solution and how some others patched their systems.

The fix is for me to add this to my Dockerfile before npm gets called:
RUN apt-get update -y && apt-get dist-upgrade -y && \
apt-get install -y --no-install-recommends paxctl && \
paxctl -mC `which node`

It also works if I add it just after:
FROM node:carbon

If this comment seems long and includes a lot of technical lines, it is meant to. If anyone else ends up googling the errors like I did, I hope this helps.

**Comment by xzyfer** [comment] 2018-03-24 04:01
Can anyone confirm whether this is still an issue with 4.8.3?

**Comment by xakep139** [comment] 2018-03-27 08:00
@xzyfer I confirm, 4.8.3 cause `Segmentation fault (core dumped)`

**Comment by happysalada** [comment] 2018-11-19 09:44
I still have this issue on 4.10, with node:11.1-alpine

**Comment by happysalada** [comment] 2018-11-20 02:05
I get it too on node:11.2-alpine and node:11.2-slim
if anybody else runs into this, I solved it by using the full image
`node:11.2`

**Comment by happysalada** [comment] 2018-11-20 05:07
using `node:10.13-alpine` seems to solve the problem

**Comment by testica** [comment] 2019-05-18 13:33
I was facing the same problem serving an express server. For some reason `-alpine` version throw segmentation fault.

Using just `node:8` solved my problem

**Comment by kozr** [comment] 2019-09-27 21:53
Using `node:10.16.3` gave me seg fault, and changing it to `node:8` or `node:latest` as of 2019 Sept 27th worked for me.

**Closed** 2019-10-18 05:02 UTC
Labels: External - Node, Invalid - Unsupported Platform, Node 8, OS - Alpine Linux

**Comment by superern** [comment] 2020-02-10 07:50
> using `node:10.13-alpine` seems to solve the problem

This resolves our problem.
