### ISSUE TITLE
Failed at the node-sass

### ISSUE THREAD

**Issue by Atlant000000** [sass/node-sass#1389] opened 2016-02-18 00:14 UTC
I used `npm rebuild`, but it's not working.  What's the problem?

> 4933 error Windows_NT 5.1.2600
> 4934 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
> 4935 error node v5.6.0
> 4936 error npm  v3.6.0
> 4937 error code ELIFECYCLE
> 4938 error node-sass@3.4.2 postinstall: `node scripts/build.js`
> 4938 error Exit status 3221225477
> 4939 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
> 4939 error Make sure you have the latest version of node.js and npm installed.
> 4939 error If you do, this is most likely a problem with the node-sass package,
> 4939 error not with npm itself.
> 4939 error Tell the author that this fails on your system:
> 4939 error     node scripts/build.js
> 4939 error You can get information on how to open an issue for this project with:
> 4939 error     npm bugs node-sass
> 4939 error Or if that isn't available, you can get their info via:
> 4939 error     npm owner ls node-sass
> 4939 error There is likely additional logging output above.
> 4940 verbose exit [ 1, true ]

Thanks a lot.

**Comment by xzyfer** [comment] 2016-02-18 01:11
>4938 error Exit status 3221225477

Duplicate of https://github.com/sass/node-sass/issues/1283

**Closed by xzyfer** 2016-02-18 01:11 UTC
