### ISSUE TITLE
Exit status 3221225477 returned from node scripts/build.js / Windows XP

### ISSUE THREAD

**Issue by vzdeadler** [sass/node-sass#1326] opened 2016-01-04 10:40 UTC
When i run **npm install node-sass** i get this error

` npm ERR! Windows_NT 5.1.2600 `
 `npm ERR! argv "C:\\Archivos de programa\\nodejs\\node.exe" "C:\\Archivos de prog `
` rama\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "node-sass" `

 ` npm ERR! node v4.2.4 `
 ` npm ERR! npm  v2.14.12`
 `npm ERR! code ELIFECYCLE`

 `npm ERR! node-sass@3.4.2 postinstall: node scripts/build.js`
 `npm ERR! Exit status 3221225477`
 `npm ERR!`
 `npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js`

 `npm ERR! This is most likely a problem with the node-sass package,`
 `npm ERR! not with npm itself.`
 `npm ERR! Tell the author that this fails on your system:`
 `npm ERR!     node scripts/build.js`
 `npm ERR! You can get their info via:`
 `npm ERR!     npm owner ls node-sass`
 `npm ERR! There is likely additional logging output above.`

 `npm ERR! Please include the following file with any support request: `

> npm -v
> 2.14.12

> node -v
> v4.2.4

> node -p process.versions
> { http_parser: '2.5.0',
>  node: '4.2.4',
>  v8: '4.5.103.35',
>  uv: '1.7.5',
>  zlib: '1.2.8',
>  ares: '1.10.1-DEV',
>  icu: '56.1',
>  modules: '46',
>  openssl: '1.0.2e' }

> node -p process.platform
> win32

> node -p process.arch
> ia32

My OS: Windows XP 32 Bits

**Comment by saper** [comment] 2016-01-04 14:32
Looks like another instance of https://github.com/sass/node-sass/issues/1283 to me.

**Comment by saper** [comment] 2016-01-04 14:44
Filed https://github.com/npm/npm/issues/11024 with the npm project.

**Comment by vzdeadler** [comment] 2016-01-04 22:45
I tried cmd /d /s /c and nothing, still the same error, or maybe im doing it wrong?
im running cmd /d /s /c node, and i get the node prompt, i tried cmd /d /s /c npm install --save node-sass, i dont know if i'm doing it correctly?

Btw, sry i am a novice in this.

**Comment by asaarnak** [comment] 2016-01-05 10:26
Similar problem on Ubuntu 14.04.1 when running: npm install node-sass
```
16731 verbose stack Error: node-sass@3.4.2 install: `node scripts/install.js`
16731 verbose stack spawn ENOENT
16731 verbose stack     at ChildProcess.<anonymous> (/home/user/app/node_modules/npm/lib/utils/spawn.js:17:16)
16731 verbose stack     at emitTwo (events.js:87:13)
16731 verbose stack     at ChildProcess.emit (events.js:172:7)
16731 verbose stack     at maybeClose (internal/child_process.js:818:16)
16731 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
16732 verbose pkgid node-sass@3.4.2
16733 verbose cwd /home/user/app
16734 error Linux 4.1.5-x86_64-linode61
16735 error argv "/home/user/app/nodejs/node-v5.3.0-linux-x64/bin/node" "/home/user/app/node_modules/.bin/npm" "install" "node-sass"
16736 error node v5.3.0
16737 error npm  v3.5.2
16738 error file sh
16739 error code ELIFECYCLE
16740 error errno ENOENT
16741 error syscall spawn
16742 error node-sass@3.4.2 install: `node scripts/install.js`
16742 error spawn ENOENT
16743 error Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
16743 error Make sure you have the latest version of node.js and npm installed.
16743 error If you do, this is most likely a problem with the node-sass package,
16743 error not with npm itself.
```

**Comment by xzyfer** [comment] 2016-01-05 12:23
@asaarnak your issue is not related. Please open a separate issue after following the [troubleshooting guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) and capturing **all** of the output in a **GitHub gist**.

**Comment by xzyfer** [comment] 2016-01-05 12:23
@saper happy to close this as a duplicate?

**Comment by saper** [comment] 2016-01-05 15:36
Not sure yet. I'd rather keep both open in a hope that posters give us some more information.

@vzdeadler do you have some antivirus running? are you running as the normal user or are is your account a system administrator?

**Comment by vzdeadler** [comment] 2016-01-06 00:00
I use Avast, but i always turn it off when i do npm installs, my account is system administrator

**Comment by saper** [comment] 2016-01-06 20:08
So this must be a duplicate of #1283, please continue discussion there.

**Closed by saper** 2016-01-06 20:08 UTC
Labels: Bug - Maybe, External - NPM, Invalid - Duplicate, NPM - Install, OS - Windows

**Comment by largomike1** [comment] 2018-04-10 18:35
We had the same errors when attempting run any script using "npm run-script xxxxx".  I eventually discovered that it was due to the GIT install on Windows.  I uninstalled the current version and reinstalled the latest version and the errors went away.

**Comment by tiandashu** [comment] 2018-07-03 05:30
我好像找到了这个问题产生的原因，当我这样写的时候会产生这个错误。
.submitInput /deep/{
        @include wh(2.4rem,0.51rem);
        @include font(0.18rem,0.46rem);
        background: url("./img/worldCup04.png") no-repeat;
        background-size: auto 100%;
        border: none;
        color: #fff;
        margin: 0.31rem auto;
    }
    input:disabled{
        @extend .submitInput;  //注意这里
        background: url("./img/worldCup044.png") no-repeat;
        background-size: auto 100%;
        disabled:disabled;
        opacity: 1;
    }

如果我把@extend .submitInput;  去掉这个问题就会解决
