### ISSUE TITLE
Missing binary 4.11.0

### ISSUE THREAD

**Issue by MalteOschlies** [sass/node-sass#2643] opened 2019-04-26 07:28 UTC
Our pipeline fails with
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node": 

Yesterday it stil worked with x64-67, was there an update today?

**Comment by skjnldsv** [comment] 2019-04-26 07:29
Same here

**Comment by nschonni** [comment] 2019-04-26 07:34
Duplicate of #2632

**Closed by nschonni** 2019-04-26 07:34 UTC
