### ISSUE TITLE
node版本为16.4.0 node-sasss为6.0.1，无法支持4.0.0

### ISSUE THREAD

**Issue by yingkongyi** [sass/node-sass#3138] opened 2021-06-30 01:27 UTC
ERROR  Failed to compile with 1 error                                                                                                                        9:19:35 AM

 error  in ./src/assets/style/custom-p.scss

Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.

 @ ./src/main.js 136:0-38
 @ multi babel-polyfill ./src/main.js

**Comment by nschonni** [comment] 2021-06-30 02:08
Probably a duplicate of #3103

**Closed by nschonni** 2021-06-30 02:08 UTC
