### ISSUE TITLE
Color keywords are replaced when prefixed with `--`

### ISSUE THREAD

**Issue by seamusleahy** [sass/node-sass#1677] opened 2016-08-24 07:46 UTC
When a color keyword is prefixed with `--`, the value is replaced with the hex value. Other uses of the keyword are not replaces with the hex value.

Input: `body{background: magenta; color: var(--magenta); border-color: var(--color-magenta);}`

Output: `body{background:magenta;color:var(--#ff00ff);border-color:var(--color-magenta)}`

**Comment by nschonni** [comment] 2016-09-01 03:02
Although the title may be different this is a dupe of #1624. You can track the issue/upstream issue there.

**Closed by nschonni** 2016-09-01 03:02 UTC

**Comment by xzyfer** [comment] 2016-09-01 03:58
This issue elaborates on the issue with colour names further: https://github.com/sass/sass/issues/2128#issuecomment-243897569

You should never use a colour name unquoted in Sass. However Sass 3.5 will have better support for custom properties (`--red`) http://blog.sass-lang.com/posts/809572-sass-35-release-candidate. This feature has not landed yet in node-sass.
