### ISSUE TITLE
3.0.x branch broken in OS X

### ISSUE THREAD

**Issue by CaseyLeask** [sass/node-sass#819] opened 2015-03-30 04:17 UTC
Hi Team,

I'm getting this error on two different OS X machines.

```
node-sass(master) $ git co 19b5e3c5cc4831da153e24dee96c983d03799e2f
Note: checking out '19b5e3c5cc4831da153e24dee96c983d03799e2f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 19b5e3c... Build: Uses v8 version instead of runtime name. The new binary path format is: `<platform>-<arch>-<v8 version>/binding.node`

node-sass(tags/v3.0.0-pre~25^2) $ npm cache clean && rm -rf node_modules && npm install && npm test

> node-sass@2.0.1 install /Users/casey.leask/src/community/node-sass
> node scripts/install.js


> node-sass@2.0.1 postinstall /Users/casey.leask/src/community/node-sass
> node scripts/build.js

Building: /opt/boxen/nodenv/versions/v0.10.29/bin/node node_modules/pangyp/bin/node-gyp rebuild
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:4:10: fatal error: 'libsass/sass_context.h' file not found
#include "libsass/sass_context.h"
         ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/casey.leask/src/community/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/opt/boxen/nodenv/versions/v0.10.29/bin/node" "/Users/casey.leask/src/community/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/casey.leask/src/community/node-sass
gyp ERR! node -v v0.10.29
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
Build failed
```

I'm getting this regression on all commits from https://github.com/sass/node-sass/commit/19b5e3c5cc4831da153e24dee96c983d03799e2f onwards.

```
node-sass(tags/v3.0.0-pre~25^2) $ git co HEAD~1
Previous HEAD position was 19b5e3c... Build: Uses v8 version instead of runtime name. The new binary path format is: `<platform>-<arch>-<v8 version>/binding.node`
HEAD is now at 8c3bd77... Merge pull request #686 from Jakobo/test_options2

node-sass(tags/v3.0.0-pre~26) $ npm cache clean && rm -rf node_modules && npm install && npm test

> node-sass@2.0.1 install /Users/casey.leask/src/community/node-sass
> node scripts/install.js


> node-sass@2.0.1 postinstall /Users/casey.leask/src/community/node-sass
> node scripts/build.js

`darwin-x64-node-0.10` exists; testing
Binary is fine; exiting
object-assign@2.0.0 node_modules/object-assign

get-stdin@4.0.1 node_modules/get-stdin

mocha-lcov-reporter@0.0.1 node_modules/mocha-lcov-reporter

replace-ext@0.0.1 node_modules/replace-ext

nan@1.7.0 node_modules/nan

semver@4.3.3 node_modules/semver

shelljs@0.3.0 node_modules/shelljs

cross-spawn@0.2.8 node_modules/cross-spawn
└── lru-cache@2.5.0

mkdirp@0.5.0 node_modules/mkdirp
└── minimist@0.0.8

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

npmconf@2.1.1 node_modules/npmconf
├── uid-number@0.0.5
├── inherits@2.0.1
├── osenv@0.1.0
├── ini@1.3.3
├── once@1.3.1 (wrappy@1.0.1)
├── nopt@3.0.1 (abbrev@1.0.5)
└── config-chain@1.1.8 (proto-list@1.2.3)

meow@3.1.0 node_modules/meow
├── minimist@1.1.1
├── camelcase-keys@1.0.0 (camelcase@1.0.2, map-obj@1.0.0)
└── indent-string@1.2.1 (repeating@1.1.2)

gaze@0.5.1 node_modules/gaze
└── globule@0.1.0 (lodash@1.0.1, glob@3.1.21, minimatch@0.2.14)

mocha@2.2.1 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── debug@2.0.0 (ms@0.6.2)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

pangyp@2.1.0 node_modules/pangyp
├── which@1.0.9
├── osenv@0.1.0
├── rimraf@2.2.8
├── graceful-fs@3.0.6
├── semver@4.2.2
├── fstream@1.0.4 (inherits@2.0.1)
├── nopt@3.0.1 (abbrev@1.0.5)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.7)
├── npmlog@1.0.0 (ansi@0.3.0, gauge@1.0.2, are-we-there-yet@1.0.3)
├── request@2.51.0 (caseless@0.8.0, oauth-sign@0.5.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, tunnel-agent@0.4.0, qs@2.3.3, node-uuid@1.4.3, combined-stream@0.0.7, mime-types@1.0.2, form-data@0.2.0, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1, bl@0.9.4)
└── minimatch@2.0.4 (brace-expansion@1.1.0)

coveralls@2.11.2 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.3.0, tunnel-agent@0.4.0, qs@1.0.2, node-uuid@1.4.3, mime-types@1.0.2, tough-cookie@0.12.1, form-data@0.1.4, http-signature@0.10.1, hawk@1.1.1)
└── js-yaml@3.0.1 (esprima@1.0.4, argparse@0.1.16)

sass-graph@1.2.0 node_modules/sass-graph
├── lodash@2.4.1
├── commander@2.7.1 (graceful-readlink@1.0.1)
└── glob@4.5.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)

jscoverage@0.5.9 node_modules/jscoverage
├── xfs@0.1.8
├── ejs@1.0.0
├── coffee-script@1.9.1
├── debug@1.0.3 (ms@0.6.2)
├── optimist@0.3.1 (wordwrap@0.0.2)
└── uglify-js@2.4.15 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)

request@2.54.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.2
├── node-uuid@1.4.3
├── qs@2.4.1
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── mime-types@2.0.10 (mime-db@1.8.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── form-data@0.2.0 (async@0.9.0)
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.6.1, hoek@2.12.0)
├── bl@0.9.4 (readable-stream@1.0.33)
└── har-validator@1.5.1 (commander@2.7.1, bluebird@2.9.21, chalk@1.0.0, is-my-json-valid@2.10.0)

jshint@2.6.3 node_modules/jshint
├── strip-json-comments@1.0.2
├── underscore@1.6.0
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@1.0.0 (sigmund@1.0.0, lru-cache@2.5.0)
├── cli@0.6.6 (glob@3.2.11)
└── htmlparser2@3.8.2 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)

> node-sass@2.0.1 pretest /Users/casey.leask/src/community/node-sass
> jshint bin lib test


> node-sass@2.0.1 test /Users/casey.leask/src/community/node-sass
> mocha test

\

  api
    .render(options)
      ✓ should compile sass to css with file
      ✓ should compile sass to css with outFile set to absolute url
      ✓ should compile sass to css with outFile set to relative url
      ✓ should compile sass to css with outFile and sourceMap set to relative url
      ✓ should compile sass to css with data
      ✓ should compile sass to css using indented syntax
      ✓ should throw error status 1 for bad input
      ✓ should compile with include paths
      ✓ should compile with image path
      ✓ should throw error with non-string image path
      ✓ should render with --precision option
...
```

There's features in libsass 3.2 that I'd really love to use, but for now, I'm writing [manual workarounds](https://github.com/CaseyLeask/javascript-without-javascript/commit/acd0d10e272ffdcdc571a40a7de5d72072556f2a).

Cheers,
Casey

**Comment by am11** [comment] 2015-03-30 04:48
Hi, 

The current stable is v2.1.1, while current beta is beta.4. The existing master is few commits ahead of beta.4.

Having said that, can you please recap briefly what is going wrong and what you want us to fix here?

**Comment by xzyfer** [comment] 2015-03-30 05:12
@am11 it appears compilation is failing. I'd say it's partially due to missing osx binaries (doing this now).

**Comment by am11** [comment] 2015-03-30 05:14
Oh nice! Welcome back! :sunglasses:

**Comment by CaseyLeask** [comment] 2015-03-30 05:22
@am11 When any 3.0.x is used in `gulp-sass`, it hangs the entire process with no feedback.

**Comment by xzyfer** [comment] 2015-03-30 05:22
I can't reproduce the compilation error on the recent beta, it may be due to versions being out of sync in the pre release.

**Comment by xzyfer** [comment] 2015-03-30 05:26
@am11 I've updated the 3.0.0-beta.4 release with the OSX binaries and opened the PR in node-sass-binaries https://github.com/sass/node-sass-binaries/pull/51

**Comment by am11** [comment] 2015-03-30 05:27
:+1: 

@CaseyLeask, can you try installing `npm install node-sass@beta` now? I think `gulp-sass` needs an upgrade. We introduced bunch of breaking changes in API usage.

**Comment by am11** [comment] 2015-03-30 06:10
@CaseyLeask, for reference see the diff for grunt-sass: https://github.com/sindresorhus/grunt-sass/commit/c14beebc304816fc9b5973f0bd0a47a19556f52d. 

gulp-sass probably needs this kind upgrade.

At this point, since the original install issue seems to be fixed, I am closing it. Please open the gulp-sass issue in the respective repo.

**Closed by am11** 2015-03-30 06:10 UTC
Labels: Build, OSX
