### ISSUE TITLE
Can't install node-sass on High Sierra MacOs 10.13

### ISSUE THREAD

**Issue by deluigiluca** [sass/node-sass#2109] opened 2017-10-05 08:53 UTC
Dear All,

can anyone please help me with this issue?

Here my infos:

- NPM version (`2.5.1`)
- Node version (`v0.12.0`)
- Node Process (`{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }`)
- Node Platform (`darwin`)
- Node architecture (`x64`)
- node-sass version (`module.js:338
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)`)
- npm node-sass versions (`npm ERR! code 1`)

When `npm install node-sass`
it says:

> npm ERR! Darwin 17.0.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-sass"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
> npm ERR! This is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/install.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.

Before opening an issue:
- Read the common workarounds in the [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md)
- [Search for duplicate or closed issues](https://github.com/sass/node-sass/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](http://sassmeister.com/) that it runs with both Ruby Sass and LibSass
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/sass/node-sass/blob/master/.github/CONTRIBUTING.md)

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

When encountering a syntax, or compilation issue:

- [Open an issue on `LibSass`](https://github.com/sass/LibSass/issues/new). You
may link it back here, but any change will be required there, not here

*If you delete this text without following it, your issue will be closed.*

**Comment by nschonni** [comment] 2017-10-05 20:38
Likely a duplicate of #2100, but can you provide the installation log in a gist please

**Comment by deluigiluca** [comment] 2017-10-06 12:57
[npm-debug.log](https://github.com/sass/node-sass/files/1362727/npm-debug.log)

**Comment by KishoreBarik** [comment] 2017-10-09 12:39
Having same issue, but reason is issue with node-gyp which is not able to access specific folder and node-sass installation goes into an infinite loop. I keep getting following log repeatedly until I force stop the process.

`gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.6.0' ]
gyp verb install input version string "8.6.0"
gyp verb install installing version: 8.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.6.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.6.0' ]
gyp verb install input version string "8.6.0"
gyp verb install installing version: 8.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.6.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.6.0' ]
gyp verb install input version string "8.6.0"
gyp verb install installing version: 8.6.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.6.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp/8.6.0"
`

**Comment by deluigiluca** [comment] 2017-10-09 12:48
Now `npm install node-sass` seems fine ... 
I don't remember what I did (too many try).
But maybe it start to work once I disable the SIP (from terminal `csrutil disable` in "recovery mode") ?

**Comment by nschonni** [comment] 2017-10-31 12:57
> Unable to save binary /Users/kb/Dropbox/Local Sites/giantthoughts/app/public/wp-content/pre/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/kb/Dropbox/Local Sites/giantthoughts/app/public/wp-content/pre/node_modules/node-sass/vendor'

@kbooshco you have some sort of permission issue, not related to this issue.

Closing since the OPs resolved their issus

**Closed by nschonni** 2017-10-31 12:57 UTC
Labels: Awaiting Response, Node 0.12, OS - OSX

**Comment by ferdiardiansa91** [comment] 2018-03-12 10:23
the peoples above me didn't fix the issue clearly :(

**Comment by xzyfer** [comment] 2018-03-12 10:25
Then please a new issue following the issue template. Installation issues are almost always environment specific. Jumping into someone else issue is not going to help you resolve your own.
