### ISSUE TITLE
@at-root generate wrong code with nested mixins

### ISSUE THREAD

**Issue by singggum3b** [sass/node-sass#1597] opened 2016-06-17 11:15 UTC
```
@mixin spinner-item($var) {
    .SpinnerItem {
        $bg-color: #7f7f7f; //Local scope variable
        background-color: $bg-color;
    }
}

@mixin hello($var) {
        @include spinner-item($var);
}

.module {
   @at-root {
      @include hello($spinner);
   }
}
```

output : 
```
.module .SpinnerItem {
.....
}
```

where i expected SpinnerItem to be at root.
Ruby sass seem to generate correct code.

**Comment by xzyfer** [comment] 2016-06-17 13:02
This is a duplicate of https://github.com/sass/libsass/issues/2006. Please subscribe to that issue for updates.

**Closed by xzyfer** 2016-06-17 13:02 UTC
