### ISSUE TITLE
Error when installing on Node 15

### ISSUE THREAD

**Issue by herbievine** [sass/node-sass#3014] opened 2020-10-28 17:14 UTC
- NPM version (`npm -v`): **7.0.3**
- Node version (`node -v`): **15.0.0**
- Node Process (`node -p process.versions`): 
```
{
  node: '15.0.0',
  v8: '8.6.395.16-node.15',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): **win32**
- Node architecture (`node -p process.arch`): **x64**
- node-sass version (`node -p "require('node-sass').info"`): Tried `npm i node-sass` and `npm i node-sass@4.14.1`
- npm node-sass versions (`npm ls node-sass`):
```
-- node-sass@4.14.1 extraneous

npm ERR! code ELSPROBLEMS
npm ERR! extraneous: node-sass@4.14.1 Y:\Projects\.WebStorm\test\node_modules\node-sass

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vineh\AppData\Local\npm-cache\_logs\2020-10-28T17_12_10_420Z-debug.log
```

So I have a Vue 3 project and just updated my Node to v15 and NPM to v7. Whenever I start up my app, I get a compilation error as followed (I get this error for every Vue file with SCSS in it):
```
 error  in ./src/App.vue?vue&type=style&index=0&lang=scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (Y:\Projects\.WebStorm\swooosh-client\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (Y:\Projects\.WebStorm\swooosh-client\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at getDefaultSassImplementation (Y:\Projects\.WebStorm\swooosh-client\node_modules\sass-loader\dist\getDefaultSassImplementation.js:24:10)
    at getSassImplementation (Y:\Projects\.WebStorm\swooosh-client\node_modules\sass-loader\dist\getSassImplementation.js:19:72)
    at Object.loader (Y:\Projects\.WebStorm\swooosh-client\node_modules\sass-loader\dist\index.js:40:61)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader-v16/dist/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=style&index=0&lang=scss 4:14-407 14:3-18:5 15:22-415
 @ ./src/App.vue?vue&type=style&index=0&lang=scss
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by nschonni** [comment] 2020-10-28 17:16
Duplicate of #2965

**Closed by nschonni** 2020-10-28 17:16 UTC
