### ISSUE TITLE
Node-Gyp is an outdated version

### ISSUE THREAD

**Issue by jkim7** [sass/node-sass#2752] opened 2019-10-15 19:20 UTC
Hi, sorry for the second issue, but I identified what module needs to be updated to remove the file cb-never-called-1.0.1.tgz which throws a malware warning.

Looks like node-gyp needs to be upgraded, it is using 3.8.0 which is outdated.

**Comment by nschonni** [comment] 2019-10-15 19:24
Also a duplicate of #2716 and a bunch of other isssues

**Closed by nschonni** 2019-10-15 19:24 UTC

**Comment by frennkie** [comment] 2020-01-09 03:17
@nschonni what sense does it make close this issue with a reference to another closed issue when the problem clearly still exists and there is no solution or workaround?

@xzyfer is there any indication when a v5 release  (upgrading to a newer node-gyp) can be expected?

Thanks!
