### ISSUE TITLE
Exit status 3221225725 since node-sass > 4.1.1

### ISSUE THREAD

**Issue by mriehema** [sass/node-sass#1863] opened 2017-01-18 14:24 UTC
We're using node-sass via grunt-sass. Since node-sass got updated to 4.3 it fails on **Windows** (no problems with OSX and linux). *With 4.1.1 we didn't have these problems.*

- NPM version (`npm -v`): 
`3.10.8`
- Node version (`node -v`): 
`6.9.1`
- Node Process (`node -p process.versions`):
```
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```
- Node Platform (`node -p process.platform`):
`win32`
- Node architecture (`node -p process.arch`):
`x64`
- node-sass version (`node -p "require('node-sass').info"`):
```
node-sass       4.3.0   (Wrapper)       [JavaScript]
libsass         3.4.3   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`):
```
`-- @coremedia/grunt-utils@1.0.0
  `-- grunt-sass@2.0.0
    `-- node-sass@4.3.0
```

Error message running sass via grunt via npm script:

```
...
Running "sass:build" (sass) task

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "production"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @coremedia/perfectchef-theme@1.0.0 production: `grunt production`
npm ERR! Exit status 3221225725
...
```

Running `grunt sass` exits without any exit code or error message.

Our workaround is to go back to grunt-sass 1.2.1 with node-sass 3.13.1

**Comment by nschonni** [comment] 2017-01-19 02:06
Can you reproduce this without running through grunt?

**Comment by xzyfer** [comment] 2017-01-19 02:22
Duplicate #1861. We're experience issues with grunt-sass atm.

**Comment by xzyfer** [comment] 2017-01-27 02:30
This could also be a duplicate of #1854. Needs to confirm once 4.4.0 is stable.

**Comment by mriehema** [comment] 2017-03-15 16:10
FYI: just updated to grunt-sass 2.0.0 with a clean workspace. So I got node-sass@4.5.0. but still the same exit code. :(

```
Running "sass:build" (sass) task

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "production"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @foo-theme@1.0.0 production: `grunt production`
npm ERR! Exit status 3221225725
```

**Comment by mriehema** [comment] 2017-03-31 08:53
Any news on `Exit status 3221225725`?

**Comment by mriehema** [comment] 2017-05-03 14:02
Still broken, so I checked my sass files and found the some code causing this issue. 

It's working in Codepen, see https://codepen.io/anon/pen/YVxwdG
But not with node-sass.  Running the example scss from codepen with `node-sass test.scss` will exit without any output. :(

**Comment by xzyfer** [comment] 2017-05-03 14:47
Noone has been able to reproduce `Exit status 3221225725`. As for your codepen I see the same output as Ruby Sass when testing with https://www.sassmeister.com/

**Comment by mriehema** [comment] 2017-05-03 16:09
Can you run the code  (which work in codepen and sassmeister) with node-sass as I described? I can't. Runnning node-sass directly will exit without any information. Running node-sass via npm script will cause this exit code.

See my example project: https://github.com/mriehema/node-sass-issue

**Comment by xzyfer** [comment] 2017-05-03 16:50
Sessmeister is running node-sass when you select LibSass from the drop
down. I also confirmed it running LibSass directly. Are you using the
latest node-sass?

**Comment by mriehema** [comment] 2017-05-04 09:24
Hi @xzyfer, I'm sorry to bother you, but did you check my example project? _Please try to reproduce it._
I asked my colleagues to test it and all Windows user got the same error code (it doesn't matter, which node version they used.) but it works with macOS. *This error occurs since 4.2.0. v4.1.1 was fine.* I added a branch for that too: https://github.com/mriehema/node-sass-issue/tree/old-node-sass-version

**Comment by saper** [comment] 2017-05-07 09:44
When did we change versions of Visual Studio from 2013 to 2015?

**Comment by mriehema** [comment] 2017-05-08 15:12
I testet it with 7.10.0, 6.9.5, 6.10.3 and 4.8.3. Same result. 

I played with my example code again and it looks like it depends on the length of the `$svg`. If I shorten the string or remove one of the calls `str-replace` in the loop, it works. `str-replace`  uses `str-slice`, which was changed in libsass 3.4.1, see https://github.com/sass/libsass/issues/2240

**Comment by saper** [comment] 2017-05-08 21:34
Well, this might be #1289 str-replace is a stack-eating monster. Maybe running this in the debugger may reveal a huge stack that is full?

**Comment by mriehema** [comment] 2017-05-09 13:53
Sorry, I'm not familiar with C++ Debugger. Could you tell me, what to do and I will give you all results you need.

**Comment by saper** [comment] 2017-05-09 15:06
Do you have Visual Studio installed? Do you have `ntsd`, `cdb` and `WinDbg` debuggers installed? They can be installed independently of Visual Studio as a [Debugging Tools for Windows (WinDbg, KD, CDB, NTSD)](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063%28v=vs.85%29.aspx)

**Comment by xzyfer** [comment] 2018-03-10 10:31
This is probably fixed in 4.8.0

**Closed by xzyfer** 2018-03-10 10:31 UTC
Labels: External - LibSass, Node 6, OS - Windows

**Comment by vedi** [comment] 2018-06-15 14:48
expreiencing the same in 4.8.0 and 4.9.0

**Comment by xzyfer** [comment] 2018-06-15 14:53
@vedi this comment is not useful without a reproducible test case

**Comment by vedi** [comment] 2018-06-15 15:06
sorry, did not put it, because it looks similar with the initial one:

Win10 x64
node@8.11.3
node-sass@4.9.0

If I have long inlined svg node-sass just silently stops. If I use it through babel I get 
`Command failed with exit code 3221225725.`
