### ISSUE TITLE
npm ERR! `darwin-x64-node-0.12`

### ISSUE THREAD

**Issue by monolithed** [sass/node-sass#738] opened 2015-03-06 14:55 UTC
```
➜ npm install node-sass

> node-sass@1.2.3 install node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at 
node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@2.0.1 install node_modules/node-sass
> node scripts/install.js


> node-sass@1.2.3 postinstall node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

> node-sass@2.0.1 postinstall node_modules/node-sass
> node scripts/build.js

`darwin-x64-node-0.12` exists; testing
Binary is fine; exiting
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by am11** [comment] 2015-03-06 16:01
This is duplicate of https://github.com/sass/node-sass/issues/693.

Please go through the conversation there and find out if any given solution works for you and post your gist there.

**Closed by am11** 2015-03-06 16:01 UTC
Labels: Duplicate
