### ISSUE TITLE
node-sass error on npm install

### ISSUE THREAD

**Issue by singhizm** [sass/node-sass#2145] opened 2017-11-08 03:15 UTC
E:\xampp\htdocs\kngtravels>npm install

> node-sass@4.5.3 install E:\xampp\htdocs\kngtravels\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5
.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win3
2-x64-59_binding.node":

tunneling socket could not be established, statusCode=405

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall E:\xampp\htdocs\kngtravels\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\xampp\htdocs\kngtravels\node_modul
es\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= -
-libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\xampp\\htdocs\\kngtravels\\node_modules\\node-gyp\\bin\\node
-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\xampp\htdocs\kngtravels\node
_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:68:19)
gyp verb `which` failed     at E (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:80:29)
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\which\whi
ch.js:89:16
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\ind
ex.js:42:5
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\win
dows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\xampp\htdocs\kngtravels\node
_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:68:19)
gyp verb `which` failed     at E (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:80:29)
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\which\whi
ch.js:89:16
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\ind
ex.js:42:5
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\win
dows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE
rror (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:13:12)\n    a
t F (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:68:19)\n    at
 E (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:80:29)\n    at
E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:89:16\n    at E:\\x
ampp\\htdocs\\kngtravels\\node_modules\\isexe\\index.js:42:5\n    at E:\\xampp\\
htdocs\\kngtravels\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncom
plete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\xampp\htdocs\kngtravels\node
_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:68:19)
gyp verb `which` failed     at E (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:80:29)
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\which\whi
ch.js:89:16
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\ind
ex.js:42:5
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\win
dows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\xampp\htdocs\kngtravels\node
_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:68:19)
gyp verb `which` failed     at E (E:\xampp\htdocs\kngtravels\node_modules\which\
which.js:80:29)
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\which\whi
ch.js:89:16
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\ind
ex.js:42:5
gyp verb `which` failed     at E:\xampp\htdocs\kngtravels\node_modules\isexe\win
dows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundEr
ror (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:13:12)\n    at
 F (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:68:19)\n    at
E (E:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:80:29)\n    at E
:\\xampp\\htdocs\\kngtravels\\node_modules\\which\\which.js:89:16\n    at E:\\xa
mpp\\htdocs\\kngtravels\\node_modules\\isexe\\index.js:42:5\n    at E:\\xampp\\h
tdocs\\kngtravels\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomp
lete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.ex
e"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print
(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node v
ersion: 9.0.0
gyp verb command install [ '9.0.0' ]
gyp verb install input version string "9.0.0"
gyp verb install installing version: 9.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 9.0.0
gyp verb ensuring nodedir is created C:\Users\welcome\.node-gyp\9.0.0
gyp verb created nodedir C:\Users\welcome\.node-gyp\9.0.0
gyp http GET https://nodejs.org/download/release/v9.0.0/node-v9.0.0-headers.tar.
gz
gyp WARN download ignoring invalid "proxy" config setting: "127.1.1.1"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '9.0.0' ]
gyp verb remove using node-gyp dir: C:\Users\welcome\.node-gyp
gyp verb remove removing target version: 9.0.0
gyp verb remove removing development files for version: 9.0.0
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=405
gyp ERR! stack     at ClientRequest.onConnect (E:\xampp\htdocs\kngtravels\node_m
odules\request\node_modules\tunnel-agent\index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:328:30)
gyp ERR! stack     at emitThree (events.js:145:13)
gyp ERR! stack     at ClientRequest.emit (events.js:227:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:471:11)
gyp ERR! stack     at emitOne (events.js:125:13)
gyp ERR! stack     at Socket.emit (events.js:221:7)
gyp ERR! stack     at addChunk (_stream_readable.js:265:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:252:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:209:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\xampp\\htdocs\\kngtr
avels\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsas
s_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\xampp\htdocs\kngtravels\node_modules\node-sass
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'E:\xampp\htdocs\kngtrav
els\node_modules\scss-tokenizer\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'E:\xampp\htdocs\kngt
ravels\node_modules\scss-tokenizer\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\xampp\\h
tdocs\\kngtravels\\node_modules\\scss-tokenizer\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'E:\\xampp\\htdocs\\kngtravels\\node_modules\\scss-tokenizer\\n
ode_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\welcome\AppData\Roaming\npm-cache\_logs\2017-11-08T02_43_4
6_165Z-debug.log

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):5.5.1
- Node version (`node -v`):v9.0.0
- Node Process (`node -p process.versions`):v9.0.0
- Node Platform (`node -p process.platform`):win32
- Node architecture (`node -p process.arch`):x64
- node-sass version (`node -p "require('node-sass').info"`):error cannot find node sass module
- npm node-sass versions (`npm ls node-sass`):-- (empty)

**Comment by nschonni** [comment] 2017-11-08 04:05
Duplicate of #2129

**Closed by nschonni** 2017-11-08 04:05 UTC

**Comment by hagar-chen** [comment] 2017-12-31 09:37
Hi, I'm getting the same issue when running sudo npm i, and my package.json file is set to install node-sass 4.6.0

- Npm version 5.5.1

- Node version v8.9.1

- Node process (node -p process.versions)
{ http_parser: '2.7.0',
  node: '8.9.1',
  v8: '6.1.534.47',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2m',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }

- Node platform (node -p process.platform) darwin

- Node architecture (node -p process.arch):x64

- Node-sass version (node -p "require('node-sass').info"):Error: ENOENT: no such file or directory

**Comment by sunranhou** [comment] 2018-01-05 16:07
"Downloading binary from .... Cannot download ..." 
This is the root cause. As your bad network, cannot download something. 
So you can download it with other method and add it to npm cache. 
Based on the error message "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node" we know "v4.5.3/win32-x64-59_binding.node" is that to be downloaded.

 In fact, I known "v4.5.7/win32-x64-59_binding.node" is for the application installed with the package of "node-v9.3.0-x64.msi" in windows10 and "v4.5.7/win32-x64-57_binding.node" for "node-v8.9.1-x64.msi".

For your problem, after you download it. add it to folder "C:\Users\computer-name\AppData\Roaming\npm-cache\node-sass\4.5.3\". 

Re-install, everything is fine.

**Comment by hagar-chen** [comment] 2018-01-06 07:21
This was the problem for me! thanks!
