### ISSUE TITLE
Node Sass version 6.0.1 is incompatible with ^4.0.0 || ^5.0.0.

### ISSUE THREAD

**Issue by vitpankin** [sass/node-sass#3181] opened 2021-09-10 03:18 UTC
Node Sass version 6.0.1 is incompatible with ^4.0.0 || ^5.0.0. 

npx create-react-app my-app \ yarn create react-app my-app
yarn add node-sass
Whatever I'm trying to do.

- NPM version (`npm -v`): 7.21.0
- Node version (`node -v`): v16.8.0
- Node Process (`node -p process.versions`): 
```{
  node: '16.8.0',
  v8: '9.2.230.21-node.20',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.44.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): code: 'MODULE_NOT_FOUND',
- npm node-sass versions (`npm ls node-sass`): (empty)

**Comment by nschonni** [comment] 2021-09-10 03:20
Duplicate of #3103

**Closed by nschonni** 2021-09-10 03:20 UTC
