### ISSUE TITLE
Assertion `(new_handler_count) >= (0)' failed [node v13.2]

### ISSUE THREAD

**Issue by adrianmay** [sass/node-sass#2805] opened 2019-12-09 16:27 UTC
Hope this helps:

```
$ npm install node-sass

> node-sass@4.13.0 install /home/adrianmay/src/tracs-enterprise/master/webpack/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-79_binding.node
Download complete..] - :
Binary saved to /home/adrianmay/src/tracs-enterprise/master/webpack/node_modules/node-sass/vendor/linux-x64-79/binding.node
Caching binary to /home/adrianmay/.npm/node-sass/4.13.0/linux-x64-79_binding.node
node[553980]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion `(new_handler_count) >= (0)' failed.
 1: 0x5619fe77b041 node::Abort() [node]
 2: 0x5619fe77b0e1  [node]
 3: 0x5619fe828183 node::DecreaseSignalHandlerCount(int) [node]
 4: 0x5619fe8282af  [node]
 5: 0x5619fe70e927 node::Environment::CleanupHandles() [node]
 6: 0x5619fe70ebff node::Environment::RunCleanup() [node]
 7: 0x5619fe7c1a3b node::NodeMainInstance::Run() [node]
 8: 0x5619fe7484de node::Start(int, char**) [node]
 9: 0x7f2c65953153 __libc_start_main [/usr/lib/libc.so.6]
10: 0x5619fe6d574e _start [node]
zsh: abort (core dumped)  npm install node-sass

$ node --version
v13.2.0

$ npm --version
6.12.1

$ node -p process.versions
{
  node: '13.2.0',
  v8: '7.9.317.23-node.20',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '79',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  openssl: '1.1.1d',
  cldr: '36.0',
  icu: '65.1',
  tz: '2019c',
  unicode: '12.1'
}

$ node -p process.platform
linux

$ node -p process.arch
x64

$ node -p "require('node-sass').info"
node-sass	4.13.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]

$ npm ls node-sass
XXXXX@0.1.0 /home/XXXXX/src/XXXXXX/master/webpack
└── (empty)

```

**Comment by saper** [comment] 2019-12-09 23:01
What operating system is this? (As much details as possible please)

**Comment by xzyfer** [comment] 2019-12-10 21:58
It's possible the Darwin binaries built on Mojave aren't compatibile with Catalina

**Comment by phibsi** [comment] 2019-12-11 20:48
Hi,

I have the same issue with node-sass@4.13.0 on Windows.
Any Idea?

System: Windows 10 18363.476 x64
NodeJS: v13.2.0
npm: 6.13.1

```
> node-sass@4.13.0 install C:\test\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-79_binding.node
Download complete .] - :
Binary saved to C:\test\node_modules\node-sass\vendor\win32-x64-79\binding.node
Caching binary to C:\Users\phili\AppData\Roaming\npm-cache\node-sass\4.13.0\win32-x64-79_binding.node
npm[10404]: c:\ws\src\signal_wrap.cc:159: Assertion `(new_handler_count) >= (0)' failed.
 1: 00007FF77B86021F napi_wrap+124591
 2: 00007FF77B800296 v8::base::CPU::has_sse+35542
 3: 00007FF77B8005B3 v8::base::CPU::has_sse+36339
 4: 00007FF77B784393 v8::internal::MicrotaskQueue::microtasks_policy+37795
 5: 00007FF77B7839D4 v8::internal::MicrotaskQueue::microtasks_policy+35300
 6: 00007FF77B84C20D napi_wrap+42653
 7: 00007FF77B85A62A napi_wrap+101050
 8: 00007FF77B7CC1CB v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder+29851
 9: 00007FF77B828080 node::Start+288
10: 00007FF77B6E66FC RC4_options+339452
11: 00007FF77C527678 v8::internal::SetupIsolateDelegate::SetupHeap+1290008
12: 00007FFFDD5B7BD4 BaseThreadInitThunk+20
13: 00007FFFDDDACED1 RtlUserThreadStart+33
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-sass@4.13.0 install: `node scripts/install.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\phili\AppData\Roaming\npm-cache\_logs\2019-12-11T20_34_43_907Z-debug.log
```

**Comment by saper** [comment] 2019-12-14 12:56
This is the same as https://github.com/nodejs/node/issues/30581 as well a duplicate of https://github.com/sass/node-sass/issues/2807

Please upgrade to node v13.3.0

**Closed by saper** 2019-12-14 12:56 UTC
Labels: External - Node, Node 13
