### ISSUE TITLE
Post install failed

### ISSUE THREAD

**Issue by ZaniaDeveloper** [sass/node-sass#2178] opened 2017-12-05 08:12 UTC
- NPM version (`npm -v`): 5.5.1
- Node version (`node -v`): v6.11.4
- Node Process (`node -p process.versions`):
```js
{ http_parser: '2.7.0',
  node: '6.11.4',
  v8: '5.1.281.108',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.13.0',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2g' }
```
- Node Platform (`node -p process.platform`): linux
- Node architecture (`node -p process.arch`): x64

When i want install, here is the result, **with an infinite execution, the installation processus never ends** :

![image](https://user-images.githubusercontent.com/30778006/33596140-c0ded5b2-d9ab-11e7-8aac-07bf28a0ea75.png)

And it's absolutely not a problem with access rights (permissions), indeed, the */usr/local/lib/node_modules/node-sass/vendor/linux-x64-48* directory can't be created cause the */usr/local/lib/node_modules/node-sass/vendor* directory never exists in post-install.

**Comment by nschonni** [comment] 2017-12-06 23:00
It is an access issue from the `EACCES` message.
Duplicate of #1098

**Closed by nschonni** 2017-12-06 23:00 UTC

**Comment by mvrhov** [comment] 2017-12-07 17:23
I'm also hitting this. And it cannot be access issue. as I'm running npm install as root

**Comment by mvrhov** [comment] 2017-12-07 17:38
I had to run npm with: `npm install --unsafe-perm=true`

The problem is with node-sass because it tries to install some files globally!
```
npm install --unsafe-perm=true

> node-sass@4.7.2 install /srv/www/project/site/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-57_binding.node
Download complete..] - :
Binary saved to /srv/www/project/site/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.7.2/linux-x64-57_binding.node
```

**Comment by tripstar22** [comment] 2017-12-13 14:52
Had the same issue as @mvrhov and his solution worked for me

**Comment by ZaniaDeveloper** [comment] 2017-12-15 07:41
@nschonni read all the content of issue, please, it's absolutely not an EACCES, and #1098 can't resolve problem !

I said « /usr/local/lib/node_modules/node-sass/vendor/linux-x64-48 directory *can't be created* cause the /usr/local/lib/node_modules/node-sass/vendor directory », it's cause the vendor directory doesn't exist, the vendor directory is not created. If it can't be created cause an EACCES, so the solution is elsewhere i'm executed command in a root session (no need sudo).

Yes, it's an `npm install -g` command in a root terminal in a root session, root user has all permissions ! Am i wrong ?. How to have an EACESS problem in a root session, i don't know.

In #1098, @saper said « sudo npm will run our installations scripts as nobody », so i switched to root session by `sudo su -` but the same problem has always occured. Then i did a `chown -R nobody $(npm config get prefix)/{lib/node_modules,bin,share}`, but that's failed too.

Following @mvrhov 's advice, i did `npm install --unsafe-perm=true -g node-sass` and it works. #1098 resolves nothing at all, but @mvrhov resolved the problem.

This problem is a big big big problem, cause node-sass is in dependencies of others project like "@angular/cli", and cause this problem "@angular/cli" can't be installed cause this big big problem.

Fortunately @mvrhov is here and now i can use "@angular/cli".
