### ISSUE TITLE
node 6.3 The `libsass` binding was not found

### ISSUE THREAD

**Issue by dcsan** [sass/node-sass#1629] opened 2016-07-12 22:42 UTC
I tried reports on other tickets regarding this, but can't seem to get this working.

error occurs with node versions:

  ο node/6.0.0
    node/6.2.2
    node/6.3.0

no problem with node v5.x

npm -v
2.14.20

on starting my app:

```
bin/run-local.sh                                                                                             *[master] 
(node:5849) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:5849) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/harp/node_modules/terraform/lib/stylesheet/pro
```

so try to rebuild

```
$ npm rebuild node-sass                                                                                        *[master] 

> node-sass@3.4.2 install /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/install.js


> node-sass@3.4.2 postinstall /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass
> node scripts/build.js

` /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node ` exists. 
 testing binary.
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x340e20ac9e59 <JS Object>#0#
    1: .node [module.js:568] [pc=0x103a71877704] (this=0x11ca3f0053a1 <an Object with map 0x33575a71a261>#1#,module=0x11ca3f152391 <a Module with map 0x33575a71a839>#2#,filename=0x11ca3f1522f1 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    2: load [module.js:458] [pc=0x103a71835772] (this=0x11ca3f152391 <a Module with map 0x33575a71a839>#2#,filename=0x11ca3f1522f1 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x103a7183529d] (this=0x340e20a04189 <undefined>,module=0x11ca3f152391 <a Module with map 0x33575a71a839>#2#,filename=0x11ca3f1522f1 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    4: _load [module.js:409] [pc=0x103a71830e82] (this=0x11ca3f005011 <JS Function Module (SharedFunctionInfo 0x3c0cc9a2db71)>#3#,request=0x11ca3f150e71 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>,parent=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,isMain=0x340e20a04299 <false>)
    5: require [module.js:468] [pc=0x103a7183df33] (this=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,path=0x11ca3f150e71 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    6: require(aka require) [internal/module.js:20] [pc=0x103a7183dc66] (this=0x340e20a04189 <undefined>,path=0x11ca3f150e71 <String[136]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    7: /* anonymous */ [/Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js:16] [pc=0x103a71877031] (this=0x11ca3f146b21 <an Object with map 0x281e68a07ac1>#5#,exports=0x11ca3f146b21 <an Object with map 0x281e68a07ac1>#5#,require=0x11ca3f14d859 <JS Function require (SharedFunctionInfo 0x3c0cc9a5cc99)>#6#,module=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,__filename=0x11ca3f146a41 <String[115]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js>,__dirname=0x11ca3f14d7f1 <String[106]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib>)
    8: _compile [module.js:541] [pc=0x103a7183cd30] (this=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,content=0x11ca3f147c19 <Very long string[9231]>#7#,filename=0x11ca3f146a41 <String[115]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js>)
    9: .js [module.js:550] [pc=0x103a71836d6b] (this=0x11ca3f0053a1 <an Object with map 0x33575a71a261>#1#,module=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,filename=0x11ca3f146a41 <String[115]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js>)
   10: load [module.js:458] [pc=0x103a71835772] (this=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,filename=0x11ca3f146a41 <String[115]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js>)
   11: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x103a7183529d] (this=0x340e20a04189 <undefined>,module=0x11ca3f146ad1 <a Module with map 0x33575a71a839>#4#,filename=0x11ca3f146a41 <String[115]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/lib/index.js>)
   12: _load [module.js:409] [pc=0x103a71830e82] (this=0x11ca3f005011 <JS Function Module (SharedFunctionInfo 0x3c0cc9a2db71)>#3#,request=0x3c0cc9a5bec1 <String[3]: ../>,parent=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,isMain=0x340e20a04299 <false>)
   13: require [module.js:468] [pc=0x103a7183df33] (this=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,path=0x3c0cc9a5bec1 <String[3]: ../>)
   14: require(aka require) [internal/module.js:20] [pc=0x103a7183dc66] (this=0x340e20a04189 <undefined>,path=0x3c0cc9a5bec1 <String[3]: ../>)
   15: testBinary [/Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js:209] [pc=0x103a71860863] (this=0x340e20ae1601 <JS Global Object>#9#,options=0x11ca3f133c81 <an Object with map 0x33575a72fc31>#10#)
   16: /* anonymous */ [/Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js:225] [pc=0x103a7183d72c] (this=0x11ca3f006871 <an Object with map 0x281e68a07ac1>#11#,exports=0x11ca3f006871 <an Object with map 0x281e68a07ac1>#11#,require=0x11ca3f006601 <JS Function require (SharedFunctionInfo 0x3c0cc9a5cc99)>#12#,module=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,__filename=0x11ca3f0067e1 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>,__dirname=0x11ca3f0067b9 <String[110]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts>)
   17: _compile [module.js:541] [pc=0x103a7183cd30] (this=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,content=0x11ca3f007c31 <Very long string[4873]>#13#,filename=0x11ca3f0067e1 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>)
   18: .js [module.js:550] [pc=0x103a71836d6b] (this=0x11ca3f0053a1 <an Object with map 0x33575a71a261>#1#,module=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,filename=0x11ca3f0067e1 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>)
   19: load [module.js:458] [pc=0x103a71835772] (this=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,filename=0x11ca3f0067e1 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>)
   20: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x103a7183529d] (this=0x340e20a04189 <undefined>,module=0x11ca3f006539 <a Module with map 0x33575a71a839>#8#,filename=0x11ca3f0067e1 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>)
   21: _load [module.js:409] [pc=0x103a71830e82] (this=0x11ca3f005011 <JS Function Module (SharedFunctionInfo 0x3c0cc9a2db71)>#3#,request=0x11ca3f008f79 <String[119]: /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass/scripts/build.js>,parent=0x340e20a04101 <null>,isMain=0x340e20a04231 <true>)
   22: /* anonymous */(aka /* anonymous */) [module.js:575] [pc=0x103a7183094a] (this=0x340e20a04189 <undefined>)
   23: run(aka run) [bootstrap_node.js:352] [pc=0x103a718307c8] (this=0x340e20a04189 <undefined>,entryFunction=0x3c0cc9a52ad1 <JS Function Module.runMain (SharedFunctionInfo 0x3c0cc9a2e8f1)>#14#)
   24: startup(aka startup) [bootstrap_node.js:144] [pc=0x103a71740615] (this=0x340e20a04189 <undefined>)
   25: /* anonymous */(aka /* anonymous */) [bootstrap_node.js:467] [pc=0x103a7173e59f] (this=0x340e20a04101 <null>,process=0x340e20add419 <a process with map 0x281e68a115c9>#15#)
=====================


==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: SassTypes::Boolean::get_constructor()
 3: SassTypes::Factory::initExports(v8::Local<v8::Object>)
 4: RegisterModule(v8::Local<v8::Object>)
 5: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 6: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 7: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 8: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 9: 0x103a7170961b
10: 0x103a71877704
Binary is fine; exiting.

> node-sass@3.8.0 install /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/node-sass
> node scripts/install.js


> node-sass@3.8.0 postinstall /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/node-sass
> node scripts/build.js

"/Users/dc/dev/rikai/rikai.co/harp-site/node_modules/node-sass/vendor/darwin-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/harp/node_modules/terraform/node_modules/node-sass
node-sass@3.8.0 /Users/dc/dev/rikai/rikai.co/harp-site/node_modules/node-sass
```

same error on trying to restart

I nuked ALL the node_modules and `npm install`ed again.
same problem. 

I changed down to node v5 and everything works fine.

**Comment by dcsan** [comment] 2016-07-12 22:48
In addition some 42M huge file has been created:

-rw-r--r--  1 dc  staff    42M Jul 12 15:36 node_modules/harp/node_modules/terraform/node_modules/node-sass/build/Release/sass.a

is this .a file some crash/compile artifact i can delete?

**Comment by nschonni** [comment] 2016-07-12 22:55
Dupe of #1612, see response https://github.com/sass/node-sass/issues/1612#issuecomment-228993387

**Closed by nschonni** 2016-07-12 22:55 UTC

**Comment by dcsan** [comment] 2016-07-12 23:13
tx for the quick reply!
