### ISSUE TITLE
Including mixin in itself produces no output, no error

### ISSUE THREAD

**Issue by mattdistefano** [sass/node-sass#1582] opened 2016-06-07 18:09 UTC
Not sure if this is a node-sass or libsass issue but...

The following code just causes the process to exit without error or output (using the CLI and gulp-sass):

```scss
@mixin my-mixin() {
    @include my-mixin();
}

.foo {
    display: block;
}

@include my-mixin();
```
Obviously I don't expect this to actually compile, but it seems like there should be an error emitted at least.

node 5.8.0 on Windows 10
node-sass       3.7.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]

**Comment by xzyfer** [comment] 2016-06-08 00:02
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output. In the future please confirm that LibSass' output differs from Ruby Sass before opening an issue.

If you wish to suggest features of file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Closed by xzyfer** 2016-06-08 00:02 UTC

**Comment by xzyfer** [comment] 2016-06-08 00:04
Thanks for your report @mattdistefano. I have confirmed that Ruby Sass does the same thing given the code you have supplied. You can always test this yourself online with http://sassmeister.com.

I agree that producing no output/error here is strange. Please an in issue with the official Sass compiler.
