### ISSUE TITLE
(Windows) npm install node-sass fails @ node-sass@2.0.0-beta install script 'node scripts/install.js'

### ISSUE THREAD

**Issue by kvntrn** [sass/node-sass#659] opened 2015-02-10 16:37 UTC
C:\temp1>node -v
v0.12.0

C:\temp1>npm -v
2.5.1

C:\temp1>node -p process.arch
ia32

C:\temp1>npm install node-sass
\
> node-sass@2.0.0-beta install C:\temp1\node_modules\node-sass
> node scripts/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\ktran\scripts\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@2.0.0-beta install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@2.0.0-beta install script 'node scripts/install
.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp1\npm-debug.log

C:\temp1>

Any assistance would be great.

Thank you.

**Comment by am11** [comment] 2015-02-10 17:09
Duplicate of https://github.com/sass/node-sass/issues/656.

Wait for vNext of node-sass, it will be compatible with node v0.12.

**Closed by am11** 2015-02-10 17:09 UTC
Labels: Duplicate
