### ISSUE TITLE
npm install generating error : Failed at the node-sass@4.5.3 postinstall script

### ISSUE THREAD

**Issue by shaharyar123** [sass/node-sass#2990] opened 2020-10-03 11:42 UTC
- NPM version (`6.14.6`):
- Node version (`12.18.4`):
- Node Process ({
  node: '12.18.4',
  v8: '7.8.279.23-node.39',
  uv: '1.38.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.16.0',
  modules: '72',
  nghttp2: '1.41.0',
  napi: '6',
  llhttp: '2.1.2',
  http_parser: '2.9.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}):
- Node Platform (`linux`):
- Node architecture (`x64`):
- node-sass version (`node-sass       4.12.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]`):
- npm node-sass versions (`node-sass@4.12.0 `):

i am having angular/ionic project. 
by running command `npm i` it falls back to the error 
````
cpp
../src/binding.cpp: In function ‘void MakeCallback(uv_work_t*)’:
../src/binding.cpp:246:39: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     ctx_w->success_callback->Call(0, 0);
                                       ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/binding.cpp:254:40: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     ctx_w->error_callback->Call(1, argv);
                                        ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘T CallbackBridge<T, L>::operator()(std::vector<void*>) [with T = Sass_Import**; L = void*]’:
../src/binding.cpp:19:21:   required from here
../src/callback_bridge.h:111:5: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     );
     ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘T CallbackBridge<T, L>::operator()(std::vector<void*>) [with T = Sass_Value*; L = void*]’:
../src/binding.cpp:32:21:   required from here
../src/callback_bridge.h:111:5: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     );
     ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Value*; L = void*; uv_async_t = uv_async_s]’:
../src/callback_bridge.h:68:18:   required from ‘CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Value*; L = void*]’
../src/custom_function_bridge.h:11:109:   required from here
../src/callback_bridge.h:162:3: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
   ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
In file included from ../src/custom_function_bridge.h:7:0,
                 from ../src/sass_context_wrapper.h:9,
                 from ../src/binding.cpp:3:
../src/callback_bridge.h: In instantiation of ‘static void CallbackBridge<T, L>::dispatched_async_uv_callback(uv_async_t*) [with T = Sass_Import**; L = void*; uv_async_t = uv_async_s]’:
../src/callback_bridge.h:68:18:   required from ‘CallbackBridge<T, L>::CallbackBridge(v8::Local<v8::Function>, bool) [with T = Sass_Import**; L = void*]’
../src/custom_importer_bridge.h:13:112:   required from here
../src/callback_bridge.h:162:3: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
   ^
In file included from ../src/binding.cpp:1:0:
../../../../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/shaharyar/.node-gyp/12.18.4/include/node -I/home/shaharyar/.node-gyp/12.18.4/src -I/home/shaharyar/.node-gyp/12.18.4/deps/openssl/config -I/home/shaharyar/.node-gyp/12.18.4/deps/openssl/openssl/include -I/home/shaharyar/.node-gyp/12.18.4/deps/uv/include -I/home/shaharyar/.node-gyp/12.18.4/deps/zlib -I/home/shaharyar/.node-gyp/12.18.4/deps/v8/include -I../../../../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
In file included from /home/shaharyar/.node-gyp/12.18.4/include/node/node.h:67:0,
                 from ../../../../../nan/nan.h:56,
                 from ../src/create_string.cpp:1:
/home/shaharyar/.node-gyp/12.18.4/include/node/v8.h:3135:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^
/home/shaharyar/.node-gyp/12.18.4/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/home/shaharyar/peter-projects/staffy-ionic-v2/node_modules/@ionic/app-scripts/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/shaharyar/peter-projects/staffy-ionic-v2/node_modules/@ionic/app-scripts/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-118-generic
gyp ERR! command "/usr/local/bin/node" "/home/shaharyar/peter-projects/staffy-ionic-v2/node_modules/@ionic/app-scripts/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/shaharyar/peter-projects/staffy-ionic-v2/node_modules/@ionic/app-scripts/node_modules/node-sass
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular-devkit/build-webpack@0.803.29 requires a peer of webpack@^4.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/stripe@4.20.0 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic-native/stripe@4.20.0 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@8.3.29 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@10.1.4 requires a peer of zone.js@~0.10.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@10.1.4 requires a peer of @angular/platform-browser@10.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN circular-dependency-plugin@5.2.0 requires a peer of webpack@>=4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN copy-webpack-plugin@6.0.3 requires a peer of webpack@^4.37.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@4.2.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.5.4 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
npm WARN mini-css-extract-plugin@0.8.0 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN raw-loader@3.1.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN style-loader@1.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@3.0.3 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.11.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-plugin@3.2.0 requires a peer of webpack@>= 4 but none is installed. You must install peer dependencies yourself.
npm WARN The package @angular/compiler is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/sass/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shaharyar/.npm/_logs/2020-10-03T11_36_11_411Z-debug.log
````

my package.json is 
````
{
  "name": "x",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --source-map",
    "build": "BUILD_ENV=${BUILD_ENV: -dev}  ng build --configuration=$BUILD_ENV --source-map",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ng build --prod --source-map",
    "heroku-postbuild": "ng build --prod --source-map"
  },
  "config": {
    "ionic_generate_source_map": "true"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/pwa": "^0.802.2",
    "@angular/router": "~8.1.2",
    "@angular/service-worker": "~8.1.2",
    "@ionic-native/app-rate": "^5.18.0",
    "@ionic-native/app-version": "^5.28.0",
    "@ionic-native/camera": "^5.13.0",
    "@ionic-native/contacts": "^5.26.0",
    "@ionic-native/core": "^5.13.0",
    "@ionic-native/device": "^5.28.0",
    "@ionic-native/file": "^5.27.0",
    "@ionic-native/file-opener": "^5.27.0",
    "@ionic-native/file-transfer": "^5.13.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/in-app-browser": "^5.18.0",
    "@ionic-native/keyboard": "^5.26.0",
    "@ionic-native/network": "^5.19.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.28.0",
    "@ionic-native/stripe": "^4.20.0",
    "@ionic/angular": "^4.7.1",
    "@ionic/app-scripts": "2.1.4",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "2.2.0",
    "@logisticinfotech/ionic-timepicker": "^1.0.3",
    "@ngrx/effects": "^8.2.0",
    "@ngrx/router-store": "^8.2.0",
    "@ngrx/store": "^8.2.0",
    "@ngrx/store-devtools": "^8.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@sentry/angular": "^5.24.2",
    "@sentry/tracing": "^5.24.2",
    "@types/cordova-plugin-network-information": "^1.3.2",
    "@types/lodash": "^4.14.157",
    "bignumber.js": "^9.0.0",
    "cordova-android": "8.0.0",
    "cordova-plugin-apprate": "1.5.0",
    "cordova-plugin-camera": "4.1.0",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-dialogs": "2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "3.0.3",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-inappbrowser": "3.1.0",
    "cordova-plugin-nativestorage": "2.3.2",
    "cordova-plugin-network-information": "2.0.2",
    "cordova-sqlite-storage": "3.3.0",
    "core-js": "^2.5.4",
    "express": "^4.17.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.3.2",
    "moment-timezone": "^0.5.31",
    "ng-starrating": "1.0.11",
    "ng2-date-picker": "8.0.0",
    "ng2-pdf-viewer": "^6.3.2",
    "ngx-doc-viewer": "^1.3.0",
    "ngx-webcam": "^0.2.6",
    "pdfmake": "^0.1.66",
    "pushwoosh-cordova-plugin": "^7.18.11",
    "rxjs": "~6.5.1",
    "sentry-cordova": "^0.17.0",
    "tslib": "^1.9.0",
    "typescript": "~3.4.3",
    "update": "^0.7.4",
    "webdriver-manager": "^12.1.7",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.803.20",
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular-devkit/core": "~8.3.20",
    "@angular-devkit/schematics": "~8.3.20",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/googlemaps": "^3.39.8",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/moment": "^2.13.0",
    "@types/moment-duration-format": "^2.2.2",
    "@types/moment-timezone": "^0.5.13",
    "@types/node": "~8.9.4",
    "@types/stripe-checkout": "^1.0.3",
    "@types/stripe-v3": "^3.1.7",
    "codelyzer": "^5.2.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-ionic": "^5.4.7",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-splashscreen": "^5.0.4",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "node-gyp": "^7.0.0",
    "node-sass": "^4.12.0",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0"
  },
  "description": "An Ionic project",
  "engines": {
    "node": "10.16.3",
    "npm": "6.9.0"
  },
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-apprate": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-contacts": {},
      "pushwoosh-cordova-plugin": {
        "LOG_LEVEL": "DEBUG",
        "IOS_FOREGROUND_ALERT_TYPE": "NONE",
        "ANDROID_FOREGROUND_PUSH": "false"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-file-opener2": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-app-version": {},
      "cordova-plugin-ionic": {
        "APP_ID": "da4462b7",
        "CHANNEL_NAME": "Production",
        "UPDATE_METHOD": "background",
        "MAX_STORE": "2",
        "MIN_BACKGROUND_DURATION": "30",
        "UPDATE_API": "https://api.ionicjs.com"
      },
      "sentry-cordova": {
        "SENTRY_ANDROID_SDK_VERSION": "1+"
      }
    },
    "platforms": [
      "android"
    ]
  },
  "optionalDependencies": {
    "fsevents": "^2.1.3"
  }
}
````

**Comment by nschonni** [comment] 2020-10-03 15:06
Duplicate of a bunch of issues, but basically your node version is too new for the really old node-sass https://github.com/sass/node-sass#node-version-support-policy

**Closed by nschonni** 2020-10-03 15:06 UTC
