### ISSUE TITLE
Install problems 3.5.2

### ISSUE THREAD

**Issue by basvandenheuvel** [sass/node-sass#1461] opened 2016-04-21 11:11 UTC
I use gulp-sass which uses node-sass "^3.5.1". Before 3.5.2 was released i had proxy issues. Since 3.5.2 is released i get this error when i'm behind a proxy (only when i'm behind a proxy):

npm ERR! node-sass@3.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.5.2 postinstall script 'node scripts/build.js
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by xzyfer** [comment] 2016-04-21 11:30
Unfortunately that doesn't help, but following the [troubleshooting documentation](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#linuxosx) will.

Make sure to preserve **all** of the output into to [gist](https://gist.github.com/). Please do not post the output into this issue.

**Comment by basvandenheuvel** [comment] 2016-04-21 11:52
@xzyfer see this gist for the npm-debug.log: https://gist.github.com/basvandenheuvel/392d5945f1f45ae01bae72d54790b9b3

**Comment by marfous** [comment] 2016-04-21 12:21
@xzyfer it looks I'm facing the same issue:
https://gist.github.com/marfous/22390a005aa7ec7a279070a4c2c3a722

We are behind a proxy.
I tried to put several console.logs into the install.js script and it looks to be stuck at:
`got.stream(url, options)
.on('error', function(error) {
        reportError(error);
})
        .on('end', function() {
          cb();
        })
        .pipe(fs.createWriteStream(dest));`

Since the 'end' callback is never called, it looks to be still connection issues. Can I add any information which would help you to resolve this? Thanks.

**Comment by xzyfer** [comment] 2016-04-21 13:23
@marfous please confirm your issue still exists with node-sass@v3.5.3

**Comment by xzyfer** [comment] 2016-04-21 13:25
This appears to be a duplicate of https://github.com/sass/node-sass/issues/1455. Closing this so we can centralise the conversation on one issue.

**Closed by xzyfer** 2016-04-21 13:25 UTC
Labels: Bug - Maybe, NPM - Install

**Comment by basvandenheuvel** [comment] 2016-04-21 13:56
@xzyfer looks like it works now! thanks
