### ISSUE TITLE
Consider using node-pre-gyp

### ISSUE THREAD

**Issue by saper** [sass/node-sass#766] opened 2015-03-16 08:35 UTC
I am somehow frustrated with our scripts.

http://github.com/mapbox/node-pre-gyp could possibly fetch binaries for us, it supports options like `--build-from-source` and `--fallback-to-build`

**Comment by am11** [comment] 2015-03-16 08:39
Duplicate of https://github.com/sass/node-sass/issues/56.

**Closed by am11** 2015-03-16 08:39 UTC

**Comment by saper** [comment] 2015-03-16 08:55
How is that? It's about getting rid of our `scripts/install.js` and friends...

**Comment by am11** [comment] 2015-03-16 08:59
If you read down, there is mentioning on node-pre-gyp and *automating* the build process.

**Comment by am11** [comment] 2015-03-16 09:06
Also if you search the issue tracker before opening a new issue, you will find that at 33 distinct places, this matter has been discussed. Please read the [contributing guideline](https://github.com/sass/node-sass/blob/master/CONTRIBUTING.md#bug-reports) which begs issue reporter to make use of GH search feature -- coz its pretty awesome! :sunglasses:

**Comment by saper** [comment] 2015-03-16 09:12
People discuss everything everywhere. Bug #56 is about automated build (things like poudriere I am using or vagrant) and not primarily about node-pre-gyp. The guideline recommends specifically that problems should be isolated.

**Comment by am11** [comment] 2015-03-16 09:34
That is a guideline for bug. This is a feature suggestion. Suggestions can be broader. Automating the build is what node-pre-gyp which is just a "tool". There are other methods available. So please continue this discussion where it belong!
