### ISSUE TITLE
node-sass 4.8.1 can't parse @extend %#{$loading-animation} !optional

### ISSUE THREAD

**Issue by JoyeLuo** [sass/node-sass#2283] opened 2018-03-13 02:37 UTC
Error: build/_css/clay/mixins/_buttons.scss
Error: Invalid CSS after "%": expected selector, was "% !optional"
        on line 61 of build/_css/clay/mixins/_buttons.scss

The line:  @extend %#{$loading-animation} !optional;

When I change node-sass version to 4.7.2, this problem was gone.

**Comment by xzyfer** [comment] 2018-03-13 02:47
Can you please provide a copy pastes let example I can use to reproduce
this error locally.

**Comment by JoyeLuo** [comment] 2018-03-13 05:43
This is the content of _buttons.scss
`@mixin clay-button-variant($map) {
	$bg: map-get($map, bg);
	$border-color: map-get($map, border-color);
	$color: map-get($map, color);
	$hover-bg: map-get($map, hover-bg);
	$hover-border-color: map-get($map, hover-border-color);
	$hover-color: map-get($map, hover-color);
	$focus-bg: setter(map-get($map, focus-bg), $hover-bg);
	$focus-border-color: setter(map-get($map, focus-border-color), $hover-border-color);
	$focus-box-shadow: map-get($map, focus-box-shadow);
	$focus-color: map-get($map, focus-color);
	$disabled-bg: map-get($map, disabled-bg);
	$disabled-border-color: map-get($map, disabled-border-color);
	$disabled-color: map-get($map, disabled-color);
	$active-bg: map-get($map, active-bg);
	$active-border-color: map-get($map, active-border-color);
	$active-box-shadow: map-get($map, active-box-shadow);
	$active-color: map-get($map, active-color);
	$active-focus-box-shadow: setter(map-get($map, active-focus-box-shadow), $focus-box-shadow);
	$loading-animation: map-get($map, loading-animation);

	background-color: $bg;
	border-color: $border-color;
	color: $color;

	@include hover {
		background-color: $hover-bg;
		border-color: $hover-border-color;
		color: $hover-color;
	}

	&:focus,
	&.focus {
		background-color: $focus-bg;
		border-color: $focus-border-color;
		box-shadow: $focus-box-shadow;
		color: $focus-color;
	}

	&:disabled,
	&.disabled {
		background-color: $disabled-bg;
		border-color: $disabled-border-color;
		color: $disabled-color;
	}

	&:not([disabled]):not(.disabled):active,
	&:not([disabled]):not(.disabled).active,
	.show > &.dropdown-toggle {
		background-color: $active-bg;
		border-color: $active-border-color;
		box-shadow: $active-box-shadow;
		color: $active-color;

		&:focus {
			box-shadow: $active-focus-box-shadow;
		}
	}

	.loading-animation {
		@extend %#{$loading-animation} !optional;
	}
}`

**Comment by nschonni** [comment] 2018-03-13 06:19
I simplified the case to
```scss
@mixin undelcared-variable-interpolation() {
	.loading-animation {
		@extend %#{$loading-animation} !optional;
	}
}

foo {
  @include undelcared-variable-interpolation()
}
```
Which still outputs an error in Ruby Sass and Libsass 3.5.0-beta2 (node-sass 4.7.2) "Undefined variable: "$loading-animation"."

**Comment by nschonni** [comment] 2018-03-13 06:24
This also produces the same message as the original error
```scss
$loading-animation: "";
@mixin undelcared-variable-interpolation() {
	.loading-animation {
		@extend %#{$loading-animation} !optional;
	}
}

foo {
  @include undelcared-variable-interpolation()
}
```
Which gave the same error with Ruby Sass, but not with 3.5.0-beta2 (node-sass 4.7.2).

I'm closing this as it appears the old behaviour in 4.7.2 was actually a bug

**Closed by nschonni** 2018-03-13 06:24 UTC
Labels: Awaiting Response, node-sass 4.8

**Comment by JoyeLuo** [comment] 2018-03-13 06:30
I have $loading-animation variable defined in another file. 
And I don't know how to send u the whole project.

**Comment by nschonni** [comment] 2018-03-13 06:44
Please try to create a minimal reproduction if you think it is valid, but it appears that the variables is set to an empty string which is creating invalid placholder class. Previously node-sass didn't throw an error where it should have.
EX: if the viable is set to an empty string, it's equivalent to 
```scss
	.loading-animation {
		@extend % !optional;
	}
```
So even though you have the `!optional`, it will still throw an error because of the invalid/empty placeholder

**Comment by JoyeLuo** [comment] 2018-03-13 06:54
Thanks a lot. I finally got what you mean.

**Comment by cmal** [comment] 2018-08-29 07:41
I probably have the same problem:
```
@-webkit-keyframes rcToolTipZoomIn {
  @extend .fnrcToolTipZoomIn;
}
@keyframes rcToolTipZoomIn {
  @extend .fnrcToolTipZoomIn;
}
```

```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js?outputStyle=expanded!./app/style/entry/campulCourseEmpty.scss
Module build failed:
  @extend .fnrcToolTipZoomIn;
         ^
      Extend directives may only be used within rules.
      in /home/works/build/frontend/app/style/component/tooltip.scss (line 166, column 11)
 @ ./app/style/entry/campulCourseEmpty.scss 4:14-239
Warning: Task "webpack:campulCourseEmpty" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by nschonni** [comment] 2018-08-29 22:30
> Extend directives may only be used within rules.

@cmal  your code isn't valid Sass
