### ISSUE TITLE
invalid "Duplicate key" error thrown

### ISSUE THREAD

**Issue by eoneill** [sass/node-sass#1072] opened 2015-08-14 23:58 UTC
Here's a simplified test case:

```scss
$tmp: (
  in an alert: alert,
  within a toolbar: toolbar
);
```

And the failure:

```sh
/Users/eoneill/workspace/node-sass-test/node_modules/node-sass/lib/index.js:409
  throw util._extend(new Error(), JSON.parse(result.error));
             ^
Error: Duplicate key "within a toolbar" in map (in an alert: toolbar).
```

This appears to work correctly in libsass (@3.2.5) and in ruby sass (@3.4.14)

**Comment by saper** [comment] 2015-08-15 01:31
which version of node-sass?

**Comment by eoneill** [comment] 2015-08-15 21:18
Using node-sass@3.2.0

**Comment by saper** [comment] 2015-08-16 01:37
Thanks. On my shiny development version I cannot reproduce this at the moment.

**Comment by xzyfer** [comment] 2015-08-16 02:46
Node Sass versions are couple to libsass versions. If it works in LibSass 3.2.5 it works in node-sass@3.2.0. It's likely you have grunt/gulp-sass installed and it's using an older version of node-sass.

**Comment by eoneill** [comment] 2015-08-16 08:19
I created a repo that reproduces consistently (for me).
https://github.com/eoneill/node-sass-issue-1072

I'm using node-sass directly, nothing else.

I tried using `.render()` vs `.renderSync()` as well as passing `data` vs `file` and each case fails.

I can reproduced across different machines so let me know if you still can't repro. I can try to narrow down more specifics.

**Comment by saper** [comment] 2015-08-16 11:27
I think my problems with reproducing it is good news: it git fixed in the meantime:) need to figure out why

**Comment by xzyfer** [comment] 2015-08-17 15:13
@eoneill thanks heaps for your effort. This is a known issue with LibSass 3.2.5. I was initially mislead by the claim that it was not an issue in LibSass. This has been fixed in LibSass and will hopefully be resolved soon.

```
Error: Duplicate key "within a toolbar" in map (in an alert: toolbar).
        on line 17 of test.scss
>> $tmp: ( in an alert: alert, within a toolbar: toolbar );
```

**Comment by eoneill** [comment] 2015-08-17 17:20
I was able to confirm that pointing my `package.json` to `node-sass` `HEAD` fixed the issue, so it looks like the next release should resolve this.

Apologies for the inaccurate info re: working in libsass 3.2.5. I had test via codepen.io / sassmeister.com which claimed to be using 3.2.5, but should have verified locally.

Feel free to close this ticket per your workflow as the issue seems to already be resolved, just not released.

Thanks again!

**Comment by xzyfer** [comment] 2015-10-24 03:29
Fixed in https://github.com/sass/node-sass/pull/1214. Will be in v3.4.0.

**Closed by xzyfer** 2015-10-24 03:29 UTC
Labels: Bug - Confirmed, External - LibSass
