### ISSUE TITLE
Bus error in node-sass 3.1.1

### ISSUE THREAD

**Issue by firebat** [sass/node-sass#1262] opened 2015-11-12 13:38 UTC
uname -a
    Linux debian 4.2.0-1-amd64 #1 SMP Debian 4.2.5-1 (2015-10-27) x86_64 GNU/Linux

    $ more package.json 
    {
      "name": "ui",
      "version": "0.0.0",
      "dependencies": {},
      "devDependencies": {
        "css-loader": "^0.22.0",
        "sass-loader": "^3.1.1",
        "style-loader": "^0.13.0",
        "webpack": "^1.12.3"
      }
    }

    $ cat webpack.config.js 
    module.exports = {
      entry: "./js/hello.js",
      output: {
        path: __dirname,
        filename: "bundle.js"
      },
      module: {
        loaders: [{
          test: /\.scss$/,
          loader: 'style!css!sass?sourceMap'
        }]
      }
    };

    $ cat js/hello.js 
    require("../sass/hello.scss")
    document.write("Hello");

    $ cat sass/hello.scss 
    $gray : #333;
    body {
        background: $gray;
    }

I have seen this issues fixed in 3.1.0, the bug seems happened again, and the 3.4.1 was installed so slowly.
https://github.com/sass/node-sass/issues/946

**Comment by saper** [comment] 2015-11-12 13:49
It seems to work fine with the current version, can you try with 3.4.1 (or soon to be released 3.4.2) again?

**Comment by xzyfer** [comment] 2015-12-27 07:45
Slow installs is not a bug. This bug has been fixed in recent version. Please upgrade.

**Closed by xzyfer** 2015-12-27 07:45 UTC
